/*
* This header is generated by classdump-dyld 1.0
* on Thursday, May 12, 2016 at 1:01:17 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/E107A69B-5FBA-4958-8D2E-301137467F53/Translate.app/Translate
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Translate/GOOContentViewObject.h>

@class NSString;

@interface GOOBaseContentViewObject : NSObject <GOOContentViewObject> {

	unsigned _elementKind;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) unsigned elementKind;                  //@synthesize elementKind=_elementKind - In the implementation block
-(Class)contentViewClass;
-(void)setElementKind:(unsigned)arg1 ;
-(id)init;
-(unsigned)elementKind;
@end

