/*
* This header is generated by classdump-dyld 1.0
* on Thursday, May 12, 2016 at 1:01:12 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/E107A69B-5FBA-4958-8D2E-301137467F53/Translate.app/Translate
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Translate/Translate-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UITextViewDelegate.h>
#import <Translate/GOOIndeterminateProgressBarDelegate.h>

@protocol GTRInstantTranslateViewDelegate;
@class UITextView, QTMButton, GOOIndeterminateProgressBar, NSString;

@interface GTRInstantTranslateView : UIView <UITextViewDelegate, GOOIndeterminateProgressBarDelegate> {

	UITextView* _textView;
	QTMButton* _submitButton;
	GOOIndeterminateProgressBar* _progressBar;
	NSString* _targetLanguage;
	id<GTRInstantTranslateViewDelegate> _delegate;

}

@property (nonatomic,copy) NSString * targetLanguage;                                          //@synthesize targetLanguage=_targetLanguage - In the implementation block
@property (assign,nonatomic,__weak) id<GTRInstantTranslateViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)targetLanguage;
-(void)accessibilityFontAttributesChanged:(id)arg1 ;
-(void)setTargetLanguage:(NSString *)arg1 ;
-(void)submitButtonDidPress:(id)arg1 ;
-(void)animationFinished:(id)arg1 ;
-(void)setSubmitEnabled:(char)arg1 ;
-(void)setTranslationInProgress:(char)arg1 ;
-(void)handleLongPressGesture:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<GTRInstantTranslateViewDelegate>)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(id<GTRInstantTranslateViewDelegate>)delegate;
-(void)setTranslation:(id)arg1 ;
@end

