/*
* This header is generated by classdump-dyld 1.0
* on Thursday, May 12, 2016 at 1:01:16 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/E107A69B-5FBA-4958-8D2E-301137467F53/Translate.app/Translate
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Translate/NICollectionViewModel.h>

@interface NIMutableCollectionViewModel : NICollectionViewModel
-(void)_setSectionsWithArray:(id)arg1 ;
-(id)_appendSection;
-(id)_insertSectionAtIndex:(unsigned)arg1 ;
-(id)addObject:(id)arg1 toSection:(unsigned)arg2 ;
-(id)insertObject:(id)arg1 atRow:(unsigned)arg2 inSection:(unsigned)arg3 ;
-(id)removeObjectAtIndexPath:(id)arg1 ;
-(id)addSectionWithTitle:(id)arg1 ;
-(id)insertSectionWithTitle:(id)arg1 atIndex:(unsigned)arg2 ;
-(id)addObject:(id)arg1 ;
-(id)addObjectsFromArray:(id)arg1 ;
-(id)removeSectionAtIndex:(unsigned)arg1 ;
@end

