/*
* This header is generated by classdump-dyld 1.0
* on Thursday, May 12, 2016 at 1:01:19 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/E107A69B-5FBA-4958-8D2E-301137467F53/Translate.app/Translate
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Translate/TAGPBGeneratedMessage.h>

@class NSString;

@interface TAGPGaExperimentRandom : TAGPBGeneratedMessage

@property (assign,nonatomic) char hasKey; 
@property (nonatomic,retain) NSString * key; 
@property (assign,nonatomic) char hasMinRandom; 
@property (assign,nonatomic) long long minRandom; 
@property (assign,nonatomic) char hasMaxRandom; 
@property (assign,nonatomic) long long maxRandom; 
@property (assign,nonatomic) char hasRetainOriginalValue; 
@property (assign,nonatomic) char retainOriginalValue; 
@property (assign,nonatomic) char hasLifetimeInMilliseconds; 
@property (assign,nonatomic) long long lifetimeInMilliseconds; 
+(id)descriptor;
@end

