/*
* This header is generated by classdump-dyld 1.0
* on Friday, April 22, 2016 at 10:58:10 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D8C1ED38-25E6-459D-9E28-E2C1B463D6A5/Yik Yak.app/Yik Yak
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDWebImageManagerDelegate;
@class SDImageCache, SDWebImageDownloader, NSMutableSet, NSMutableArray;

@interface SDWebImageManager : NSObject {

	id<SDWebImageManagerDelegate> _delegate;
	SDImageCache* _imageCache;
	SDWebImageDownloader* _imageDownloader;
	/*^block*/id _cacheKeyFilter;
	NSMutableSet* _failedURLs;
	NSMutableArray* _runningOperations;

}

@property (assign,nonatomic,__weak) id<SDWebImageManagerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) SDImageCache * imageCache;                                  //@synthesize imageCache=_imageCache - In the implementation block
@property (nonatomic,retain) SDWebImageDownloader * imageDownloader;                     //@synthesize imageDownloader=_imageDownloader - In the implementation block
@property (nonatomic,copy) id cacheKeyFilter;                                            //@synthesize cacheKeyFilter=_cacheKeyFilter - In the implementation block
@property (nonatomic,retain) NSMutableSet * failedURLs;                                  //@synthesize failedURLs=_failedURLs - In the implementation block
@property (nonatomic,retain) NSMutableArray * runningOperations;                         //@synthesize runningOperations=_runningOperations - In the implementation block
+(id)sharedManager;
-(id)downloadImageWithURL:(id)arg1 options:(unsigned)arg2 progress:(/*^block*/id)arg3 completed:(/*^block*/id)arg4 ;
-(id)cacheKeyForURL:(id)arg1 ;
-(id)createCache;
-(id)cacheKeyFilter;
-(NSMutableSet *)failedURLs;
-(NSMutableArray *)runningOperations;
-(SDWebImageDownloader *)imageDownloader;
-(char)cachedImageExistsForURL:(id)arg1 ;
-(char)diskImageExistsForURL:(id)arg1 ;
-(void)cachedImageExistsForURL:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)diskImageExistsForURL:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)saveImageToCache:(id)arg1 forURL:(id)arg2 ;
-(void)setImageDownloader:(SDWebImageDownloader *)arg1 ;
-(void)setCacheKeyFilter:(id)arg1 ;
-(void)setFailedURLs:(NSMutableSet *)arg1 ;
-(void)setRunningOperations:(NSMutableArray *)arg1 ;
-(id)downloadWithURL:(id)arg1 options:(unsigned)arg2 progress:(/*^block*/id)arg3 completed:(/*^block*/id)arg4 ;
-(void)setImageCache:(SDImageCache *)arg1 ;
-(SDImageCache *)imageCache;
-(void)setDelegate:(id<SDWebImageManagerDelegate>)arg1 ;
-(id)init;
-(id<SDWebImageManagerDelegate>)delegate;
-(char)isRunning;
-(void)cancelAll;
@end

