/*
* This header is generated by classdump-dyld 1.0
* on Friday, April 22, 2016 at 10:58:03 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D8C1ED38-25E6-459D-9E28-E2C1B463D6A5/Yik Yak.app/Yik Yak
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Yik Yak/BaseYaksViewController.h>

@class UISegmentedControl;

@interface SegmentedYaksViewController : BaseYaksViewController {

	char _overrodeDefaultTabIndex;
	UISegmentedControl* _segmentedControl;

}

@property (nonatomic,readonly) int currentSegmentIndex; 
@property (assign,nonatomic) char overrodeDefaultTabIndex;                       //@synthesize overrodeDefaultTabIndex=_overrodeDefaultTabIndex - In the implementation block
@property (nonatomic,retain) UISegmentedControl * segmentedControl;              //@synthesize segmentedControl=_segmentedControl - In the implementation block
-(char)overrodeDefaultTabIndex;
-(void)selectSegmentAtIndex:(unsigned)arg1 ;
-(int)currentSegmentIndex;
-(void)onYakSent:(id)arg1 ;
-(void)segmentedControlChanged:(id)arg1 wasSegmentControlTapped:(char)arg2 ;
-(void)setOverrodeDefaultTabIndex:(char)arg1 ;
-(id)yakListSegments;
-(void)viewDidLoad;
-(UISegmentedControl *)segmentedControl;
-(void)segmentedControlChanged:(id)arg1 ;
-(void)setSegmentedControl:(UISegmentedControl *)arg1 ;
@end

