/*
* This header is generated by classdump-dyld 1.0
* on Friday, April 22, 2016 at 10:58:10 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D8C1ED38-25E6-459D-9E28-E2C1B463D6A5/Yik Yak.app/Yik Yak
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface UILabelCounter : NSObject {

	float _rate;

}

@property (assign) float rate;              //@synthesize rate=_rate - In the implementation block
-(float)rate;
-(float)update:(float)arg1 ;
-(void)setRate:(float)arg1 ;
@end

