/*
* This header is generated by classdump-dyld 1.0
* on Friday, April 22, 2016 at 10:58:05 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D8C1ED38-25E6-459D-9E28-E2C1B463D6A5/Yik Yak.app/Yik Yak
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSNumber, NSString, NSDate;

@interface Yik_Yak._YYContact : NSManagedObject

@property (retain,nonatomic) NSNumber * blocked; 
@property (copy,nonatomic) NSString * identifier; 
@property (retain,nonatomic) NSDate * lastSendDate; 
@property (retain,nonatomic) NSDate * modifiedDate; 
@property (copy,nonatomic) NSString * name; 
@property (retain,nonatomic) NSNumber * numberOfPings; 
@property (copy,nonatomic) NSString * phoneNumber; 
@property (retain,nonatomic) NSNumber * status; 
+(id)entity:(id)arg1 ;
+(id)entityName;
-(id)initWithManagedObjectContext:(id)arg1 ;
-(id)initWithEntity:(id)arg1 insertIntoManagedObjectContext:(id)arg2 ;
@end

