/*
* This header is generated by classdump-dyld 1.0
* on Friday, April 22, 2016 at 10:58:05 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D8C1ED38-25E6-459D-9E28-E2C1B463D6A5/Yik Yak.app/Yik Yak
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Yik Yak/YYViewController.h>
#import <UIKit/UISearchResultsUpdating.h>
#import <Yik Yak/YYSearchResultsControllerDelegate.h>
#import <UIKit/UISearchControllerDelegate.h>

@class UISearchController, YYSearchResultsController, UIView, NSString;

@interface YYSearchableViewController : YYViewController <UISearchResultsUpdating, YYSearchResultsControllerDelegate, UISearchControllerDelegate> {

	char _didSetupConstraints;
	UISearchController* _searchController;
	YYSearchResultsController* _searchResultsController;
	UIView* _searchContainerView;

}

@property (assign,nonatomic) char didSetupConstraints;                                         //@synthesize didSetupConstraints=_didSetupConstraints - In the implementation block
@property (nonatomic,retain) UISearchController * searchController;                            //@synthesize searchController=_searchController - In the implementation block
@property (nonatomic,retain) YYSearchResultsController * searchResultsController;              //@synthesize searchResultsController=_searchResultsController - In the implementation block
@property (nonatomic,retain) UIView * searchContainerView;                                     //@synthesize searchContainerView=_searchContainerView - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)performSearchWithQuery:(id)arg1 ;
-(void)addSubviews;
-(void)searchResultsController:(id)arg1 didSelectItem:(id)arg2 ;
-(void)changeSearchBarColorToGreen;
-(void)resetSearchBarColor;
-(UIView *)searchContainerView;
-(void)setSearchContainerView:(UIView *)arg1 ;
-(void)addConstraints;
-(id)init;
-(void)viewDidLoad;
-(void)viewDidAppear:(char)arg1 ;
-(YYSearchResultsController *)searchResultsController;
-(UISearchController *)searchController;
-(void)willPresentSearchController:(id)arg1 ;
-(void)didPresentSearchController:(id)arg1 ;
-(void)willDismissSearchController:(id)arg1 ;
-(void)setSearchController:(UISearchController *)arg1 ;
-(void)updateSearchResultsForSearchController:(id)arg1 ;
-(void)setSearchResultsController:(YYSearchResultsController *)arg1 ;
-(char)didSetupConstraints;
-(void)setDidSetupConstraints:(char)arg1 ;
-(void)setupView;
@end

