/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 11, 2016 at 2:06:45 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/57E44ADD-CBC7-4349-9D9F-96F9CA56753B/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/IGFeedNetworkSourceDelegate.h>

@protocol IGAlbumSubscriptionTrayNetworkSourceDelegate;
@class IGFeedNetworkSource, IGFeedItem, NSArray, NSString;

@interface IGAlbumSubscriptionTrayNetworkSource : NSObject <IGFeedNetworkSourceDelegate> {

	int _feedFetchState;
	IGFeedNetworkSource* _feedNetworkSource;
	id<IGAlbumSubscriptionTrayNetworkSourceDelegate> _delegate;
	IGFeedItem* _currentAlbum;
	NSArray* _collaborativeAlbums;

}

@property (assign,nonatomic) int feedFetchState;                                                            //@synthesize feedFetchState=_feedFetchState - In the implementation block
@property (nonatomic,readonly) IGFeedNetworkSource * feedNetworkSource;                                     //@synthesize feedNetworkSource=_feedNetworkSource - In the implementation block
@property (assign,nonatomic,__weak) id<IGAlbumSubscriptionTrayNetworkSourceDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) IGFeedItem * currentAlbum;                                                     //@synthesize currentAlbum=_currentAlbum - In the implementation block
@property (nonatomic,retain) NSArray * collaborativeAlbums;                                                 //@synthesize collaborativeAlbums=_collaborativeAlbums - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(IGFeedItem *)currentAlbum;
-(IGFeedNetworkSource *)feedNetworkSource;
-(void)setFeedFetchState:(int)arg1 ;
-(void)setCurrentAlbum:(IGFeedItem *)arg1 ;
-(NSArray *)collaborativeAlbums;
-(void)setCollaborativeAlbums:(NSArray *)arg1 ;
-(void)resetAndFetchAgainIfNeeded;
-(int)feedFetchState;
-(void)feedNetworkSource:(id)arg1 didFinishLoadingObjects:(id)arg2 forFetchAction:(int)arg3 ;
-(void)feedNetworkSource:(id)arg1 didFailToLoadForFetchAction:(int)arg2 ;
-(void)feedNetworkSource:(id)arg1 willLoadItemsFromResponse:(id)arg2 ;
-(void)fetchDataIfNotFullyLoaded;
-(void)fetchData;
-(void)setDelegate:(id<IGAlbumSubscriptionTrayNetworkSourceDelegate>)arg1 ;
-(void)dealloc;
-(id<IGAlbumSubscriptionTrayNetworkSourceDelegate>)delegate;
-(id)initWithDelegate:(id)arg1 ;
@end

