/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 11, 2016 at 2:06:45 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/57E44ADD-CBC7-4349-9D9F-96F9CA56753B/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/IGDKDiffable.h>

@class NSArray, IGPostItem, IGUser, NSDate;

@interface IGAlbumSubscriptionTrayItemModel : NSObject <IGDKDiffable> {

	char _isCurrentOrCollaborativeAlbum;
	char _seen;
	NSArray* _albumGroup;
	IGPostItem* _item;

}

@property (nonatomic,readonly) NSArray * albumGroup;                            //@synthesize albumGroup=_albumGroup - In the implementation block
@property (nonatomic,readonly) char isCurrentOrCollaborativeAlbum;              //@synthesize isCurrentOrCollaborativeAlbum=_isCurrentOrCollaborativeAlbum - In the implementation block
@property (nonatomic,readonly) IGUser * user; 
@property (nonatomic,readonly) IGUser * lastCollaborativeUser; 
@property (nonatomic,readonly) IGPostItem * item;                               //@synthesize item=_item - In the implementation block
@property (nonatomic,readonly) char seen;                                       //@synthesize seen=_seen - In the implementation block
@property (nonatomic,readonly) NSDate * lastTakenDate; 
-(id)diffIdentifier;
-(NSArray *)albumGroup;
-(char)isCurrentOrCollaborativeAlbum;
-(id)initWithAlbumGroup:(id)arg1 isCurrentOrCollaborativeAlbum:(char)arg2 lastSeenDate:(id)arg3 ;
-(IGUser *)lastCollaborativeUser;
-(NSDate *)lastTakenDate;
-(char)seen;
-(IGUser *)user;
-(char)isEqual:(id)arg1 ;
-(IGPostItem *)item;
@end

