/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 11, 2016 at 2:06:41 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/57E44ADD-CBC7-4349-9D9F-96F9CA56753B/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IGContext;

@interface IGGLShader : NSObject {

	unsigned _shaderId;
	IGContext* _context;

}

@property (assign,nonatomic,__weak) IGContext * context;              //@synthesize context=_context - In the implementation block
@property (nonatomic,readonly) unsigned shaderId;                     //@synthesize shaderId=_shaderId - In the implementation block
-(id)initVertexShaderWithSource:(id)arg1 ;
-(id)initFragmentShaderWithSource:(id)arg1 ;
-(unsigned)shaderId;
-(id)initShaderWithSource:(id)arg1 type:(int)arg2 ;
-(void)dealloc;
-(IGContext *)context;
-(void)setContext:(IGContext *)arg1 ;
@end

