/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 11, 2016 at 2:06:47 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/57E44ADD-CBC7-4349-9D9F-96F9CA56753B/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IGImageURLProvider <NSObject,NSCoding>
@required
-(id)imageURLForWidth:(float)arg1;
-(id)thumbnailURLForAspectFillSize:(CGSize)arg1 option:(int)arg2;
-(id)imageURLForWidth:(float)arg1 option:(int)arg2;
-(id)imageURLForWidth:(float)arg1 option:(int)arg2 scale:(float)arg3;
-(id)imageURLOfAtLeastWidth:(float)arg1 scale:(float)arg2;

@end

