/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 11, 2016 at 2:06:40 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/57E44ADD-CBC7-4349-9D9F-96F9CA56753B/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, NSTimer;

@interface IGNetworkStat : NSObject {

	NSMutableArray* _rates;
	unsigned _insertionIndex;
	double _lastCaptureTime;
	unsigned _captureBytes;
	unsigned _previousCaptureBytes;
	float _currentAverage;
	double _averagedSum;
	int _samples;
	NSTimer* _sampler;
	int _currentRate;
	/*^block*/id _transferRateStatusChangeBlock;

}

@property (nonatomic,copy) id transferRateStatusChangeBlock;              //@synthesize transferRateStatusChangeBlock=_transferRateStatusChangeBlock - In the implementation block
+(id)sharedStat;
-(void)addTransferData:(unsigned)arg1 ;
-(id)transferRateStatusChangeBlock;
-(void)addTransferRate:(float)arg1 ;
-(void)notifyForNetworkStatChange;
-(void)sample:(id)arg1 ;
-(void)startSampling;
-(float)mostRecentAverageTransferRate;
-(int)mostRecentTransferRate;
-(id)mostRecentTransferRateString;
-(void)setTransferRateStatusChangeBlock:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(float)averageTransferRate;
-(void)stopSampling;
@end

