/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:57 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Twitter/CLSAnalyticsEvent.h>

@interface CLSAnalyticsApplicationLifecycleEvent : CLSAnalyticsEvent
-(id)initWithApplicationNotificationName:(id)arg1 timestamp:(unsigned long long)arg2 eventIdentifier:(id)arg3 highPriorityEventOnBackground:(char)arg4 ;
-(id)initApplicationInstalledEventWithTimestamp:(unsigned long long)arg1 eventIdentifier:(id)arg2 ;
-(id)initApplicationLaunchedEventWithTimestamp:(unsigned long long)arg1 eventIdentifier:(id)arg2 ;
-(id)initApplicationCrashedEventWithTimestamp:(unsigned long long)arg1 eventIdentifier:(id)arg2 ;
@end

