/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:23 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface T1Appearance : NSObject
+(void)_setupNavigationBarAppearance:(id)arg1 customShadowColor:(id)arg2 translucent:(char)arg3 barTintColor:(id)arg4 itemTintColor:(id)arg5 titleColor:(id)arg6 statusBarStyle:(int)arg7 ;
+(void)_setupBackButtonAppearance:(id)arg1 tintColor:(id)arg2 ;
+(void)_setupTextBarButtonItemAppearance:(id)arg1 font:(id)arg2 textTintColor:(id)arg3 ;
+(void)_setupDoneBarButtonItemFont:(id)arg1 ;
+(void)_setupImageBarButtonItemButtonAppearance:(id)arg1 imageTintColor:(id)arg2 ;
+(void)_setupProgressInNavigationAppearance:(id)arg1 progressColor:(id)arg2 trackColor:(id)arg3 ;
+(void)_setupToolbarAppearance:(id)arg1 customShadowColor:(id)arg2 barTintColor:(id)arg3 itemTintColor:(id)arg4 ;
+(void)_setupTableViewCellAppearance:(id)arg1 cellTintColor:(id)arg2 ;
+(void)_setupScopeBarAppearance:(id)arg1 strokeColor:(id)arg2 fillColor:(id)arg3 ;
+(id)_barButtonItemTextAttributesWithFont:(id)arg1 ;
+(void)setupAppearance;
@end

