/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:32 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Twitter/TFNCanvasEventHandler.h>

@protocol TFNCanvasEventHandlerDelegate;
@class TFNTwitterAccount, TFNTwitterScribeContext, TFNTwitterCardViewEventContext, NSString;

@interface T1CanvasEventHandler : NSObject <TFNCanvasEventHandler> {

	id<TFNCanvasEventHandlerDelegate> _eventHandlerDelegate;
	TFNTwitterAccount* _account;
	TFNTwitterScribeContext* _scribeContext;
	TFNTwitterCardViewEventContext* _cardViewEventContext;

}

@property (nonatomic,retain) TFNTwitterAccount * account;                                                //@synthesize account=_account - In the implementation block
@property (nonatomic,retain) TFNTwitterScribeContext * scribeContext;                                    //@synthesize scribeContext=_scribeContext - In the implementation block
@property (nonatomic,retain) TFNTwitterCardViewEventContext * cardViewEventContext;                      //@synthesize cardViewEventContext=_cardViewEventContext - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) id<TFNCanvasEventHandlerDelegate> eventHandlerDelegate;              //@synthesize eventHandlerDelegate=_eventHandlerDelegate - In the implementation block
+(void)scribeAction:(id)arg1 withAccount:(id)arg2 scribeContext:(id)arg3 ;
-(void)handleViewEvent:(id)arg1 ;
-(id<TFNCanvasEventHandlerDelegate>)eventHandlerDelegate;
-(void)setEventHandlerDelegate:(id<TFNCanvasEventHandlerDelegate>)arg1 ;
-(TFNTwitterScribeContext *)scribeContext;
-(void)setScribeContext:(TFNTwitterScribeContext *)arg1 ;
-(id)initWithAccount:(id)arg1 scribeContext:(id)arg2 cardViewEventContext:(id)arg3 ;
-(TFNTwitterCardViewEventContext *)cardViewEventContext;
-(void)setCardViewEventContext:(TFNTwitterCardViewEventContext *)arg1 ;
-(void)setAccount:(TFNTwitterAccount *)arg1 ;
-(TFNTwitterAccount *)account;
@end

