/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:30 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Twitter/Twitter-Structs.h>
#import <Twitter/T1DirectMessageAbstractConversationEntryCell.h>

@class TFNAttributedTextView, CALayer, T1DirectMessageConversationLastReadMarkerEntryDisplayModel;

@interface T1DirectMessageConversationLastReadMarkerEntryCell : T1DirectMessageAbstractConversationEntryCell {

	TFNAttributedTextView* _textLabel;
	CALayer* _leftDividerLine;
	CALayer* _rightDividerLine;

}

@property (nonatomic,readonly) T1DirectMessageConversationLastReadMarkerEntryDisplayModel * lastReadMarkerEntryDisplayModel; 
@property (nonatomic,readonly) TFNAttributedTextView * textLabel;                                                                         //@synthesize textLabel=_textLabel - In the implementation block
@property (nonatomic,readonly) CALayer * leftDividerLine;                                                                                 //@synthesize leftDividerLine=_leftDividerLine - In the implementation block
@property (nonatomic,readonly) CALayer * rightDividerLine;                                                                                //@synthesize rightDividerLine=_rightDividerLine - In the implementation block
-(void)setEntryDisplayModel:(id)arg1 ;
-(T1DirectMessageConversationLastReadMarkerEntryDisplayModel *)lastReadMarkerEntryDisplayModel;
-(CALayer *)leftDividerLine;
-(CGRect)_frameForDividerLineWithOriginX:(float)arg1 ;
-(CALayer *)rightDividerLine;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(TFNAttributedTextView *)textLabel;
@end

