/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:32 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Twitter/TFNForm.h>

@class TFNFormField, TFNBooleanItem, TFNTwitterList;

@interface T1EditListDetailsForm : TFNForm {

	TFNFormField* _nameField;
	TFNFormField* _descriptionField;
	TFNBooleanItem* _privateItem;
	TFNTwitterList* _list;

}

@property (nonatomic,retain) TFNFormField * nameField;                     //@synthesize nameField=_nameField - In the implementation block
@property (nonatomic,retain) TFNFormField * descriptionField;              //@synthesize descriptionField=_descriptionField - In the implementation block
@property (nonatomic,readonly) TFNBooleanItem * privateItem;               //@synthesize privateItem=_privateItem - In the implementation block
@property (nonatomic,readonly) TFNTwitterList * list;                      //@synthesize list=_list - In the implementation block
-(TFNBooleanItem *)privateItem;
-(TFNFormField *)descriptionField;
-(char)tracksEditsAndChanges;
-(void)setDescriptionField:(TFNFormField *)arg1 ;
-(id)sections;
-(TFNFormField *)nameField;
-(void)setNameField:(TFNFormField *)arg1 ;
-(id)initWithList:(id)arg1 ;
-(TFNTwitterList *)list;
@end

