/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:26 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Twitter/Twitter-Structs.h>
#import <Twitter/TFNFrameRateMonitorDelegate.h>

@class TFNTwitterAccount, NSString;

@interface T1FrameRateReporter : NSObject <TFNFrameRateMonitorDelegate> {

	char _enabled;
	TFNTwitterAccount* _account;
	unsigned _threshold;
	char _belowThreshold;
	unsigned _failureCount;
	SCD_Struct_T114 _onceToken;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedReporter;
-(void)enableFrameRateReporter:(char)arg1 withThreshold:(unsigned)arg2 ;
-(void)_accountActivated:(id)arg1 ;
-(void)monitor:(id)arg1 didCalculateAbsoluteFPS:(float)arg2 deltaFPS:(float)arg3 intervalSinceArmed:(double)arg4 ;
-(void)dealloc;
-(id)init;
-(void)resume;
-(void)pause;
@end

