/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:36 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Twitter/Twitter-Structs.h>
#import <UIKit/UIView.h>

@class UILabel, UITapGestureRecognizer;

@interface T1MomentErrorView : UIView {

	/*^block*/id _refreshBlock;
	UILabel* _errorLabel;
	UILabel* _subtitleLabel;
	UITapGestureRecognizer* _tapRecognizer;

}

@property (nonatomic,retain) UITapGestureRecognizer * tapRecognizer;              //@synthesize tapRecognizer=_tapRecognizer - In the implementation block
@property (nonatomic,copy) id refreshBlock;                                       //@synthesize refreshBlock=_refreshBlock - In the implementation block
@property (nonatomic,readonly) UILabel * errorLabel;                              //@synthesize errorLabel=_errorLabel - In the implementation block
@property (nonatomic,readonly) UILabel * subtitleLabel;                           //@synthesize subtitleLabel=_subtitleLabel - In the implementation block
-(void)_didTap:(id)arg1 ;
-(void)setRefreshBlock:(id)arg1 ;
-(id)refreshBlock;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(UILabel *)subtitleLabel;
-(void)setTapRecognizer:(UITapGestureRecognizer *)arg1 ;
-(UILabel *)errorLabel;
-(UITapGestureRecognizer *)tapRecognizer;
@end

