/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:26 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Twitter/Twitter-Structs.h>
#import <Twitter/T1NativeAppCardDetailsViewModel.h>
#import <Twitter/TFNTwitterCardContextModel.h>
#import <Twitter/T1PlayerCardViewModel.h>
#import <Twitter/T1NativeCardImageResourceProvider.h>

@class NSString, TFNTwitterCardContext, NSArray, TFNTwitterUser, UIImage;

@interface T1NativeMediaAppCardViewModel : NSObject <T1NativeAppCardDetailsViewModel, TFNTwitterCardContextModel, T1PlayerCardViewModel, T1NativeCardImageResourceProvider> {

	char _appRedeemEnabled;
	float _minimumRatingThreshold;
	NSArray* _starImages;
	TFNTwitterCardContext* _cardContext;
	TFNTwitterUser* _primaryUser;

}

@property (nonatomic,retain) TFNTwitterCardContext * cardContext;                                            //@synthesize cardContext=_cardContext - In the implementation block
@property (nonatomic,retain) TFNTwitterUser * primaryUser;                                                   //@synthesize primaryUser=_primaryUser - In the implementation block
@property (nonatomic,readonly) NSString * title; 
@property (nonatomic,readonly) NSString * ratingsText; 
@property (nonatomic,readonly) NSString * detailText; 
@property (nonatomic,readonly) NSString * callToAction; 
@property (nonatomic,readonly) NSArray * starImages;                                                         //@synthesize starImages=_starImages - In the implementation block
@property (nonatomic,readonly) NSString * callToActionEventType; 
@property (nonatomic,readonly) NSString * imageTapEventType; 
@property (nonatomic,readonly) int mediaType; 
@property (nonatomic,readonly) CGSize imageSize; 
@property (nonatomic,readonly) double videoDuration; 
@property (nonatomic,readonly) UIImage * avatarImage; 
@property (nonatomic,readonly) NSString * userFullName; 
@property (getter=shouldUseRoundedCorners,nonatomic,readonly) char useRoundedCorners; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) float ratingScore; 
@property (nonatomic,readonly) unsigned buttonStrength; 
@property (getter=shouldUseFixedHeight,nonatomic,readonly) char useFixedHeight; 
@property (getter=shouldShowStarsView,nonatomic,readonly) char showStarsView; 
@property (getter=shouldUseSmallStars,nonatomic,readonly) char useSmallStars; 
@property (getter=shouldShowAppCategoryLabel,nonatomic,readonly) char showAppCategoryLabel; 
@property (getter=shouldShowSubtitleLabel,nonatomic,readonly) char showSubtitleLabel; 
@property (getter=shouldRightAlignCallToAction,nonatomic,readonly) char rightAlignCallToAction; 
@property (getter=shouldUseSmallImage,nonatomic,readonly) char useSmallImage; 
@property (getter=shouldUseUnifiedDesign,nonatomic,readonly) char useUnifiedDesign; 
@property (nonatomic,readonly) char hasAppCategory; 
@property (nonatomic,readonly) float imageWidth; 
@property (nonatomic,readonly) float cornerRadius; 
@property (nonatomic,readonly) unsigned cardType; 
@property (nonatomic,readonly) NSString * appCategory; 
@property (nonatomic,copy,readonly) NSString * streamURL; 
@property (nonatomic,readonly) char isVine; 
@property (nonatomic,readonly) char isAmplify; 
@property (nonatomic,readonly) char canPlayStreamInline; 
@property (nonatomic,readonly) int playerControllerMode; 
@property (nonatomic,copy,readonly) NSString * imageURLString; 
-(char)isVine;
-(NSString *)callToAction;
-(id)initWithCardContext:(id)arg1 ;
-(char)canPlayStreamInline;
-(char)isAmplify;
-(int)playerControllerMode;
-(char)shouldUseUnifiedDesign;
-(float)ratingScore;
-(char)shouldUseSmallStars;
-(NSString *)ratingsText;
-(TFNTwitterCardContext *)cardContext;
-(NSString *)imageURLString;
-(TFNTwitterUser *)primaryUser;
-(void)setCardContext:(TFNTwitterCardContext *)arg1 ;
-(void)setPrimaryUser:(TFNTwitterUser *)arg1 ;
-(void)_userDidUpdate:(id)arg1 ;
-(UIImage *)avatarImage;
-(char)shouldShowStarsView;
-(char)shouldUseSmallImage;
-(unsigned)buttonStrength;
-(char)shouldUseFixedHeight;
-(char)shouldShowAppCategoryLabel;
-(char)shouldShowSubtitleLabel;
-(char)shouldRightAlignCallToAction;
-(char)hasAppCategory;
-(NSString *)appCategory;
-(NSString *)callToActionEventType;
-(char)_isAppRedeemable;
-(NSString *)imageTapEventType;
-(char)shouldUseRoundedCorners;
-(NSArray *)starImages;
-(NSString *)userFullName;
-(NSString *)detailText;
-(int)mediaType;
-(double)videoDuration;
-(void)dealloc;
-(NSString *)title;
-(float)cornerRadius;
-(CGSize)imageSize;
-(id)badgeImage;
-(float)imageWidth;
-(NSString *)streamURL;
-(unsigned)cardType;
@end

