/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:19 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Twitter/Twitter-Structs.h>
#import <UIKit/UIView.h>

@protocol T1PlacePageInfoViewDelegate;
@class UILabel, UIView, TFNButton;

@interface T1PlacePageInfoView : UIView {

	id<T1PlacePageInfoViewDelegate> _delegate;
	UILabel* _placeNameLabel;
	UILabel* _placeAddressLabel;
	UIView* _placeAttributionView;
	TFNButton* _ctaButton;

}

@property (nonatomic,retain) UILabel * placeNameLabel;                                     //@synthesize placeNameLabel=_placeNameLabel - In the implementation block
@property (nonatomic,retain) UILabel * placeAddressLabel;                                  //@synthesize placeAddressLabel=_placeAddressLabel - In the implementation block
@property (nonatomic,retain) UIView * placeAttributionView;                                //@synthesize placeAttributionView=_placeAttributionView - In the implementation block
@property (nonatomic,retain) TFNButton * ctaButton;                                        //@synthesize ctaButton=_ctaButton - In the implementation block
@property (assign,nonatomic,__weak) id<T1PlacePageInfoViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(UILabel *)placeAddressLabel;
-(UILabel *)placeNameLabel;
-(void)setPlaceNameLabel:(UILabel *)arg1 ;
-(void)setPlaceAddressLabel:(UILabel *)arg1 ;
-(void)_didTapCTA:(id)arg1 ;
-(UIView *)placeAttributionView;
-(TFNButton *)ctaButton;
-(void)setPlaceAttributionView:(UIView *)arg1 ;
-(void)updateWithPlace:(id)arg1 ;
-(void)setCtaButton:(TFNButton *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<T1PlacePageInfoViewDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<T1PlacePageInfoViewDelegate>)delegate;
-(float)preferredHeight;
@end

