/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:19 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TFNUI/TFNViewController.h>
#import <Twitter/T1ProfileUserInfoViewDelegate.h>
#import <Twitter/T1ResizableHeaderSubheader.h>
#import <Twitter/TFNTwitterAuthenticated.h>

@protocol T1ProfileDataSource;
@class TFNTwitterAccount, T1ProfileUserInfoView, NSString;

@interface T1ProfileUserInfoViewController : TFNViewController <T1ProfileUserInfoViewDelegate, T1ResizableHeaderSubheader, TFNTwitterAuthenticated> {

	char _isPlaceholderVineDisplayEnabled;
	TFNTwitterAccount* _account;
	/*^block*/id _preferredHeightCheckBlock;
	id _subheaderInfo;
	id<T1ProfileDataSource> _dataSource;
	/*^block*/id _birthdayTapBlock;

}

@property (nonatomic,readonly) T1ProfileUserInfoView * infoView; 
@property (nonatomic,retain) id<T1ProfileDataSource> dataSource;                //@synthesize dataSource=_dataSource - In the implementation block
@property (assign,nonatomic) char isPlaceholderVineDisplayEnabled;              //@synthesize isPlaceholderVineDisplayEnabled=_isPlaceholderVineDisplayEnabled - In the implementation block
@property (nonatomic,copy) id birthdayTapBlock;                                 //@synthesize birthdayTapBlock=_birthdayTapBlock - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) id subheaderInfo;                                  //@synthesize subheaderInfo=_subheaderInfo - In the implementation block
@property (nonatomic,copy) id preferredHeightCheckBlock;                        //@synthesize preferredHeightCheckBlock=_preferredHeightCheckBlock - In the implementation block
@property (nonatomic,retain) TFNTwitterAccount * account;                       //@synthesize account=_account - In the implementation block
-(id)scribePage;
-(id)scribeSection;
-(void)setSubheaderInfo:(id)arg1 ;
-(id)subheaderInfo;
-(void)setPreferredHeightCheckBlock:(id)arg1 ;
-(void)scribeImpressionWithParameters:(id)arg1 ;
-(void)setIsPlaceholderVineDisplayEnabled:(char)arg1 ;
-(char)isUserProtectedFromViewingAccount;
-(void)_viewFollowersWithTab:(unsigned)arg1 ;
-(id)preferredHeightCheckBlock;
-(void)_viewFollowing;
-(id)birthdayTapBlock;
-(void)_unmuteUser:(id)arg1 ;
-(void)profileUserInfoView:(id)arg1 didTapURL:(id)arg2 ;
-(void)profileUserInfoView:(id)arg1 didLongPressURL:(id)arg2 inView:(id)arg3 ;
-(void)profileUserInfoViewDidTapFollowers:(id)arg1 ;
-(void)profileUserInfoViewDidTapFollowing:(id)arg1 ;
-(void)profileUserInfoView:(id)arg1 didTapBioActiveRange:(id)arg2 ;
-(void)profileUserInfoView:(id)arg1 didTapStructuredLocation:(id)arg2 ;
-(void)profileUserInfoViewDidTapBirthday:(id)arg1 ;
-(void)profileUserInfoView:(id)arg1 didTapVineLinkWithUrl:(id)arg2 ;
-(void)profileUserInfoView:(id)arg1 didTapUnmute:(id)arg2 ;
-(void)setBirthdayTapBlock:(id)arg1 ;
-(void)showFollowersWithTab:(unsigned)arg1 ;
-(char)isPlaceholderVineDisplayEnabled;
-(void)_fontSizeDidChange;
-(id)scribe;
-(T1ProfileUserInfoView *)infoView;
-(void)setDataSource:(id<T1ProfileDataSource>)arg1 ;
-(void)dealloc;
-(void)reloadData;
-(id)init;
-(id<T1ProfileDataSource>)dataSource;
-(void)loadView;
-(void)viewDidLayoutSubviews;
-(void)viewWillAppear:(char)arg1 ;
-(float)preferredHeight;
-(void)setAccount:(TFNTwitterAccount *)arg1 ;
-(TFNTwitterAccount *)account;
@end

