/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:21 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol T1StatusViewInlineImages <NSObject>
@required
-(id)imageViewAtIndex:(int)arg1;
-(CGRect*)imageContentsRectAtIndex:(int)arg1;
-(int)imageContentModeAtIndex:(int)arg1;
-(char)hasAnyVisibleImageBeenDownloaded;
-(void)animateImageWithKenBurnsAnimationType:(unsigned)arg1 duration:(double)arg2 zoomScale:(float)arg3 presentationLayer:(id)arg4;
-(void)animateImagesWithSlideshowDuration:(double)arg1 imageIndex:(int)arg2 startingOpacity:(float)arg3 endingOpacity:(float)arg4;
-(id)imageAtIndex:(int)arg1;

@end

