/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:29 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TFNUI/TNLRequestDelegate.h>
#import <Twitter/TFNTwitterAuthenticated.h>

@class TFNTwitterAccount, NSURL, TFNTwitterEntityURL, TFNTwitterStatus, T1TalonURLUnwrapperPerformanceLogger, NSString;

@interface T1TalonURLUnwrapper : NSObject <TNLRequestDelegate, TFNTwitterAuthenticated> {

	char _tcoURLhost;
	TFNTwitterAccount* _account;
	NSURL* _URL;
	TFNTwitterEntityURL* _entityURL;
	TFNTwitterStatus* _status;
	T1TalonURLUnwrapperPerformanceLogger* _logger;

}

@property (nonatomic,retain) NSURL * URL;                                                  //@synthesize URL=_URL - In the implementation block
@property (nonatomic,retain) TFNTwitterEntityURL * entityURL;                              //@synthesize entityURL=_entityURL - In the implementation block
@property (nonatomic,retain) TFNTwitterStatus * status;                                    //@synthesize status=_status - In the implementation block
@property (nonatomic,readonly) char canBeUnwrapped; 
@property (nonatomic,readonly) char shouldUnwrapCompletely; 
@property (getter=isTcoURLHost,nonatomic,readonly) char tcoURLhost;                        //@synthesize tcoURLhost=_tcoURLhost - In the implementation block
@property (nonatomic,readonly) T1TalonURLUnwrapperPerformanceLogger * logger;              //@synthesize logger=_logger - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) TFNTwitterAccount * account;                                  //@synthesize account=_account - In the implementation block
-(TFNTwitterEntityURL *)entityURL;
-(void)setEntityURL:(TFNTwitterEntityURL *)arg1 ;
-(char)isTcoURLHost;
-(char)canBeUnwrapped;
-(void)_unwrapFromCacheWithCompletion:(/*^block*/id)arg1 logger:(id)arg2 ;
-(void)_unwrapFromAPIWithCompletion:(/*^block*/id)arg1 logger:(id)arg2 ;
-(char)shouldUnwrapCompletely;
-(void)_saveMetadataToEntity:(id)arg1 ;
-(void)_pingHopURL:(id)arg1 ;
-(id)initWithTwitterURL:(id)arg1 status:(id)arg2 account:(id)arg3 ;
-(void)unwrapInAppBrowserRequestWithCompletionBlock:(/*^block*/id)arg1 ;
-(id)externalBrowserURL;
-(void)pingIntermediateHops;
-(void)requestOperation:(id)arg1 didCompleteWithResponse:(id)arg2 ;
-(T1TalonURLUnwrapperPerformanceLogger *)logger;
-(id)_requestForURL:(id)arg1 ;
-(id)init;
-(NSURL *)URL;
-(void)setURL:(NSURL *)arg1 ;
-(TFNTwitterStatus *)status;
-(void)setStatus:(TFNTwitterStatus *)arg1 ;
-(void)setAccount:(TFNTwitterAccount *)arg1 ;
-(TFNTwitterAccount *)account;
@end

