/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:50 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Twitter/Twitter-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableDictionary, UIFont, UIColor;

@interface TFNFormAppearance : NSObject <NSCopying> {

	NSMutableDictionary* _fieldBackgroundImages;
	NSMutableDictionary* _separatorCoverImages;
	char _insetSeparator;
	char _fullWidth;
	char _overlapped;
	float _margin;
	float _lineSpacing;
	float _fieldSpacing;
	float _fieldBorderWidth;
	UIFont* _customItemFont;
	UIColor* _backgroundColor;
	UIColor* _highlightedBackgroundColor;
	UIColor* _inputDisabledBackgroundColor;
	UIColor* _borderColor;
	UIEdgeInsets _sectionInset;

}

@property (assign,nonatomic) float margin;                                          //@synthesize margin=_margin - In the implementation block
@property (assign,nonatomic) float lineSpacing;                                     //@synthesize lineSpacing=_lineSpacing - In the implementation block
@property (assign,nonatomic) float fieldSpacing;                                    //@synthesize fieldSpacing=_fieldSpacing - In the implementation block
@property (assign,nonatomic) float fieldBorderWidth;                                //@synthesize fieldBorderWidth=_fieldBorderWidth - In the implementation block
@property (assign,nonatomic) UIEdgeInsets sectionInset;                             //@synthesize sectionInset=_sectionInset - In the implementation block
@property (assign,nonatomic) char insetSeparator;                                   //@synthesize insetSeparator=_insetSeparator - In the implementation block
@property (assign,getter=isFullWidth,nonatomic) char fullWidth;                     //@synthesize fullWidth=_fullWidth - In the implementation block
@property (assign,getter=isOverlapped,nonatomic) char overlapped;                   //@synthesize overlapped=_overlapped - In the implementation block
@property (nonatomic,readonly) UIColor * borderColor;                               //@synthesize borderColor=_borderColor - In the implementation block
@property (nonatomic,readonly) UIFont * customItemFont;                             //@synthesize customItemFont=_customItemFont - In the implementation block
@property (nonatomic,readonly) UIColor * backgroundColor;                           //@synthesize backgroundColor=_backgroundColor - In the implementation block
@property (nonatomic,readonly) UIColor * highlightedBackgroundColor;                //@synthesize highlightedBackgroundColor=_highlightedBackgroundColor - In the implementation block
@property (nonatomic,readonly) UIColor * inputDisabledBackgroundColor;              //@synthesize inputDisabledBackgroundColor=_inputDisabledBackgroundColor - In the implementation block
+(id)basicAppearance;
+(id)fullWidthAppearanceInsetSeparator:(char)arg1 ;
-(UIColor *)highlightedBackgroundColor;
-(id)fieldBackgroundImageForSectionBreaks:(unsigned)arg1 highlighted:(char)arg2 inputDisabled:(char)arg3 ;
-(id)validityIndicatorImageForFormField:(id)arg1 validityState:(unsigned)arg2 ;
-(void)setInsetSeparator:(char)arg1 ;
-(float)fieldBorderWidth;
-(UIColor *)inputDisabledBackgroundColor;
-(char)insetSeparator;
-(id)separatorCoverImageForSectionBreaks:(unsigned)arg1 inset:(float)arg2 ;
-(void)setFieldBorderWidth:(float)arg1 ;
-(UIFont *)customItemFont;
-(char)isOverlapped;
-(void)setOverlapped:(char)arg1 ;
-(UIColor *)backgroundColor;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(float)lineSpacing;
-(void)setLineSpacing:(float)arg1 ;
-(UIColor *)borderColor;
-(void)setMargin:(float)arg1 ;
-(float)margin;
-(void)setSectionInset:(UIEdgeInsets)arg1 ;
-(UIEdgeInsets)sectionInset;
-(char)isFullWidth;
-(void)setFullWidth:(char)arg1 ;
-(void)setFieldSpacing:(float)arg1 ;
-(float)fieldSpacing;
@end

