/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:45 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSString, TFNStopwatch, NSMutableArray, NSObject;

@interface TFNTwitterScribeNetworkOperation : NSObject {

	unsigned _type;
	NSString* _retryPolicyId;
	unsigned _status;
	TFNStopwatch* _stopwatch;
	int _retryCount;
	NSMutableArray* _requests;
	NSObject*<OS_dispatch_queue> _requestsAccessQueue;
	NSString* _context;
	long long _operationId;
	double _duration;

}

@property (assign,nonatomic) unsigned type;                                                 //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) long long operationId;                                         //@synthesize operationId=_operationId - In the implementation block
@property (nonatomic,copy) NSString * retryPolicyId;                                        //@synthesize retryPolicyId=_retryPolicyId - In the implementation block
@property (assign,nonatomic) unsigned status;                                               //@synthesize status=_status - In the implementation block
@property (nonatomic,retain) TFNStopwatch * stopwatch;                                      //@synthesize stopwatch=_stopwatch - In the implementation block
@property (assign,nonatomic) double duration;                                               //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) int retryCount;                                                //@synthesize retryCount=_retryCount - In the implementation block
@property (nonatomic,retain) NSMutableArray * requests;                                     //@synthesize requests=_requests - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> requestsAccessQueue;              //@synthesize requestsAccessQueue=_requestsAccessQueue - In the implementation block
@property (nonatomic,copy) NSString * context;                                              //@synthesize context=_context - In the implementation block
+(id)operationWithType:(unsigned)arg1 httpRequestConfiguration:(id)arg2 ;
+(id)operationWithType:(unsigned)arg1 retryPolicy:(id)arg2 timeout:(double)arg3 packetTimeout:(double)arg4 ;
-(id)scribeParameters;
-(TFNStopwatch *)stopwatch;
-(void)setStopwatch:(TFNStopwatch *)arg1 ;
-(NSString *)retryPolicyId;
-(id)initWithType:(unsigned)arg1 retryPolicyId:(id)arg2 context:(id)arg3 ;
-(id)initWithType:(unsigned)arg1 retryPolicy:(id)arg2 timeout:(double)arg3 packetTimeout:(double)arg4 ;
-(void)_addRequest:(id)arg1 ;
-(id)_requests;
-(void)setRetryPolicyId:(NSString *)arg1 ;
-(id)thriftEvent;
-(void)addTNLResponse:(id)arg1 ;
-(void)endWithStatus:(unsigned)arg1 ;
-(char)hasRequests;
-(NSObject*<OS_dispatch_queue>)requestsAccessQueue;
-(void)setRequestsAccessQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)init;
-(double)duration;
-(void)setDuration:(double)arg1 ;
-(void)setType:(unsigned)arg1 ;
-(unsigned)type;
-(NSString *)context;
-(void)start;
-(void)setContext:(NSString *)arg1 ;
-(unsigned)status;
-(void)setStatus:(unsigned)arg1 ;
-(char)isStarted;
-(void)setRetryCount:(int)arg1 ;
-(int)retryCount;
-(void)addRequest:(id)arg1 ;
-(NSMutableArray *)requests;
-(void)setRequests:(NSMutableArray *)arg1 ;
-(long long)operationId;
-(void)setOperationId:(long long)arg1 ;
@end

