/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 9:31:53 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8A9DE0F0-8C0D-4043-A8B5-545C839396E1/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface TFNTwitterSearchActivity : NSObject {

	float _maxScore;
	float _minScore;
	unsigned _numIntervals;
	NSArray* _histogramIntervals;
	NSArray* _eventIntervals;

}

@property (assign,nonatomic) unsigned numIntervals;                       //@synthesize numIntervals=_numIntervals - In the implementation block
@property (nonatomic,readonly) float maxScore; 
@property (nonatomic,readonly) float minScore; 
@property (nonatomic,readonly) NSArray * histogramIntervals;              //@synthesize histogramIntervals=_histogramIntervals - In the implementation block
@property (nonatomic,readonly) NSArray * eventIntervals;                  //@synthesize eventIntervals=_eventIntervals - In the implementation block
+(id)activityWithJSONDictionary:(id)arg1 ;
-(id)initWithJSONDictionary:(id)arg1 ;
-(void)setNumIntervals:(unsigned)arg1 ;
-(unsigned)numIntervals;
-(NSArray *)histogramIntervals;
-(float)minScore;
-(float)maxScore;
-(NSArray *)eventIntervals;
@end

