/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 27, 2016 at 5:25:08 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/18A47B54-BBB4-452D-8D90-8FE53FA433AA/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IGFeedItemVideoViewDelegate <NSObject>
@required
-(void)feedItemVideoViewDidRequestVideoPlayback:(id)arg1;
-(void)feedItemVideoView:(id)arg1 didFailToPlayWithError:(id)arg2;
-(void)feedItemVideoViewDidDoubleTap:(id)arg1;
-(void)feedItemVideoViewDidLoadImage:(id)arg1;
-(void)feedItemVideoViewDidPlay:(id)arg1;
-(void)feedItemVideoViewDidPauseWithEmptyBuffer:(id)arg1;
-(void)feedItemVideoViewDidPlayToEnd:(id)arg1;
-(void)feedItemVideoViewDidLongPress:(id)arg1;
-(void)feedItemVideoView:(id)arg1 didToggleAudio:(char)arg2;

@end

