/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 27, 2016 at 5:25:15 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/18A47B54-BBB4-452D-8D90-8FE53FA433AA/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UIView.h>

@protocol IGInsightsContentRowListViewDelegate;
@class UIButton, UIView, NSArray;

@interface IGInsightsContentRowListView : UIView {

	char _showDetails;
	id<IGInsightsContentRowListViewDelegate> _delegate;
	UIButton* _textbutton;
	UIButton* _chevronbutton;
	UIView* _bottomSeparator;
	NSArray* _listItemViews;

}

@property (assign,nonatomic) char showDetails;                                                      //@synthesize showDetails=_showDetails - In the implementation block
@property (assign,nonatomic,__weak) id<IGInsightsContentRowListViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) UIButton * textbutton;                                               //@synthesize textbutton=_textbutton - In the implementation block
@property (nonatomic,readonly) UIButton * chevronbutton;                                            //@synthesize chevronbutton=_chevronbutton - In the implementation block
@property (nonatomic,readonly) UIView * bottomSeparator;                                            //@synthesize bottomSeparator=_bottomSeparator - In the implementation block
@property (nonatomic,copy) NSArray * listItemViews;                                                 //@synthesize listItemViews=_listItemViews - In the implementation block
-(void)buttonClick:(id)arg1 ;
-(void)initializeTextButtonWithTitle:(id)arg1 ;
-(void)initializeChevronButton;
-(void)initializeListItemViewsWithParagraphUnits:(id)arg1 ;
-(char)showDetails;
-(float)getDeltaHeightForSize:(CGSize)arg1 ;
-(NSArray *)listItemViews;
-(UIButton *)textbutton;
-(UIButton *)chevronbutton;
-(void)layoutListItemViewsWithCurrentY:(float)arg1 ;
-(void)flipChevronButton;
-(void)animateCollapse;
-(void)animateExpand;
-(void)initializeBottomSeparator;
-(void)buttonClickInFilterSelectorView;
-(void)setListItemViews:(NSArray *)arg1 ;
-(id)initWithTitle:(id)arg1 paragraphUnits:(id)arg2 ;
-(void)setShowDetails:(char)arg1 ;
-(void)setDelegate:(id<IGInsightsContentRowListViewDelegate>)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<IGInsightsContentRowListViewDelegate>)delegate;
-(UIView *)bottomSeparator;
@end

