/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 27, 2016 at 5:24:59 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/18A47B54-BBB4-452D-8D90-8FE53FA433AA/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface IGKVOHandle : NSObject {

	char _stoppedObserving;
	/*^block*/id _block;
	id _object;
	NSString* _keyPath;

}

@property (nonatomic,copy) id block;                        //@synthesize block=_block - In the implementation block
@property (assign,nonatomic,__weak) id object;              //@synthesize object=_object - In the implementation block
@property (nonatomic,copy) NSString * keyPath;              //@synthesize keyPath=_keyPath - In the implementation block
-(id)initWithBlock:(/*^block*/id)arg1 object:(id)arg2 keyPath:(id)arg3 ;
-(id)block;
-(void)setBlock:(id)arg1 ;
-(void)dealloc;
-(id)object;
-(NSString *)keyPath;
-(void)setKeyPath:(NSString *)arg1 ;
-(void)setObject:(id)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)stopObserving;
@end

