/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 27, 2016 at 5:25:02 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/18A47B54-BBB4-452D-8D90-8FE53FA433AA/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Instagram/Instagram-Structs.h>
@class CMMotionManager, NSOperationQueue;

@interface IGStabilizationSampler : NSObject {

	CMMotionManager* _motionManager;
	NSOperationQueue* _gyroQueue;
	OpaqueCMClockRef _audioClock;
	OpaqueCMClockRef _videoClock;
	circular_buffer<IGGyroSample, std::__1::allocator<IGGyroSample> >* _prerecordedGyroTrack;
	vector<IGGyroSample, std::__1::allocator<IGGyroSample> >* _gyroTrack;
	vector<IGFrameSample, std::__1::allocator<IGFrameSample> >* _frameTrack;
	char _isSampling;

}
-(void)startSampling;
-(id)gyroTrack;
-(id)frameMetadataTrack;
-(void)dealloc;
-(id)init;
-(void)processSampleBuffer:(opaqueCMSampleBufferRef)arg1 ;
-(void)stopSampling;
@end

