/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 27, 2016 at 5:25:09 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/18A47B54-BBB4-452D-8D90-8FE53FA433AA/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/IGVideoRequestDelegate.h>
#import <libobjc.A.dylib/AVAssetResourceLoaderDelegate.h>
#import <Instagram/IGVideoProxyProtocol.h>

@protocol IGVideoProxyDelegate, OS_dispatch_queue;
@class NSMutableDictionary, NSMutableSet, NSObject, NSString;

@interface IGVideoProxy : NSObject <IGVideoRequestDelegate, AVAssetResourceLoaderDelegate, IGVideoProxyProtocol> {

	NSMutableDictionary* _requestsForURL;
	NSMutableDictionary* _listeners;
	NSMutableSet* _whiteListedRemoteURLs;
	id<IGVideoProxyDelegate> _delegate;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                    //@synthesize queue=_queue - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) id<IGVideoProxyDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(id)sharedProxy;
+(id)remoteURLforProxyURL:(id)arg1 ;
+(void)updateContentInformationRequest:(id)arg1 header:(id)arg2 ;
-(id)proxyURLForURL:(id)arg1 ;
-(void)addWhiteListedURL:(id)arg1 ;
-(void)removeWhiteListedURL:(id)arg1 ;
-(void)cancelVideoRequestForURL:(id)arg1 ;
-(void)handlePlaybackErrorForURL:(id)arg1 ;
-(void)onAppDidEnterBackground;
-(void)cancelMediaLoaderRequestForURL:(id)arg1 ;
-(id)videoRequestForURL:(id)arg1 ;
-(void)videoRequestDidEnd:(id)arg1 error:(id)arg2 ;
-(void)startVideoRequestForURL:(id)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)setDelegate:(id<IGVideoProxyDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(id<IGVideoProxyDelegate>)delegate;
-(void)stopAllRequests;
-(char)resourceLoader:(id)arg1 shouldWaitForLoadingOfRequestedResource:(id)arg2 ;
-(void)resourceLoader:(id)arg1 didCancelLoadingRequest:(id)arg2 ;
@end

