/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:50:05 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <YouTube/EXODASHMPDFilter.h>

@protocol EXODASHMPDFilter <NSObject>
@required
-(char)acceptsAdaptationSet:(id)arg1;
-(char)acceptsRepresentation:(id)arg1;

@end


@class NSString;

@interface EXODASHMPDFilter : NSObject <EXODASHMPDFilter> {

	/*^block*/id _adaptationSetFilter;
	/*^block*/id _representationFilter;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)filterAcceptingAudioContentTypes;
+(id)filterAcceptingVideoContentTypes;
+(id)filterAcceptingEverything;
-(id)initWithAdaptationSetFilter:(/*^block*/id)arg1 representationFilter:(/*^block*/id)arg2 ;
-(char)acceptsAdaptationSet:(id)arg1 ;
-(char)acceptsRepresentation:(id)arg1 ;
-(id)init;
@end

