/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:50:06 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <YouTube/EXOBuildableObjectBuilder.h>

@class NSString;

@interface EXOFormatBuilder : EXOBuildableObjectBuilder {

	NSString* _ID;
	NSString* _MIMEType;
	unsigned _width;
	unsigned _height;
	long long _bitrate;
	double _fps;

}

@property (nonatomic,retain) NSString * ID;                    //@synthesize ID=_ID - In the implementation block
@property (nonatomic,retain) NSString * MIMEType;              //@synthesize MIMEType=_MIMEType - In the implementation block
@property (assign,nonatomic) long long bitrate;                //@synthesize bitrate=_bitrate - In the implementation block
@property (assign,nonatomic) unsigned width;                   //@synthesize width=_width - In the implementation block
@property (assign,nonatomic) unsigned height;                  //@synthesize height=_height - In the implementation block
@property (assign,nonatomic) double fps;                       //@synthesize fps=_fps - In the implementation block
-(void)setFps:(double)arg1 ;
-(double)fps;
-(void)setMIMEType:(NSString *)arg1 ;
-(id)init;
-(unsigned)width;
-(unsigned)height;
-(NSString *)MIMEType;
-(void)setWidth:(unsigned)arg1 ;
-(void)setHeight:(unsigned)arg1 ;
-(NSString *)ID;
-(void)setID:(NSString *)arg1 ;
-(id)build;
-(void)setBitrate:(long long)arg1 ;
-(long long)bitrate;
@end

