/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:50:05 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class EXOFormat, NSDictionary, EXONetworkStats, EXOViewportSize;

@interface EXOFormatSelection : NSObject {

	EXOFormat* _format;
	NSDictionary* _userInfo;

}

@property (nonatomic,readonly) EXOFormat * format;                          //@synthesize format=_format - In the implementation block
@property (nonatomic,readonly) NSDictionary * userInfo;                     //@synthesize userInfo=_userInfo - In the implementation block
@property (nonatomic,readonly) int reason; 
@property (nonatomic,readonly) EXONetworkStats * networkStats; 
@property (nonatomic,readonly) EXOViewportSize * viewportSize; 
@property (nonatomic,readonly) double readaheadBufferDuration; 
-(EXONetworkStats *)networkStats;
-(id)initWithFormat:(id)arg1 userInfo:(id)arg2 ;
-(double)readaheadBufferDuration;
-(EXOFormat *)format;
-(EXOViewportSize *)viewportSize;
-(id)init;
-(NSDictionary *)userInfo;
-(id)initWithFormat:(id)arg1 ;
-(int)reason;
@end

