/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:07 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <YouTube/YouTube-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSCoding.h>

@class NSURL;

@interface GCKImage : NSObject <NSCopying, NSCoding> {

	NSURL* _URL;
	int _width;
	int _height;

}

@property (nonatomic,readonly) NSURL * URL;              //@synthesize URL=_URL - In the implementation block
@property (nonatomic,readonly) int width;                //@synthesize width=_width - In the implementation block
@property (nonatomic,readonly) int height;               //@synthesize height=_height - In the implementation block
-(id)initWithURL:(id)arg1 width:(int)arg2 height:(int)arg3 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(int)width;
-(int)height;
-(NSURL *)URL;
-(id)JSONObject;
-(id)initWithJSONObject:(id)arg1 ;
@end

