/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:25 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <YouTube/GHKWebViewController.h>

@interface GHKSurveyContactFormWebViewController : GHKWebViewController
-(id)initWithHTMLString:(id)arg1 baseURL:(id)arg2 title:(id)arg3 ;
-(void)GHK_didTapBackButton;
-(void)didTapCloseButton;
-(void)viewDidLoad;
-(char)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3 ;
@end

