/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:13 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, NSArray;

@interface GIPAppParser : NSObject {

	NSDictionary* _dictionary;
	NSArray* _tldList;

}
+(id)appParserWithDictionary:(id)arg1 tldList:(id)arg2 ;
-(id)initWithDictionary:(id)arg1 tldList:(id)arg2 ;
-(id)parseName;
-(id)parseLocalizedNames;
-(id)parseBundleIdentifier;
-(int)parsePriority;
-(char)parseSystemApp;
-(id)parseStoreId;
-(id)parseTags;
-(id)parseSchemesMapping;
-(id)parseMappingVersions;
-(id)parseAdditionalData;
-(char)parseAuthUserEnabled;
-(char)parseGoogleOwnedApp;
-(id)parseAppIcons;
-(id)init;
@end

