/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:24 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MDXResources : NSObject
+(id)castConnectedImageWithColor:(id)arg1 ;
+(id)imageWithName:(id)arg1 color:(id)arg2 ;
+(id)qtmImageWithName:(id)arg1 color:(id)arg2 ;
+(id)mdxMiniPlayerLogoImageView;
+(id)actionsheetCastConnectedImage;
+(id)actionsheetCastDisconnectedImage;
+(id)castDiconnectedTvImageWithColor:(id)arg1 ;
+(id)castConnectedTvImageWithColor:(id)arg1 ;
+(id)castDiconnectedSwitchImage;
+(id)castConnectedSwitchImage;
+(id)castDisconnectedImageWithColor:(id)arg1 ;
+(void)initialize;
+(void)flushCache;
@end

