/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:36 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <YouTube/MLQoEPeriodicStatsSnapshot.h>

@class NSDate;

@interface MLAVAccessLogSnapshot : MLQoEPeriodicStatsSnapshot {

	unsigned _index;
	NSDate* _switchDate;
	int _itag;
	double _segmentsDownloadedDuration;

}

@property (nonatomic,readonly) unsigned index;                                 //@synthesize index=_index - In the implementation block
@property (nonatomic,readonly) NSDate * switchDate;                            //@synthesize switchDate=_switchDate - In the implementation block
@property (nonatomic,readonly) int itag;                                       //@synthesize itag=_itag - In the implementation block
@property (nonatomic,readonly) double segmentsDownloadedDuration;              //@synthesize segmentsDownloadedDuration=_segmentsDownloadedDuration - In the implementation block
+(id)snapshotWithItag:(int)arg1 accessLogEvent:(id)arg2 atIndex:(unsigned)arg3 ;
+(id)snapshotWithAccessLogEvent:(id)arg1 atIndex:(unsigned)arg2 ;
-(int)itag;
-(id)changeSinceSnapshot:(id)arg1 ;
-(id)initWithIndex:(unsigned)arg1 switchDate:(id)arg2 itag:(int)arg3 bytesTransferred:(unsigned long long)arg4 transferDuration:(double)arg5 segmentsDownloadedDuration:(double)arg6 droppedFrames:(unsigned)arg7 ;
-(id)initWithBytesTransferred:(unsigned long long)arg1 transferDuration:(double)arg2 droppedFrames:(unsigned)arg3 ;
-(char)isEqualToSnapshot:(id)arg1 ;
-(id)formatSelectionMeasurementWithAbsoluteTime:(double)arg1 QoEFormatData:(id)arg2 audioTrack:(id)arg3 viewportSize:(id)arg4 reason:(int)arg5 ;
-(NSDate *)switchDate;
-(double)segmentsDownloadedDuration;
-(id)init;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(unsigned)index;
@end

