/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:36 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSString, MLLocalStreamEntity;

@interface MLLocalSegmentEntity : NSManagedObject

@property (assign,nonatomic) int index; 
@property (assign,nonatomic) long long size; 
@property (assign,nonatomic) double duration; 
@property (nonatomic,copy) NSString * filename; 
@property (assign,nonatomic) char complete; 
@property (nonatomic,retain) MLLocalStreamEntity * stream; 
-(id)localSegment;
@end

