/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:50:07 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSMutableSet;

@interface NIActions : NSObject {

	id _target;
	NSMutableDictionary* _objectToAction;
	NSMutableDictionary* _classToAction;
	NSMutableSet* _objectSet;

}

@property (assign,nonatomic,__weak) id target;                                  //@synthesize target=_target - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * objectToAction;              //@synthesize objectToAction=_objectToAction - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * classToAction;               //@synthesize classToAction=_classToAction - In the implementation block
@property (nonatomic,retain) NSMutableSet * objectSet;                          //@synthesize objectSet=_objectSet - In the implementation block
+(id)objectFromKeyClass:(Class)arg1 map:(id)arg2 ;
-(id)attachToObject:(id)arg1 navigationSelector:(SEL)arg2 ;
-(void)attachToClass:(Class)arg1 tapSelector:(SEL)arg2 ;
-(id)attachToObject:(id)arg1 tapSelector:(SEL)arg2 ;
-(char)isObjectActionable:(id)arg1 ;
-(id)actionForObjectOrClassOfObject:(id)arg1 ;
-(NSMutableSet *)objectSet;
-(NSMutableDictionary *)objectToAction;
-(NSMutableDictionary *)classToAction;
-(id)actionForObject:(id)arg1 ;
-(id)actionForClass:(Class)arg1 ;
-(unsigned)attachedActionTypesForObject:(id)arg1 ;
-(id)attachToObject:(id)arg1 tapBlock:(/*^block*/id)arg2 ;
-(id)attachToObject:(id)arg1 detailBlock:(/*^block*/id)arg2 ;
-(id)attachToObject:(id)arg1 navigationBlock:(/*^block*/id)arg2 ;
-(id)attachToObject:(id)arg1 detailSelector:(SEL)arg2 ;
-(void)attachToClass:(Class)arg1 tapBlock:(/*^block*/id)arg2 ;
-(void)attachToClass:(Class)arg1 detailBlock:(/*^block*/id)arg2 ;
-(void)attachToClass:(Class)arg1 navigationBlock:(/*^block*/id)arg2 ;
-(void)attachToClass:(Class)arg1 detailSelector:(SEL)arg2 ;
-(void)attachToClass:(Class)arg1 navigationSelector:(SEL)arg2 ;
-(void)setObjectToAction:(NSMutableDictionary *)arg1 ;
-(void)setClassToAction:(NSMutableDictionary *)arg1 ;
-(void)setObjectSet:(NSMutableSet *)arg1 ;
-(id)keyForObject:(id)arg1 ;
-(id)init;
-(void)setTarget:(id)arg1 ;
-(id)target;
-(id)initWithTarget:(id)arg1 ;
@end

