/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:10 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <YouTube/YouTube-Structs.h>
#import <UIKit/UICollectionReusableView.h>

@class YTFormattedStringLabel, YTFormSwitchField;

@interface YTAutonavHeaderView : UICollectionReusableView {

	YTFormattedStringLabel* _titleLabel;
	YTFormSwitchField* _autoplayToggleView;

}

@property (nonatomic,retain) YTFormSwitchField * autoplayToggleView;              //@synthesize autoplayToggleView=_autoplayToggleView - In the implementation block
+(float)preferredHeightForTitle:(id)arg1 width:(float)arg2 ;
-(YTFormSwitchField *)autoplayToggleView;
-(void)setAutoplayToggleView:(YTFormSwitchField *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setTitle:(id)arg1 ;
-(float)leftPadding;
@end

