/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:50:02 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <YouTube/YTBaseService.h>

@class YTCoreDataContext;

@interface YTBaseCoreDataStore : YTBaseService {

	YTCoreDataContext* _context;

}

@property (nonatomic,retain) YTCoreDataContext * context;              //@synthesize context=_context - In the implementation block
+(id)fetchRequestForPredicate:(id)arg1 context:(id)arg2 entityName:(id)arg3 ;
+(id)coordinatorWithModelURL:(id)arg1 databaseName:(id)arg2 wipe:(char)arg3 error:(id*)arg4 ;
-(void)performWithContextBlock:(/*^block*/id)arg1 ;
-(id)saveWithContext:(id)arg1 ;
-(void)markForRetryWithRetryable:(id)arg1 maxRetryDate:(id)arg2 userID:(id)arg3 retryTaskConfig:(id)arg4 responseBlock:(/*^block*/id)arg5 errorBlock:(/*^block*/id)arg6 ;
-(void)clearRetryStateWithRetryable:(id)arg1 responseBlock:(/*^block*/id)arg2 errorBlock:(/*^block*/id)arg3 ;
-(id)entityFromPredicate:(id)arg1 context:(id)arg2 entityName:(id)arg3 ;
-(void)performWithContextBlockAndWait:(/*^block*/id)arg1 ;
-(void)dealloc;
-(id)init;
-(YTCoreDataContext *)context;
-(id)initWithContext:(id)arg1 ;
-(void)setContext:(YTCoreDataContext *)arg1 ;
@end

