/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:37 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <YouTube/PBGeneratedMessage.h>

@class YTIFormattedString, NSData, YTIAccessibilityData, YTIBubbleHintButtonSupportedRenderers;

@interface YTIBubbleHintRenderer : PBGeneratedMessage

@property (assign,nonatomic) char hasText; 
@property (nonatomic,retain) YTIFormattedString * text; 
@property (assign,nonatomic) char hasTrackingParams; 
@property (nonatomic,retain) NSData * trackingParams; 
@property (assign,nonatomic) char hasAccessibility; 
@property (nonatomic,retain) YTIAccessibilityData * accessibility; 
@property (assign,nonatomic) char hasDetailsText; 
@property (nonatomic,retain) YTIFormattedString * detailsText; 
@property (assign,nonatomic) char hasMaxWidthPercentage; 
@property (assign,nonatomic) float maxWidthPercentage; 
@property (assign,nonatomic) char hasDismissButton; 
@property (nonatomic,retain) YTIBubbleHintButtonSupportedRenderers * dismissButton; 
@property (assign,nonatomic) char hasAcceptButton; 
@property (nonatomic,retain) YTIBubbleHintButtonSupportedRenderers * acceptButton; 
+(id)descriptor;
@end

