/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:32 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <YouTube/YTGuideServiceProtocol.h>

@protocol YTOfflineGuideUserDefaultsProtocol;
@class YTUserDefaults, NSMutableOrderedSet, NSString;

@interface YTOfflineGuideService : NSObject <YTGuideServiceProtocol> {

	YTUserDefaults*<YTOfflineGuideUserDefaultsProtocol> _userDefaults;
	NSMutableOrderedSet* _requests;

}

@property (nonatomic,readonly) NSMutableOrderedSet * requests;              //@synthesize requests=_requests - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)performEntitlementRefresh;
-(void)makeRequest:(id)arg1 refresh:(char)arg2 responseBlock:(/*^block*/id)arg3 errorBlock:(/*^block*/id)arg4 ;
-(void)clearCaches;
-(id)initWithUserDefaults:(id)arg1 ;
-(Class)responseClass;
-(NSMutableOrderedSet *)requests;
-(Class)requestClass;
@end

