/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:31 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <YouTube/YTResponderEvent.h>

@class YTCollectionViewCell;

@interface YTScrollToCellResponderEvent : YTResponderEvent {

	YTCollectionViewCell* _cell;
	unsigned _scrollPosition;

}

@property (nonatomic,readonly) YTCollectionViewCell * cell;              //@synthesize cell=_cell - In the implementation block
@property (nonatomic,readonly) unsigned scrollPosition;                  //@synthesize scrollPosition=_scrollPosition - In the implementation block
+(id)eventWithFirstResponder:(id)arg1 cell:(id)arg2 scrollPosition:(unsigned)arg3 ;
-(id)initWithFirstResponder:(id)arg1 cell:(id)arg2 scrollPosition:(unsigned)arg3 ;
-(unsigned)scrollPosition;
-(YTCollectionViewCell *)cell;
@end

