/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:12 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <YouTube/YTStyleContextResponderProvider.h>
#import <YouTube/YTResponseViewController.h>

@protocol YTServices, YTInnerTubeUIService, YTResponder, YTResponseViewController;
@class YTISearchResponse, NSError, YTPersonalizedSuggestionsController, GIMMe, UIViewController, YTMealbarPromoController, NSString;

@interface YTSearchResponseViewController : UIViewController <YTStyleContextResponderProvider, YTResponseViewController> {

	YTISearchResponse* _renderer;
	id<YTServices> _services;
	id<YTInnerTubeUIService> _service;
	NSError* _error;
	YTPersonalizedSuggestionsController* _personalizedSuggestionsController;
	id<YTResponder> _parentResponder;
	GIMMe* _gimme;
	UIViewController*<YTResponseViewController> _contentViewController;
	YTMealbarPromoController* _mealbarPromoController;

}

@property (assign,nonatomic,__weak) GIMMe * gimme;                                                           //@synthesize gimme=_gimme - In the implementation block
@property (nonatomic,retain) UIViewController*<YTResponseViewController> contentViewController;              //@synthesize contentViewController=_contentViewController - In the implementation block
@property (nonatomic,retain) YTMealbarPromoController * mealbarPromoController;                              //@synthesize mealbarPromoController=_mealbarPromoController - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * styleContext; 
@property (nonatomic,__weak,readonly) id<YTResponder> parentResponder;                                       //@synthesize parentResponder=_parentResponder - In the implementation block
-(id<YTResponder>)parentResponder;
-(GIMMe *)gimme;
-(void)setGimme:(GIMMe *)arg1 ;
-(id)initWithService:(id)arg1 parentResponder:(id)arg2 ;
-(void)loadWithModel:(id)arg1 ;
-(NSString *)styleContext;
-(void)loadDefaultContent;
-(YTMealbarPromoController *)mealbarPromoController;
-(void)setMealbarPromoController:(YTMealbarPromoController *)arg1 ;
-(char)scrollToModelMatchingBlock:(/*^block*/id)arg1 animated:(char)arg2 ;
-(void)loadWithError:(id)arg1 ;
-(void)setEmptyMessage:(id)arg1 ;
-(void)willMakeRequest:(id)arg1 ;
-(void)loadView;
-(UIViewController*<YTResponseViewController>)contentViewController;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(void)viewWillDisappear:(char)arg1 ;
-(void)setContentViewController:(UIViewController*<YTResponseViewController>)arg1 ;
@end

