/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:49:31 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/FFD4619E-59E7-49B9-AD90-0E28F5807C56/YouTube.app/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <YouTube/YTBaseInnerTubeRequestService.h>

@class YTApiaryResourceParser, GIMMe;

@interface YTWatchHistoryService : YTBaseInnerTubeRequestService {

	YTApiaryResourceParser* _clearWatchHistoryResponseParser;
	YTApiaryResourceParser* _pauseWatchHistoryResponseParser;
	YTApiaryResourceParser* _resumeWatchHistoryResponseParser;
	YTApiaryResourceParser* _getHistoryPausedStateResponseParser;
	GIMMe* _gimme;

}

@property (assign,nonatomic,__weak) GIMMe * gimme;              //@synthesize gimme=_gimme - In the implementation block
-(GIMMe *)gimme;
-(void)setGimme:(GIMMe *)arg1 ;
-(void)makeClearWatchHistoryRequestWithClickTrackingParams:(id)arg1 responseBlock:(/*^block*/id)arg2 errorBlock:(/*^block*/id)arg3 ;
-(void)getWatchHistoryStateRequest:(id)arg1 responseBlock:(/*^block*/id)arg2 errorBlock:(/*^block*/id)arg3 ;
-(void)makePauseWatchHistoryRequestWithClickTrackingParams:(id)arg1 responseBlock:(/*^block*/id)arg2 errorBlock:(/*^block*/id)arg3 ;
-(void)makeResumeWatchHistoryRequestWithClickTrackingParams:(id)arg1 responseBlock:(/*^block*/id)arg2 errorBlock:(/*^block*/id)arg3 ;
-(id)init;
@end

