/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:35:17 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/ABE77428-6C25-43C9-8AD9-E0579EF1E1DA/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WhatsApp/WAChatSessionCell.h>

@class NSLayoutConstraint, _WAChatSessionCellSideButtonsView, UIPanGestureRecognizer;

@interface _WAChatSessionCellModern : WAChatSessionCell {

	NSLayoutConstraint* _containerViewRightToContentViewConstraint;
	NSLayoutConstraint* _messageContainerToNameLabelConstraint;
	NSLayoutConstraint* _messageContainerToSenderLabelConstraint;
	_WAChatSessionCellSideButtonsView* _rightSideButtonsView;
	_WAChatSessionCellSideButtonsView* _leftSideButtonsView;
	unsigned _archiveButtonIndex;
	unsigned _markUnreadButtonIndex;
	UIPanGestureRecognizer* _cellSwipeGesture;
	int _cellSwipeState;
	float _sideButtonsViewBaseWidth;
	float _currentSideButtonsViewWidthChange;
	float _initialGestureTranslation;
	char _isRTLLayout;

}
+(char)moreOptionsMenuSupported;
+(id)buttonInView:(id)arg1 ;
+(void)initialize;
-(void)setArchived:(char)arg1 ;
-(void)reloadFonts;
-(void)configureWithChatSession:(id)arg1 message:(id)arg2 ;
-(char)isResizingSideButtons;
-(void)cancelResizingSideButtons;
-(void)hideSideButtonsAnimated:(char)arg1 completion:(/*^block*/id)arg2 ;
-(void)markUnreadAction:(id)arg1 ;
-(void)showMoreOptions:(id)arg1 ;
-(void)archiveAction:(id)arg1 ;
-(void)handleCellSideSwipe:(id)arg1 ;
-(void)addAutolayoutConstraints;
-(void)updateContentViewHorizontalPosition;
-(void)reloadMessageTextWithMessage:(id)arg1 ;
-(void)reloadTitleOfMarkUnreadButton;
-(void)beganChangingSideButtons;
-(void)expandOrCollapseLeftSideButtonsIfNecessary;
-(void)expandOrCollapseRightSideButtonsIfNecessary;
-(void)endRightSwipeWithGestureRecognizerState:(int)arg1 ;
-(void)endLeftSwipeWithGestureRecognizerState:(int)arg1 ;
-(void)endedChangingSideButtons;
-(id)accessoryButton;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(char)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
-(void)tintColorDidChange;
-(void)prepareForReuse;
-(void)willTransitionToState:(unsigned)arg1 ;
-(id)accessibilityCustomActions;
-(void)setUnreadCount:(int)arg1 ;
@end

