/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:35:23 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/ABE77428-6C25-43C9-8AD9-E0579EF1E1DA/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UILabel.h>

@class NSTimer, NSString;

@interface WAAlternatingLabel : UILabel {

	NSTimer* _timer;
	int _index;
	NSString* _primaryText;
	NSString* _secondaryText;
	double _interval;

}

@property (nonatomic,copy) NSString * primaryText;                           //@synthesize primaryText=_primaryText - In the implementation block
@property (nonatomic,copy) NSString * secondaryText;                         //@synthesize secondaryText=_secondaryText - In the implementation block
@property (assign,getter=isAnimating,nonatomic) char animating; 
@property (assign,nonatomic) double interval;                                //@synthesize interval=_interval - In the implementation block
-(void)switchLabel:(id)arg1 ;
-(void)setSecondaryText:(NSString *)arg1 ;
-(void)setPrimaryText:(NSString *)arg1 ;
-(NSString *)primaryText;
-(char)isAnimating;
-(void)setAnimating:(char)arg1 ;
-(void)setInterval:(double)arg1 ;
-(double)interval;
-(NSString *)secondaryText;
@end

