/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:35:21 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/ABE77428-6C25-43C9-8AD9-E0579EF1E1DA/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WhatsApp/WAContactInfoUnit.h>

@class NSString, NSManagedObjectID;

@interface WAContactInfoPhoneUnit : WAContactInfoUnit {

	NSString* _jid;
	NSManagedObjectID* _waStatusID;

}

@property (nonatomic,copy) NSString * jid;                                //@synthesize jid=_jid - In the implementation block
@property (nonatomic,retain) NSManagedObjectID * waStatusID;              //@synthesize waStatusID=_waStatusID - In the implementation block
+(id)contactInfoPhoneUnitForWAPhone:(id)arg1 ;
-(NSString *)jid;
-(void)setJid:(NSString *)arg1 ;
-(id)initWithWAPhone:(id)arg1 ;
-(NSManagedObjectID *)waStatusID;
-(id)waStatus;
-(void)setWaStatusID:(NSManagedObjectID *)arg1 ;
-(id)valueText;
-(id)initWithContactProperty:(id)arg1 ;
@end

