/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:35:24 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/ABE77428-6C25-43C9-8AD9-E0579EF1E1DA/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSManagedObjectContext, NSArray;

@interface WADatabaseResultsFetcher : NSObject {

	NSManagedObjectContext* _sourceManagedObjectContext;
	NSManagedObjectContext* _destinationManagedObjectContext;
	NSArray* _objectIDs;
	NSArray* _relationshipKeyPathsForPrefetching;

}

@property (nonatomic,retain) NSManagedObjectContext * sourceManagedObjectContext;                   //@synthesize sourceManagedObjectContext=_sourceManagedObjectContext - In the implementation block
@property (nonatomic,retain) NSManagedObjectContext * destinationManagedObjectContext;              //@synthesize destinationManagedObjectContext=_destinationManagedObjectContext - In the implementation block
@property (nonatomic,retain) NSArray * objectIDs;                                                   //@synthesize objectIDs=_objectIDs - In the implementation block
@property (nonatomic,retain) NSArray * relationshipKeyPathsForPrefetching;                          //@synthesize relationshipKeyPathsForPrefetching=_relationshipKeyPathsForPrefetching - In the implementation block
@property (nonatomic,readonly) unsigned objectCount; 
+(id)nullFetcher;
-(void)setSourceManagedObjectContext:(NSManagedObjectContext *)arg1 ;
-(void)setDestinationManagedObjectContext:(NSManagedObjectContext *)arg1 ;
-(void)setObjectIDs:(NSArray *)arg1 ;
-(NSManagedObjectContext *)destinationManagedObjectContext;
-(unsigned)objectCount;
-(NSManagedObjectContext *)sourceManagedObjectContext;
-(NSArray *)relationshipKeyPathsForPrefetching;
-(id)fetchResults;
-(void)setRelationshipKeyPathsForPrefetching:(NSArray *)arg1 ;
-(NSArray *)objectIDs;
@end

