/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:35:16 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/ABE77428-6C25-43C9-8AD9-E0579EF1E1DA/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WhatsApp/WAFieldStatsEvent.h>

@interface WAFieldStatsEventLogin : WAFieldStatsEvent {

	double _login_result;
	double _retry_count;
	double _login_t;

}

@property (assign,nonatomic) double login_result;              //@synthesize login_result=_login_result - In the implementation block
@property (assign,nonatomic) double retry_count;               //@synthesize retry_count=_retry_count - In the implementation block
@property (assign,nonatomic) double login_t;                   //@synthesize login_t=_login_t - In the implementation block
-(void)setRetry_count:(double)arg1 ;
-(double)retry_count;
-(double)login_result;
-(void)setLogin_result:(double)arg1 ;
-(double)login_t;
-(void)setLogin_t:(double)arg1 ;
-(id)init;
-(void)submit;
@end

