/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:35:14 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/ABE77428-6C25-43C9-8AD9-E0579EF1E1DA/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSMutableArray, NSMutableDictionary, NSObject;

@interface WAGimmickProvider : NSObject {

	NSMutableArray* _orderedGimmickData;
	NSMutableDictionary* _shortcutMap;
	NSMutableDictionary* _assetIDToShortcutMap;
	NSMutableDictionary* _remoteURLMap;
	NSObject*<OS_dispatch_queue> _queue;

}
+(id)sharedProvider;
-(id)externalIDForShortcut:(id)arg1 ;
-(id)shortcutForAssetID:(id)arg1 ;
-(void)enumerateFeaturedGimmicksWithBlock:(/*^block*/id)arg1 ;
-(void)addShortcuts;
-(id)remoteContentURLForAssetID:(id)arg1 format:(id)arg2 ;
-(id)init;
@end

