/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:35:13 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/ABE77428-6C25-43C9-8AD9-E0579EF1E1DA/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WhatsApp/WATableViewController.h>
#import <UIKit/UINavigationControllerDelegate.h>
#import <WhatsApp/WAMediaPickerDataSource.h>
#import <WhatsApp/WAWallpaperPreviewControllerDelegate.h>

@class WAMediaPickerLibraryController, NSString;

@interface WallpaperSourceViewController : WATableViewController <UINavigationControllerDelegate, WAMediaPickerDataSource, WAWallpaperPreviewControllerDelegate> {

	int _solidColorsRowIndex;
	char _photoLibraryAvailable;
	WAMediaPickerLibraryController* _libraryController;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)controller;
-(void)wa_fontSizeDidChange;
-(id)libraryController;
-(char)canSelectMediaPickerAsset:(id)arg1 ;
-(id)selectedAssetIdentifiers;
-(char)canAddMoreMediaPickerAssets;
-(void)toggleSelectionOfMediaPickerAsset:(id)arg1 ;
-(void)showMaximumSelectionCountExceededError;
-(void)wallpaperPreviewController:(id)arg1 didSelectLibraryImageAtIndex:(unsigned)arg2 ;
-(void)wallpaperPreviewController:(id)arg1 didSelectSolidColorAtIndex:(unsigned)arg2 ;
-(void)wallpaperPreviewController:(id)arg1 didSelectCustomImage:(id)arg2 ;
-(void)wallpaperPreviewControllerDidCancel:(id)arg1 ;
-(id)init;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(char)allowsMultipleSelection;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(char)arg1 ;
-(void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(char)arg3 ;
-(void)clearSelection;
@end

