/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:35:24 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/ABE77428-6C25-43C9-8AD9-E0579EF1E1DA/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSNumber, NSString, NSDate;

@interface WAStatsRecord : NSManagedObject

@property (nonatomic,retain) NSNumber * audioCount; 
@property (nonatomic,retain) NSNumber * audioSize; 
@property (nonatomic,retain) NSString * chatName; 
@property (nonatomic,retain) NSNumber * contactCount; 
@property (nonatomic,retain) NSNumber * documentCount; 
@property (nonatomic,retain) NSNumber * documentSize; 
@property (nonatomic,retain) NSNumber * imageCount; 
@property (nonatomic,retain) NSNumber * imageSize; 
@property (nonatomic,retain) NSNumber * isRecurring; 
@property (nonatomic,retain) NSString * jid; 
@property (nonatomic,retain) NSNumber * locationCount; 
@property (nonatomic,retain) NSDate * messageDate; 
@property (nonatomic,retain) NSDate * recordDate; 
@property (nonatomic,retain) NSString * recurringID; 
@property (nonatomic,retain) NSNumber * textCount; 
@property (nonatomic,retain) NSNumber * totalCount; 
@property (nonatomic,retain) NSNumber * totalSize; 
@property (nonatomic,retain) NSNumber * videoCount; 
@property (nonatomic,retain) NSNumber * videoSize; 
@end

