/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:45 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/ASControlNode.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol ASTextNodeDelegate;
@class NSArray, NSAttributedString, NSString, ASHighlightOverlayLayer, ASTextNodeRenderer, ASTextNodeShadower, UILongPressGestureRecognizer, UIColor;

@interface ASTextNode : ASControlNode <UIGestureRecognizerDelegate> {

	CGSize _shadowOffset;
	CGColorRef _shadowColor;
	float _shadowOpacity;
	float _shadowRadius;
	NSArray* _exclusionPaths;
	NSAttributedString* _composedTruncationString;
	NSString* _highlightedLinkAttributeName;
	id _highlightedLinkAttributeValue;
	NSRange _highlightRange;
	ASHighlightOverlayLayer* _activeHighlightLayer;
	Mutex _rendererLock;
	CGSize _constrainedSize;
	ASTextNodeRenderer* _renderer;
	ASTextNodeShadower* _shadower;
	UILongPressGestureRecognizer* _longPressGestureRecognizer;
	char _longPressCancelsTouches;
	char _passthroughNonlinkTouches;
	NSAttributedString* _attributedString;
	NSAttributedString* _truncationAttributedString;
	NSAttributedString* _additionalTruncationMessage;
	int _truncationMode;
	unsigned _maximumLineCount;
	UIColor* _placeholderColor;
	NSArray* _linkAttributeNames;
	unsigned _highlightStyle;
	id<ASTextNodeDelegate> _delegate;
	float _minimumLongPressDuration;
	UIEdgeInsets _placeholderInsets;

}

@property (nonatomic,copy) NSAttributedString * attributedString;                         //@synthesize attributedString=_attributedString - In the implementation block
@property (nonatomic,copy) NSAttributedString * truncationAttributedString;               //@synthesize truncationAttributedString=_truncationAttributedString - In the implementation block
@property (nonatomic,copy) NSAttributedString * additionalTruncationMessage;              //@synthesize additionalTruncationMessage=_additionalTruncationMessage - In the implementation block
@property (assign,nonatomic) int truncationMode;                                          //@synthesize truncationMode=_truncationMode - In the implementation block
@property (getter=isTruncated,nonatomic,readonly) char truncated; 
@property (assign,nonatomic) unsigned maximumLineCount;                                   //@synthesize maximumLineCount=_maximumLineCount - In the implementation block
@property (nonatomic,readonly) unsigned lineCount; 
@property (nonatomic,retain) NSArray * exclusionPaths; 
@property (nonatomic,retain) UIColor * placeholderColor;                                  //@synthesize placeholderColor=_placeholderColor - In the implementation block
@property (assign,nonatomic) UIEdgeInsets placeholderInsets;                              //@synthesize placeholderInsets=_placeholderInsets - In the implementation block
@property (nonatomic,readonly) UIEdgeInsets shadowPadding; 
@property (nonatomic,copy) NSArray * linkAttributeNames;                                  //@synthesize linkAttributeNames=_linkAttributeNames - In the implementation block
@property (assign,nonatomic) unsigned highlightStyle;                                     //@synthesize highlightStyle=_highlightStyle - In the implementation block
@property (assign,nonatomic) NSRange highlightRange; 
@property (assign,nonatomic,__weak) id<ASTextNodeDelegate> delegate;                      //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) char longPressCancelsTouches;                                //@synthesize longPressCancelsTouches=_longPressCancelsTouches - In the implementation block
@property (assign,nonatomic) float minimumLongPressDuration;                              //@synthesize minimumLongPressDuration=_minimumLongPressDuration - In the implementation block
@property (assign,nonatomic) char passthroughNonlinkTouches;                              //@synthesize passthroughNonlinkTouches=_passthroughNonlinkTouches - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)drawRect:(CGRect)arg1 withParameters:(id)arg2 isCancelled:(/*^block*/id)arg3 isRasterizing:(char)arg4 ;
+(CGRect)_adjustRendererRect:(CGRect)arg1 forShadowPadding:(UIEdgeInsets)arg2 inBounds:(CGRect)arg3 ;
+(float)_highlightOpacityForStyle:(unsigned)arg1 ;
+(CGColorRef)_highlightColorForStyle:(unsigned)arg1 ;
-(void)setTruncationAttributedString:(NSAttributedString *)arg1 ;
-(id)initWithViewBlock:(/*^block*/id)arg1 ;
-(id)initWithLayerBlock:(/*^block*/id)arg1 ;
-(CGSize)calculateSizeThatFits:(CGSize)arg1 ;
-(NSRange)highlightRange;
-(void)displayDidFinish;
-(unsigned)highlightStyle;
-(id)drawParametersForAsyncLayer:(id)arg1 ;
-(void)clearContents;
-(CGRect)frameForTextRange:(NSRange)arg1 ;
-(id)_shadower;
-(void)setLinkAttributeNames:(NSArray *)arg1 ;
-(void)_invalidateRenderer;
-(char)longPressCancelsTouches;
-(id)_linkAttributeValueAtPoint:(CGPoint)arg1 attributeName:(out id*)arg2 range:(out NSRange*)arg3 inAdditionalTruncationMessage:(out char*)arg4 ;
-(char)_pendingTruncationTap;
-(char)_pendingLinkTap;
-(void)setHighlightRange:(NSRange)arg1 animated:(char)arg2 ;
-(void)_setHighlightRange:(NSRange)arg1 forAttributeName:(id)arg2 value:(id)arg3 animated:(char)arg4 ;
-(id)_rectsForTextRange:(NSRange)arg1 measureOption:(unsigned)arg2 ;
-(CGRect)trailingRect;
-(UIEdgeInsets)placeholderInsets;
-(NSRange)_additionalTruncationMessageRangeWithVisibleRange:(NSRange)arg1 ;
-(void)_clearHighlightIfNecessary;
-(void)_invalidateShadower;
-(void)_invalidateTruncationString;
-(id)_composedTruncationString;
-(id)_prepareTruncationStringForDrawing:(id)arg1 ;
-(id)linkAttributeValueAtPoint:(CGPoint)arg1 attributeName:(out id*)arg2 range:(out NSRange*)arg3 ;
-(void)setHighlightRange:(NSRange)arg1 ;
-(id)rectsForTextRange:(NSRange)arg1 ;
-(id)highlightRectsForTextRange:(NSRange)arg1 ;
-(void)setAdditionalTruncationMessage:(NSAttributedString *)arg1 ;
-(void)setMaximumLineCount:(unsigned)arg1 ;
-(NSAttributedString *)truncationAttributedString;
-(NSAttributedString *)additionalTruncationMessage;
-(unsigned)maximumLineCount;
-(void)setPlaceholderInsets:(UIEdgeInsets)arg1 ;
-(NSArray *)linkAttributeNames;
-(void)setHighlightStyle:(unsigned)arg1 ;
-(void)setLongPressCancelsTouches:(char)arg1 ;
-(char)passthroughNonlinkTouches;
-(void)setPassthroughNonlinkTouches:(char)arg1 ;
-(unsigned)lineCount;
-(void)_handleLongPress:(id)arg1 ;
-(id)_renderer;
-(UIColor *)placeholderColor;
-(void)setPlaceholderColor:(UIColor *)arg1 ;
-(float)shadowOpacity;
-(void)didLoad;
-(void)setDelegate:(id<ASTextNodeDelegate>)arg1 ;
-(void)dealloc;
-(char)pointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
-(id)init;
-(void)setFrame:(CGRect)arg1 ;
-(void)setBounds:(CGRect)arg1 ;
-(NSString *)description;
-(id<ASTextNodeDelegate>)delegate;
-(char)gestureRecognizerShouldBegin:(id)arg1 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)setShadowColor:(CGColorRef)arg1 ;
-(void)setShadowOffset:(CGSize)arg1 ;
-(CGSize)shadowOffset;
-(CGColorRef)shadowColor;
-(void)setAttributedString:(NSAttributedString *)arg1 ;
-(NSAttributedString *)attributedString;
-(float)shadowRadius;
-(UIEdgeInsets)shadowPadding;
-(void)setShadowOpacity:(float)arg1 ;
-(void)setShadowRadius:(float)arg1 ;
-(id)placeholderImage;
-(NSArray *)exclusionPaths;
-(void)setExclusionPaths:(NSArray *)arg1 ;
-(float)minimumLongPressDuration;
-(void)setMinimumLongPressDuration:(float)arg1 ;
-(int)truncationMode;
-(void)setTruncationMode:(int)arg1 ;
-(char)isTruncated;
@end

