/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:23:02 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSSet, NSIndexSet, NSDictionary;

@interface CKTransactionalComponentDataSourceAppliedChanges : NSObject {

	NSSet* _updatedIndexPaths;
	NSSet* _removedIndexPaths;
	NSIndexSet* _removedSections;
	NSDictionary* _movedIndexPaths;
	NSIndexSet* _insertedSections;
	NSSet* _insertedIndexPaths;
	NSDictionary* _userInfo;

}

@property (nonatomic,copy,readonly) NSSet * updatedIndexPaths;                   //@synthesize updatedIndexPaths=_updatedIndexPaths - In the implementation block
@property (nonatomic,copy,readonly) NSSet * removedIndexPaths;                   //@synthesize removedIndexPaths=_removedIndexPaths - In the implementation block
@property (nonatomic,copy,readonly) NSIndexSet * removedSections;                //@synthesize removedSections=_removedSections - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * movedIndexPaths;              //@synthesize movedIndexPaths=_movedIndexPaths - In the implementation block
@property (nonatomic,copy,readonly) NSIndexSet * insertedSections;               //@synthesize insertedSections=_insertedSections - In the implementation block
@property (nonatomic,copy,readonly) NSSet * insertedIndexPaths;                  //@synthesize insertedIndexPaths=_insertedIndexPaths - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * userInfo;                     //@synthesize userInfo=_userInfo - In the implementation block
-(NSSet *)removedIndexPaths;
-(NSIndexSet *)removedSections;
-(NSSet *)updatedIndexPaths;
-(NSDictionary *)movedIndexPaths;
-(id)initWithUpdatedIndexPaths:(id)arg1 removedIndexPaths:(id)arg2 removedSections:(id)arg3 movedIndexPaths:(id)arg4 insertedSections:(id)arg5 insertedIndexPaths:(id)arg6 userInfo:(id)arg7 ;
-(NSIndexSet *)insertedSections;
-(NSSet *)insertedIndexPaths;
-(id)init;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(NSDictionary *)userInfo;
@end

