/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:51 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBGraphQLInput.h>

@class NSString, FBApplistCreateInputDataPrivacy, NSArray;

@interface FBApplistCreateInputData : FBGraphQLInput {

	NSString* _clientMutationId;
	NSString* _actorId;
	FBApplistCreateInputDataPrivacy* _privacy;
	NSString* _role;
	NSArray* _apps;
	NSString* _name;

}

@property (nonatomic,copy) NSString * clientMutationId;                            //@synthesize clientMutationId=_clientMutationId - In the implementation block
@property (nonatomic,copy) NSString * actorId;                                     //@synthesize actorId=_actorId - In the implementation block
@property (nonatomic,copy) FBApplistCreateInputDataPrivacy * privacy;              //@synthesize privacy=_privacy - In the implementation block
@property (nonatomic,copy) NSString * role;                                        //@synthesize role=_role - In the implementation block
@property (nonatomic,copy) NSArray * apps;                                         //@synthesize apps=_apps - In the implementation block
@property (nonatomic,copy) NSString * name;                                        //@synthesize name=_name - In the implementation block
-(void)setActorId:(NSString *)arg1 ;
-(FBApplistCreateInputDataPrivacy *)privacy;
-(void)setPrivacy:(FBApplistCreateInputDataPrivacy *)arg1 ;
-(void)setClientMutationId:(NSString *)arg1 ;
-(NSString *)actorId;
-(NSString *)clientMutationId;
-(const FBGraphQLInputField*)fieldsMetadataWithOutLength:(out int*)arg1 ;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(void)setApps:(NSArray *)arg1 ;
-(NSArray *)apps;
-(void)setRole:(NSString *)arg1 ;
-(NSString *)role;
@end

