/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:54 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBAccessToken, NSString, NSArray;

@interface FBAuthenticationHandlerResponse : NSObject {

	FBAccessToken* _accessToken;
	NSString* _loggedInUserFBID;
	NSString* _machineID;
	NSArray* _httpCookies;
	NSString* _actingFBID;
	FBAccessToken* _actingAccessToken;
	NSString* _identifier;

}

@property (nonatomic,retain) FBAccessToken * accessToken;                    //@synthesize accessToken=_accessToken - In the implementation block
@property (nonatomic,copy) NSString * loggedInUserFBID;                      //@synthesize loggedInUserFBID=_loggedInUserFBID - In the implementation block
@property (nonatomic,copy) NSString * machineID;                             //@synthesize machineID=_machineID - In the implementation block
@property (nonatomic,copy) NSArray * httpCookies;                            //@synthesize httpCookies=_httpCookies - In the implementation block
@property (nonatomic,copy) NSString * actingFBID;                            //@synthesize actingFBID=_actingFBID - In the implementation block
@property (nonatomic,retain) FBAccessToken * actingAccessToken;              //@synthesize actingAccessToken=_actingAccessToken - In the implementation block
@property (nonatomic,copy) NSString * identifier;                            //@synthesize identifier=_identifier - In the implementation block
+(id)authenticationHandlerForResponse:(id)arg1 error:(id*)arg2 ;
-(NSString *)loggedInUserFBID;
-(void)addRecursiveDescriptionToString:(id)arg1 indentLevel:(int)arg2 ;
-(NSString *)actingFBID;
-(FBAccessToken *)actingAccessToken;
-(NSArray *)httpCookies;
-(void)setLoggedInUserFBID:(NSString *)arg1 ;
-(void)setHttpCookies:(NSArray *)arg1 ;
-(void)setActingFBID:(NSString *)arg1 ;
-(void)setActingAccessToken:(FBAccessToken *)arg1 ;
-(id)description;
-(NSString *)identifier;
-(void)setIdentifier:(NSString *)arg1 ;
-(NSString *)machineID;
-(void)setMachineID:(NSString *)arg1 ;
-(FBAccessToken *)accessToken;
-(void)setAccessToken:(FBAccessToken *)arg1 ;
@end

