/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:46 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
@class AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, NSDate, UIImage, NSTimer, NSURL;

@interface FBBugReportVideoScreenRecorder : NSObject {

	AVAssetWriter* _writer;
	AVAssetWriterInput* _writerInput;
	AVAssetWriterInputPixelBufferAdaptor* _writerInputPixelBufferAdaptor;
	NSDate* _startTime;
	UIImage* _latestScreenshot;
	NSTimer* _timer;
	char _captureFrameInProgress;
	NSURL* _originalFilenameURL;
	NSURL* _tmpFilenameURL;
	CGSize _frameSize;

}
-(void)captureFrame:(id)arg1 ;
-(void)captureFrameInternal;
-(id)imageRotatedByDegrees:(id)arg1 radians:(float)arg2 ;
-(char)startRecording:(id)arg1 ;
-(void)stopRecording;
@end

