/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:07 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBCameraModifiedTouchTrackingButtonListener.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBCameraFlashModeToggleViewDelegate.h>

@protocol FBClock, FBCameraViewDelegate;
@class UIView, UIButton, FBCameraTransitioningView, FBCameraModifiedTouchTrackingButton, FBCameraProgressView, FBCameraLivePreviewView, NSString, NSTimer, NSDate, UITapGestureRecognizer, FBCameraFocusIndicator, FBCameraFlashModeToggleView, CALayer, UIImage;

@interface FBCameraView : UIView <UIGestureRecognizerDelegate, FBCameraModifiedTouchTrackingButtonListener, FBCameraFlashModeToggleViewDelegate> {

	UIView* _flashView;
	UIButton* _switchCameraButton;
	UIButton* _expandButton;
	UIButton* _collapseButton;
	UIButton* _closeButton;
	FBCameraTransitioningView* _fullscreenButton;
	char _enableVideo;
	char _isLongPressEnabled;
	FBCameraModifiedTouchTrackingButton* _captureButton;
	FBCameraProgressView* _progressView;
	FBCameraLivePreviewView* _cameraLivePreviewView;
	UIView* _cameraPreviewView;
	NSString* _videoHelpString;
	NSString* _swipeUpString;
	NSString* _releaseString;
	char _cameraPreviewViewIsUp;
	NSTimer* _videoTimer;
	id<FBClock> _clock;
	NSDate* _recordingStartTime;
	char _skipMicrophonePermissionsWarning;
	UITapGestureRecognizer* _tapGesture;
	FBCameraFocusIndicator* _focusIndicator;
	FBCameraFlashModeToggleView* _flashModeToggleView;
	unsigned _fullscreenMode;
	unsigned _closeButtonType;
	char _isPortrait;
	char _enableCapture;
	char _showCaptureInstructions;
	char _usesFullscreenLayout;
	int _captureDevicePosition;
	id<FBCameraViewDelegate> _delegate;
	unsigned _state;
	unsigned _viewMode;
	float _fullscreenTransitionProgress;
	double _maxVideoLength;

}

@property (nonatomic,readonly) double maxVideoLength;                               //@synthesize maxVideoLength=_maxVideoLength - In the implementation block
@property (assign,nonatomic,__weak) CALayer * livePreviewLayer; 
@property (assign,nonatomic) int captureDevicePosition;                             //@synthesize captureDevicePosition=_captureDevicePosition - In the implementation block
@property (assign,nonatomic,__weak) id<FBCameraViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) char enableCapture;                                    //@synthesize enableCapture=_enableCapture - In the implementation block
@property (nonatomic,readonly) unsigned state;                                      //@synthesize state=_state - In the implementation block
@property (assign,nonatomic) unsigned viewMode;                                     //@synthesize viewMode=_viewMode - In the implementation block
@property (assign,nonatomic) char showCaptureInstructions;                          //@synthesize showCaptureInstructions=_showCaptureInstructions - In the implementation block
@property (nonatomic,retain) UIImage * freezeImage; 
@property (assign,nonatomic) char usesFullscreenLayout;                             //@synthesize usesFullscreenLayout=_usesFullscreenLayout - In the implementation block
@property (assign,nonatomic) float fullscreenTransitionProgress;                    //@synthesize fullscreenTransitionProgress=_fullscreenTransitionProgress - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_didTap:(id)arg1 ;
-(void)setPreviewLayerRotationAngle:(float)arg1 ;
-(void)_initializeFocusIndicatorIfNeeded;
-(void)setInterfaceRotationAngle:(float)arg1 ;
-(void)setCloseButtonToHidden:(char)arg1 ;
-(void)setRecording;
-(void)setLivePreviewLayer:(CALayer *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 configuration:(id)arg2 filterOverlayView:(id)arg3 clock:(id)arg4 cameraButton:(id)arg5 flashModeToggleView:(id)arg6 ;
-(void)setEnableCapture:(char)arg1 ;
-(void)setUsesFullscreenLayout:(char)arg1 ;
-(void)setFullscreenTransitionProgress:(float)arg1 ;
-(void)setSwitchCameraButtonToHidden:(char)arg1 ;
-(float)fullscreenTransitionProgress;
-(void)setAllowTapToEnhance:(char)arg1 ;
-(void)setFlashModeToggleEnabled:(char)arg1 ;
-(void)setShowCaptureInstructions:(char)arg1 ;
-(void)setFreezeImage:(id)arg1 rotationAngle:(float)arg2 ;
-(char)usesFullscreenLayout;
-(void)startRespondToLongPress;
-(void)setFlashModeToggleHidden:(char)arg1 ;
-(void)setFreezeImage:(UIImage *)arg1 ;
-(CALayer *)livePreviewLayer;
-(UIImage *)freezeImage;
-(double)maxVideoLength;
-(void)_switchPressed:(id)arg1 ;
-(void)_fullscreenPressed:(id)arg1 ;
-(void)_closePressed:(id)arg1 ;
-(void)_updateCamerPreviewForCaptureInstructionsStringIfAllowed;
-(void)_capturePressBegan:(id)arg1 ;
-(void)_capturePressCanceled:(id)arg1 ;
-(void)_startVideoRecording;
-(void)_showMicrophoneAlert;
-(void)_cancelVideoRecording;
-(char)_isLongPressVideoCaptureEnabled;
-(void)_updateCameraPreviewForSwipeUpString;
-(void)_updateCameraPreviewForReleaseString;
-(void)_finishVideoRecording;
-(void)_updateRecordTime;
-(double)_timeElapsedSinceRecord;
-(double)_recordDuration;
-(void)_animateDown;
-(void)_updateViewsForFullscreen:(char)arg1 ;
-(void)_setUpProgressViewForFullscreen:(char)arg1 ;
-(void)didDragEnter;
-(void)didDragExit;
-(void)didTouchUpInside;
-(void)didTouchUpOutside;
-(void)cameraFlashModeToggleView:(id)arg1 didUpdateFlashMode:(int)arg2 ;
-(void)stopRespondToLongPress;
-(char)enableCapture;
-(char)showCaptureInstructions;
-(void)_updateCameraChooserAccessibilityLabel;
-(void)_isPortraitWithAngle:(float)arg1 ;
-(void)setCaptureDevicePosition:(int)arg1 ;
-(void)setControlsToHidden:(char)arg1 ;
-(void)setButtonsEnabled:(char)arg1 ;
-(int)captureDevicePosition;
-(void)setDelegate:(id<FBCameraViewDelegate>)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(id<FBCameraViewDelegate>)delegate;
-(unsigned)state;
-(unsigned)viewMode;
-(void)flash;
-(void)setPreviewView:(id)arg1 ;
-(void)resetState;
-(void)setViewMode:(unsigned)arg1 ;
@end

