/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:18 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBCameraCaptureButtonAppearanceProvider.h>

@class NSString;

@interface FBCameraDefaultCaptureButtonAppearanceProvider : NSObject <FBCameraCaptureButtonAppearanceProvider>

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)captureButtonBorderColorForState:(unsigned)arg1 ;
-(float)captureButtonBorderOuterRadiusForState:(unsigned)arg1 ;
-(float)captureButtonBorderInnerRadiusForState:(unsigned)arg1 ;
-(id)captureButtonInnerCircleColorForState:(unsigned)arg1 ;
-(float)captureButtonInnerCircleRadiusForState:(unsigned)arg1 ;
-(unsigned)captureButtonInnerShapeForState:(unsigned)arg1 ;
-(id)captureButtonOuterCircleColorForState:(unsigned)arg1 ;
-(float)captureButtonOuterCircleRadiusForState:(unsigned)arg1 ;
-(id)dialColorForState:(unsigned)arg1 ;
-(CGSize)dialSizeForState:(unsigned)arg1 ;
-(unsigned)viewFinderShapeForState:(unsigned)arg1 ;
-(double)captureButtonAnimationDuration;
@end

