/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:05 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSCoding.h>

@class FBTypedNSArrayOfFBComposerPerson, NSArray;

@interface FBComposerTaggedUsersBundle : FBValueObject <NSCopying, NSCoding> {

	char _hasTaggedUsers;
	FBTypedNSArrayOfFBComposerPerson* _taggedUsersFromWithWho;
	FBTypedNSArrayOfFBComposerPerson* _taggedUsersFromWithWhoAndPhotos;
	FBTypedNSArrayOfFBComposerPerson* _taggedAndMentionedUsers;
	FBTypedNSArrayOfFBComposerPerson* _taggedUsersFromPhotos;
	FBTypedNSArrayOfFBComposerPerson* _taggedUsersWithoutAuthor;
	NSArray* _autoTaggedUsersFromPhotos;

}

@property (nonatomic,readonly) char hasTaggedUsers;                                                                  //@synthesize hasTaggedUsers=_hasTaggedUsers - In the implementation block
@property (nonatomic,copy,readonly) FBTypedNSArrayOfFBComposerPerson * taggedUsersFromWithWho;                       //@synthesize taggedUsersFromWithWho=_taggedUsersFromWithWho - In the implementation block
@property (nonatomic,copy,readonly) FBTypedNSArrayOfFBComposerPerson * taggedUsersFromWithWhoAndPhotos;              //@synthesize taggedUsersFromWithWhoAndPhotos=_taggedUsersFromWithWhoAndPhotos - In the implementation block
@property (nonatomic,copy,readonly) FBTypedNSArrayOfFBComposerPerson * taggedAndMentionedUsers;                      //@synthesize taggedAndMentionedUsers=_taggedAndMentionedUsers - In the implementation block
@property (nonatomic,copy,readonly) FBTypedNSArrayOfFBComposerPerson * taggedUsersFromPhotos;                        //@synthesize taggedUsersFromPhotos=_taggedUsersFromPhotos - In the implementation block
@property (nonatomic,copy,readonly) FBTypedNSArrayOfFBComposerPerson * taggedUsersWithoutAuthor;                     //@synthesize taggedUsersWithoutAuthor=_taggedUsersWithoutAuthor - In the implementation block
@property (nonatomic,copy,readonly) NSArray * autoTaggedUsersFromPhotos;                                             //@synthesize autoTaggedUsersFromPhotos=_autoTaggedUsersFromPhotos - In the implementation block
-(id)initWithHasTaggedUsers:(char)arg1 taggedUsersFromWithWho:(id)arg2 taggedUsersFromWithWhoAndPhotos:(id)arg3 taggedAndMentionedUsers:(id)arg4 taggedUsersFromPhotos:(id)arg5 taggedUsersWithoutAuthor:(id)arg6 autoTaggedUsersFromPhotos:(id)arg7 ;
-(char)hasTaggedUsers;
-(FBTypedNSArrayOfFBComposerPerson *)taggedUsersFromWithWho;
-(FBTypedNSArrayOfFBComposerPerson *)taggedUsersFromWithWhoAndPhotos;
-(FBTypedNSArrayOfFBComposerPerson *)taggedAndMentionedUsers;
-(FBTypedNSArrayOfFBComposerPerson *)taggedUsersFromPhotos;
-(FBTypedNSArrayOfFBComposerPerson *)taggedUsersWithoutAuthor;
-(NSArray *)autoTaggedUsersFromPhotos;
@end

