/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:51 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBGraphQLInput.h>

@class NSString, FBCommerceProductItemUpdateInputDataProductItemPrice, NSNumber, NSArray;

@interface FBCommerceProductItemUpdateInputData : FBGraphQLInput {

	NSString* _clientMutationId;
	NSString* _actorId;
	NSString* _graphQLID;
	NSString* _name;
	NSString* _descriptionText;
	FBCommerceProductItemUpdateInputDataProductItemPrice* _productItemPrice;
	NSNumber* _price;
	NSArray* _imageIds;
	NSString* _groupId;
	NSString* _commerceFeaturedItem;
	NSNumber* _inventory;

}

@property (nonatomic,copy) NSString * clientMutationId;                                                          //@synthesize clientMutationId=_clientMutationId - In the implementation block
@property (nonatomic,copy) NSString * actorId;                                                                   //@synthesize actorId=_actorId - In the implementation block
@property (nonatomic,copy) NSString * graphQLID;                                                                 //@synthesize graphQLID=_graphQLID - In the implementation block
@property (nonatomic,copy) NSString * name;                                                                      //@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString * descriptionText;                                                           //@synthesize descriptionText=_descriptionText - In the implementation block
@property (nonatomic,copy) FBCommerceProductItemUpdateInputDataProductItemPrice * productItemPrice;              //@synthesize productItemPrice=_productItemPrice - In the implementation block
@property (nonatomic,copy) NSNumber * price;                                                                     //@synthesize price=_price - In the implementation block
@property (nonatomic,copy) NSArray * imageIds;                                                                   //@synthesize imageIds=_imageIds - In the implementation block
@property (nonatomic,copy) NSString * groupId;                                                                   //@synthesize groupId=_groupId - In the implementation block
@property (nonatomic,copy) NSString * commerceFeaturedItem;                                                      //@synthesize commerceFeaturedItem=_commerceFeaturedItem - In the implementation block
@property (nonatomic,copy) NSNumber * inventory;                                                                 //@synthesize inventory=_inventory - In the implementation block
-(void)setActorId:(NSString *)arg1 ;
-(NSString *)graphQLID;
-(void)setGraphQLID:(NSString *)arg1 ;
-(FBCommerceProductItemUpdateInputDataProductItemPrice *)productItemPrice;
-(void)setClientMutationId:(NSString *)arg1 ;
-(NSString *)actorId;
-(NSString *)clientMutationId;
-(const FBGraphQLInputField*)fieldsMetadataWithOutLength:(out int*)arg1 ;
-(void)setProductItemPrice:(FBCommerceProductItemUpdateInputDataProductItemPrice *)arg1 ;
-(NSArray *)imageIds;
-(void)setImageIds:(NSArray *)arg1 ;
-(NSString *)commerceFeaturedItem;
-(void)setCommerceFeaturedItem:(NSString *)arg1 ;
-(NSNumber *)inventory;
-(void)setInventory:(NSNumber *)arg1 ;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(void)setDescriptionText:(NSString *)arg1 ;
-(NSString *)descriptionText;
-(void)setGroupId:(NSString *)arg1 ;
-(NSString *)groupId;
-(NSNumber *)price;
-(void)setPrice:(NSNumber *)arg1 ;
@end

