/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:19 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBCollectionViewUpdateListener.h>

@protocol FBCollectionViewUpdateTrackingIndexPathProvider;
@class NSIndexPath, FBCollectionViewUpdateIndexPathListenerAnnouncer, NSString;

@interface FBCollectionViewUpdateIndexPathTracker : NSObject <FBCollectionViewUpdateListener> {

	NSIndexPath* _referenceIndexPath;
	int _newSection;
	int _newItem;
	char _validChange;
	char _restoreOnSingleUpdate;
	FBCollectionViewUpdateIndexPathListenerAnnouncer* _listenerAnnouncer;
	id<FBCollectionViewUpdateTrackingIndexPathProvider> _trackingIndexPathProvider;

}

@property (nonatomic,readonly) FBCollectionViewUpdateIndexPathListenerAnnouncer * listenerAnnouncer;                            //@synthesize listenerAnnouncer=_listenerAnnouncer - In the implementation block
@property (assign,nonatomic,__weak) id<FBCollectionViewUpdateTrackingIndexPathProvider> trackingIndexPathProvider;              //@synthesize trackingIndexPathProvider=_trackingIndexPathProvider - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)_indexPathToTrackForCollectionView:(id)arg1 ;
-(void)saveStateBeforeUpdateForCollectionView:(id)arg1 ;
-(void)announceMovementAfterUpdateForCollectionView:(id)arg1 ;
-(void)resetStateAfterUpdateForCollectionView:(id)arg1 ;
-(FBCollectionViewUpdateIndexPathListenerAnnouncer *)listenerAnnouncer;
-(id<FBCollectionViewUpdateTrackingIndexPathProvider>)trackingIndexPathProvider;
-(void)setTrackingIndexPathProvider:(id<FBCollectionViewUpdateTrackingIndexPathProvider>)arg1 ;
-(void)collectionViewWillBeginSingleUpdate:(id)arg1 ;
-(void)collectionViewWillEndSingleUpdate:(id)arg1 ;
-(void)collectionViewDidEndSingleUpdate:(id)arg1 ;
-(void)collectionView:(id)arg1 willInsertItemsAtIndexPaths:(id)arg2 ;
-(void)collectionView:(id)arg1 willDeleteItemsAtIndexPaths:(id)arg2 ;
-(void)collectionView:(id)arg1 willReloadItemsAtIndexPaths:(id)arg2 ;
-(void)collectionViewWillBeginUpdates:(id)arg1 ;
-(void)collectionViewWillEndUpdates:(id)arg1 ;
-(void)collectionViewDidEndUpdates:(id)arg1 ;
-(id)initWithSession:(id)arg1 ;
@end

