/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:23:01 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/CKTransactionalSuspensionControllerOutputHandler.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/CKComponentSuspendable.h>

@protocol FBComponentTransactionalDataSourceOutputHandlerDelegate;
@class CKTransactionalSuspensionController, CKTransactionalComponentDataSourceState, NSString;

@interface FBComponentTransactionalDataSourceOutputHandler : NSObject <CKTransactionalSuspensionControllerOutputHandler, CKComponentSuspendable> {

	unsigned _numberOfEnqueuedOperations;
	CKTransactionalSuspensionController* _suspensionController;
	unsigned _suspensionState;
	char _isAppendingChanges;
	id<FBComponentTransactionalDataSourceOutputHandlerDelegate> _delegate;
	CKTransactionalComponentDataSourceState* _dataSourceState;

}

@property (assign,nonatomic,__weak) id<FBComponentTransactionalDataSourceOutputHandlerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) char isComputingChanges; 
@property (nonatomic,retain) CKTransactionalComponentDataSourceState * dataSourceState;                                //@synthesize dataSourceState=_dataSourceState - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) unsigned state; 
@property (nonatomic,readonly) char hasPendingChanges; 
-(char)isComputingChanges;
-(CKTransactionalComponentDataSourceState *)dataSourceState;
-(void)setDataSourceState:(CKTransactionalComponentDataSourceState *)arg1 ;
-(void)resetSuspensionState;
-(void)enqueueOperation;
-(void)suspensionController:(id)arg1 didProcessChanges:(id)arg2 previousState:(id)arg3 ;
-(char)hasPendingChanges;
-(void)setDelegate:(id<FBComponentTransactionalDataSourceOutputHandlerDelegate>)arg1 ;
-(id<FBComponentTransactionalDataSourceOutputHandlerDelegate>)delegate;
-(unsigned)state;
-(void)setState:(unsigned)arg1 ;
-(id)initWithDataSource:(id)arg1 ;
@end

