/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:56 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
@interface FBDiskSizeCalculator : NSObject {

	shared_ptr<facebook::mobile::xplat::compactdisk::DiskSizeCalculator>* _diskSizeCalculator;

}
+(id)sharedCalculator;
-(id)initWithDiskSizeCalculator:(const shared_ptr<facebook::mobile::xplat::compactdisk::DiskSizeCalculator>*)arg1 ;
-(long long)fetchDirectorySize:(id)arg1 ;
-(void)addDirectory:(id)arg1 ;
-(void)addDirectory:(id)arg1 interval:(double)arg2 ;
-(void)startDiskSizeCalculation;
-(void)startRandomDiskSizeCalculation;
-(void)setLogAnalytics;
@end

