/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:24 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBEntityCardLikersOfContentQuery : NSObject
+(id)graphQLQueryWithAfterCursor:(id)arg1 count:(id)arg2 coverHeight:(id)arg3 coverWidth:(id)arg4 inChannelsExperiment:(id)arg5 introcardBioPromptEnabled:(id)arg6 introcardFavphotosEnabled:(id)arg7 introcardFeaturedContainersEnabled:(id)arg8 introcardOtherAccountsEnabled:(id)arg9 introcardSuggestedPhotosEnabled:(id)arg10 mediaType:(id)arg11 numAboutItems:(id)arg12 profileIntroCardEnabled:(id)arg13 publicAboutEnabled:(id)arg14 referrerTargetId:(id)arg15 referrerType:(id)arg16 renderLocation:(id)arg17 scale:(id)arg18 targetId:(id)arg19 useCoverPreview:(id)arg20 videoThumbnailSize:(id)arg21 voiceoverEnabled:(id)arg22 ;
@end

