/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:45 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBValueObject.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBUIConfig.h>

@class UIFont, NSArray, UIImage, UIColor, FBImageDownloader, FBScenePath, NSString;

@interface FBFacepileViewConfig : FBValueObject <FBUIConfig> {

	char _scrollable;
	unsigned _maximumNumberOfItems;
	unsigned _maximumNumberOfRows;
	unsigned _overflowTotalNumberOfItems;
	UIFont* _overflowFont;
	/*^block*/id _overflowTitleLoader;
	/*^block*/id _overflowAccessibilityLabelLoader;
	NSArray* _items;
	unsigned _itemSize;
	unsigned _itemStyle;
	unsigned _alignment;
	UIImage* _itemDefaultImage;
	UIColor* _itemsBackgroundColor;
	float _horizontalItemSpacing;
	float _verticalItemSpacing;
	UIColor* _itemBorderLineColor;
	float _itemBorderLineWidth;
	UIColor* _backgroundColor;
	FBImageDownloader* _imageDownloader;
	FBScenePath* _scenePath;
	UIEdgeInsets _insets;

}

@property (nonatomic,readonly) unsigned maximumNumberOfItems;                         //@synthesize maximumNumberOfItems=_maximumNumberOfItems - In the implementation block
@property (nonatomic,readonly) unsigned maximumNumberOfRows;                          //@synthesize maximumNumberOfRows=_maximumNumberOfRows - In the implementation block
@property (nonatomic,readonly) unsigned overflowTotalNumberOfItems;                   //@synthesize overflowTotalNumberOfItems=_overflowTotalNumberOfItems - In the implementation block
@property (nonatomic,copy,readonly) UIFont * overflowFont;                            //@synthesize overflowFont=_overflowFont - In the implementation block
@property (nonatomic,copy,readonly) id overflowTitleLoader;                           //@synthesize overflowTitleLoader=_overflowTitleLoader - In the implementation block
@property (nonatomic,copy,readonly) id overflowAccessibilityLabelLoader;              //@synthesize overflowAccessibilityLabelLoader=_overflowAccessibilityLabelLoader - In the implementation block
@property (nonatomic,copy,readonly) NSArray * items;                                  //@synthesize items=_items - In the implementation block
@property (nonatomic,readonly) unsigned itemSize;                                     //@synthesize itemSize=_itemSize - In the implementation block
@property (nonatomic,readonly) unsigned itemStyle;                                    //@synthesize itemStyle=_itemStyle - In the implementation block
@property (nonatomic,readonly) unsigned alignment;                                    //@synthesize alignment=_alignment - In the implementation block
@property (nonatomic,copy,readonly) UIImage * itemDefaultImage;                       //@synthesize itemDefaultImage=_itemDefaultImage - In the implementation block
@property (nonatomic,copy,readonly) UIColor * itemsBackgroundColor;                   //@synthesize itemsBackgroundColor=_itemsBackgroundColor - In the implementation block
@property (nonatomic,readonly) float horizontalItemSpacing;                           //@synthesize horizontalItemSpacing=_horizontalItemSpacing - In the implementation block
@property (nonatomic,readonly) float verticalItemSpacing;                             //@synthesize verticalItemSpacing=_verticalItemSpacing - In the implementation block
@property (nonatomic,copy,readonly) UIColor * itemBorderLineColor;                    //@synthesize itemBorderLineColor=_itemBorderLineColor - In the implementation block
@property (nonatomic,readonly) float itemBorderLineWidth;                             //@synthesize itemBorderLineWidth=_itemBorderLineWidth - In the implementation block
@property (nonatomic,readonly) UIEdgeInsets insets;                                   //@synthesize insets=_insets - In the implementation block
@property (nonatomic,readonly) char scrollable;                                       //@synthesize scrollable=_scrollable - In the implementation block
@property (nonatomic,copy,readonly) UIColor * backgroundColor;                        //@synthesize backgroundColor=_backgroundColor - In the implementation block
@property (nonatomic,readonly) FBImageDownloader * imageDownloader;                   //@synthesize imageDownloader=_imageDownloader - In the implementation block
@property (nonatomic,readonly) FBScenePath * scenePath;                               //@synthesize scenePath=_scenePath - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)newWithMaximumNumberOfItems:(unsigned)arg1 maximumNumberOfRows:(unsigned)arg2 overflowTotalNumberOfItems:(unsigned)arg3 overflowFont:(id)arg4 overflowTitleLoader:(/*^block*/id)arg5 overflowAccessibilityLabelLoader:(/*^block*/id)arg6 items:(id)arg7 itemSize:(unsigned)arg8 itemStyle:(unsigned)arg9 alignment:(unsigned)arg10 itemDefaultImage:(id)arg11 itemsBackgroundColor:(id)arg12 horizontalItemSpacing:(float)arg13 verticalItemSpacing:(float)arg14 itemBorderLineColor:(id)arg15 itemBorderLineWidth:(float)arg16 insets:(UIEdgeInsets)arg17 scrollable:(char)arg18 backgroundColor:(id)arg19 imageDownloader:(id)arg20 scenePath:(id)arg21 ;
+(Class)viewClass;
-(FBImageDownloader *)imageDownloader;
-(unsigned)maximumNumberOfRows;
-(FBScenePath *)scenePath;
-(unsigned)itemStyle;
-(UIColor *)itemsBackgroundColor;
-(UIColor *)itemBorderLineColor;
-(float)itemBorderLineWidth;
-(char)scrollable;
-(id)_initWithMaximumNumberOfItems:(unsigned)arg1 maximumNumberOfRows:(unsigned)arg2 overflowTotalNumberOfItems:(unsigned)arg3 overflowFont:(id)arg4 overflowTitleLoader:(/*^block*/id)arg5 overflowAccessibilityLabelLoader:(/*^block*/id)arg6 items:(id)arg7 itemSize:(unsigned)arg8 itemStyle:(unsigned)arg9 alignment:(unsigned)arg10 itemDefaultImage:(id)arg11 itemsBackgroundColor:(id)arg12 horizontalItemSpacing:(float)arg13 verticalItemSpacing:(float)arg14 itemBorderLineColor:(id)arg15 itemBorderLineWidth:(float)arg16 insets:(UIEdgeInsets)arg17 scrollable:(char)arg18 backgroundColor:(id)arg19 imageDownloader:(id)arg20 scenePath:(id)arg21 ;
-(unsigned)overflowTotalNumberOfItems;
-(UIFont *)overflowFont;
-(id)overflowTitleLoader;
-(id)overflowAccessibilityLabelLoader;
-(UIImage *)itemDefaultImage;
-(float)horizontalItemSpacing;
-(float)verticalItemSpacing;
-(unsigned)maximumNumberOfItems;
-(UIColor *)backgroundColor;
-(NSArray *)items;
-(unsigned)alignment;
-(unsigned)itemSize;
-(UIEdgeInsets)insets;
@end

