/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:16 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBGLFaceDerivedContext : NSObject {

	float _detectionData[64];
	float _midpoint[2];
	int _activeFaces;

}

@property (nonatomic,readonly) int activeFaces;                   //@synthesize activeFaces=_activeFaces - In the implementation block
@property (nonatomic,readonly) float* detectionData; 
@property (nonatomic,readonly) float* midpoint; 
-(id)initWithFaceData:(id)arg1 ;
-(float*)detectionData;
-(int)activeFaces;
-(float*)midpoint;
@end

