/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:40 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBGraphQLConnectionStoreListener.h>

@protocol OS_dispatch_source;
@class FBGraphQLConnectionStorePersistentPageLoader, NSString, NSObject, FBGraphQLConnectionStoreChunk, FBGraphQLConnectionStorePersistenceCoordinatorListenerAnnouncer;

@interface FBGraphQLConnectionStorePersistenceCoordinator : NSObject <FBGraphQLConnectionStoreListener> {

	char _isLinkedWithStore;
	FBGraphQLConnectionStorePersistentPageLoader* _persistentPageLoader;
	NSString* _diskCacheKey;
	double _persistenceDelay;
	unsigned _persistenceEdgeCountLimit;
	NSObject*<OS_dispatch_source> _coalescenceTimer;
	FBGraphQLConnectionStoreChunk* _pendingChunk;
	/*^block*/id _restoredEdgeFilter;
	int _persistenceStrategy;
	FBGraphQLConnectionStorePersistenceCoordinatorListenerAnnouncer* _announcer;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithDiskCache:(id)arg1 uniqueIdentifier:(id)arg2 persistedEdgeCountLimit:(unsigned)arg3 restoredEdgeFilter:(/*^block*/id)arg4 persistenceDelay:(double)arg5 persistenceStrategy:(int)arg6 ;
-(void)linkWithAndInitializeStateForStore:(id)arg1 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byUpdatingEdgesAtIndexPaths:(id)arg3 ;
-(void)graphQLConnectionStoreDidFinishAttemptingToRestoreFirstPersistedPage:(id)arg1 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byInsertingChunkAtIndex:(unsigned)arg3 userInfo:(id)arg4 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byRemovingChunksAtIndexes:(id)arg3 userInfo:(id)arg4 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byMergingChunkAtIndexWithPrecedingChunk:(unsigned)arg3 userInfo:(id)arg4 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byInsertingEdgesAtIndexPaths:(id)arg3 userInfo:(id)arg4 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byRemovingEdgesAtIndexPaths:(id)arg3 deletionReason:(id)arg4 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byUpdatingLocations:(id)arg3 userInfo:(id)arg4 ;
-(void)fetchPageWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)_persistPendingStateWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)_removeCoalescenceTimer;
-(id)_pageToPersistFromPendingChunk:(id)arg1 ;
-(void)_schedulePersistenceForState:(id)arg1 userInfo:(id)arg2 ;
-(char)_containsIndexPathWithinPersistenceLimit:(id)arg1 ;
-(void)immediatelyPersistPendingStateWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)removeListener:(id)arg1 ;
-(void)addListener:(id)arg1 ;
@end

