/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:25 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBHigherValueAdFeedUnitsQuery : NSObject
+(id)graphQLQueryWithDevice:(id)arg1 feedbackIncludeSeenBy:(id)arg2 fetchHeaderForStorySetSocialContext:(id)arg3 formatType:(id)arg4 genericAttachmentFallbackSquareImageDimension:(id)arg5 genericAttachmentLargeSquareImageDimension:(id)arg6 genericAttachmentPortraitImageHeight:(id)arg7 genericAttachmentPortraitImageWidth:(id)arg8 genericAttachmentSmallCoverImageHeight:(id)arg9 genericAttachmentSmallCoverImageWidth:(id)arg10 genericAttachmentSmallSquareImageDimension:(id)arg11 genericAttachmentTallCoverImageHeight:(id)arg12 genericAttachmentTallCoverImageWidth:(id)arg13 genericAttachmentTallCoverImageWidthNoScale:(id)arg14 inChannelsExperiment:(id)arg15 includeAdminInfo:(id)arg16 includeDrafts:(id)arg17 includeProfileBadge:(id)arg18 includeProfileVideo:(id)arg19 inlineCommentsSurroundingInterestingCommentCount:(id)arg20 mediaType:(id)arg21 negativeFeedbackLocation:(id)arg22 ntContext:(id)arg23 numBylines:(id)arg24 profilePictureScale:(id)arg25 profileVideoQuality:(id)arg26 renderLocation:(id)arg27 scale:(id)arg28 shouldFetchFeedExpandedComments:(id)arg29 shouldFetchLikeSentence:(id)arg30 shouldShowInlineCommentsSurroundingInterestingComment:(id)arg31 shouldFetchCommentInteractors:(id)arg32 shouldFetchFriendCommenters:(id)arg33 shouldFetchInterestingRepliers:(id)arg34 showInterestingComment:(id)arg35 thresholdDurationForFeedDiscovery:(id)arg36 topicFeedsNewsFeedPills:(id)arg37 unseenAdUnits:(id)arg38 videoThumbnailSize:(id)arg39 videoChannelEntryPageId:(id)arg40 videoChannelEntryPoint:(id)arg41 voiceoverEnabled:(id)arg42 ;
@end

