/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:13 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
@class NSObject, NSDictionary;

@interface FBImageAttributeIndex : NSObject {

	NSObject*<OS_dispatch_queue> _dispatchQueue;
	NSDictionary* _propertyTypeToPropertyMap;
	unsigned _numberOfUncachedAssetPairsDuringLastIndexing;

}

@property (nonatomic,readonly) unsigned numberOfUncachedAssetPairsDuringLastIndexing;              //@synthesize numberOfUncachedAssetPairsDuringLastIndexing=_numberOfUncachedAssetPairsDuringLastIndexing - In the implementation block
+(id)sharedInstance;
-(unsigned)numberOfUncachedAssetPairsDuringLastIndexing;
-(void)indexAssets:(id)arg1 configuration:(id)arg2 sortChronologicallyBeforeIndexing:(char)arg3 completion:(/*^block*/id)arg4 ;
-(SCD_Struct_FB69)blurMetricForAssetIdentifier:(id)arg1 ;
-(SCD_Struct_FB69)darkMetricForAssetIdentifier:(id)arg1 ;
-(SCD_Struct_FB69)dupeCoefficientForAssetIdentifierA:(id)arg1 assetIdentifierB:(id)arg2 ;
-(SCD_Struct_FB69)_getValueForIdentifier:(id)arg1 propertyType:(unsigned)arg2 ;
-(void)_indexAssets:(id)arg1 configuration:(id)arg2 sortChronologicallyBeforeIndexing:(char)arg3 shouldBlock:(char)arg4 completion:(/*^block*/id)arg5 ;
-(void)_indexSortedAssets:(id)arg1 configuration:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_setScalarValue:(float)arg1 forPropertyType:(unsigned)arg2 identifier:(id)arg3 persistResult:(char)arg4 ;
-(void)indexAssetsBlocking:(id)arg1 configuration:(id)arg2 ;
-(id)init;
@end

