/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:55 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
@class NSDictionary, NSURLRequest;

@interface FBLigerHTTPRequestProcessObserverUnit : NSObject {

	NSDictionary* _extra;
	time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> > > _startTime;
	time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> > > _endTime;
	NSURLRequest* _request;

}
-(id)extraForRequest:(id)arg1 ;
-(char)request:(id)arg1 startedAtTimestamp:(time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> > >)arg2 ;
-(char)request:(id)arg1 completedWithResponse:(id)arg2 events:(const vector<proxygen::TraceEvent, std::__1::allocator<proxygen::TraceEvent> >*)arg3 atTimestamp:(time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> > >)arg4 ;
-(char)request:(id)arg1 failedWithError:(id)arg2 events:(const vector<proxygen::TraceEvent, std::__1::allocator<proxygen::TraceEvent> >*)arg3 atTimestamp:(time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> > >)arg4 ;
-(char)request:(id)arg1 wasCancelledWithEvents:(const vector<proxygen::TraceEvent, std::__1::allocator<proxygen::TraceEvent> >*)arg2 atTimestamp:(time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> > >)arg3 ;
-(void)logProcessForRequest:(id)arg1 withStatus:(id)arg2 response:(id)arg3 stats:(const RequestStats*)arg4 ;
-(long long)getID;
-(long long)getLoggingRate;
-(char)representsRequest:(id)arg1 ;
-(id)initWithRequest:(id)arg1 ;
-(char)shouldLog;
@end

