/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:25 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBLWIEventPromotionAdPreviewFeedUnitQuery : NSObject
+(id)graphQLQueryWithDevice:(id)arg1 eventBoostType:(id)arg2 feedbackIncludeSeenBy:(id)arg3 formatType:(id)arg4 genericAttachmentFallbackSquareImageDimension:(id)arg5 genericAttachmentLargeSquareImageDimension:(id)arg6 genericAttachmentPortraitImageHeight:(id)arg7 genericAttachmentPortraitImageWidth:(id)arg8 genericAttachmentSmallCoverImageHeight:(id)arg9 genericAttachmentSmallCoverImageWidth:(id)arg10 genericAttachmentSmallSquareImageDimension:(id)arg11 genericAttachmentTallCoverImageHeight:(id)arg12 genericAttachmentTallCoverImageWidth:(id)arg13 genericAttachmentTallCoverImageWidthNoScale:(id)arg14 inChannelsExperiment:(id)arg15 includeProfileBadge:(id)arg16 includeProfileVideo:(id)arg17 mediaType:(id)arg18 numBylines:(id)arg19 profileVideoQuality:(id)arg20 renderLocation:(id)arg21 scale:(id)arg22 targetID:(id)arg23 topicFeedsNewsFeedPills:(id)arg24 videoThumbnailSize:(id)arg25 videoChannelEntryPageId:(id)arg26 videoChannelEntryPoint:(id)arg27 voiceoverEnabled:(id)arg28 ;
@end

