/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:25 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBMentionsNotificationsQuery : NSObject
+(id)graphQLQueryWithCount:(id)arg1 device:(id)arg2 endCursor:(id)arg3 mediaType:(id)arg4 notifOptionImageScale:(id)arg5 notifOptionSetContext:(id)arg6 notifOptionSetOptionsCount:(id)arg7 notifOptionSetsCount:(id)arg8 notificationDeltaCacheIDs:(id)arg9 notificationFeedbackReactionsCount:(id)arg10 notificationFeedbackReactionsFloatingEffect:(id)arg11 notificationFeedbackReactionsType:(id)arg12 renderLocation:(id)arg13 scale:(id)arg14 source:(id)arg15 startCursor:(id)arg16 ;
@end

