/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:09 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface FBMediaPickerTraits : FBValueObject <NSCopying> {

	char _allowTagging;
	char _allowFaceDetection;
	char _requireSquarePhoto;
	char _allowFullScreenPhotoViewing;
	char _allowPhotoEditing;
	char _cpuFiltersEnabled;
	char _autoNavigationEnabled;
	char _longPressToBringUpGalleryView;
	char _shouldRestoreCompositionOnCancel;
	char _stickersAllowed;
	char _textOnPhotosAllowed;
	char _doodlesOnPhotosAllowed;
	char _canSelectMultiplePhotosAndVideos;
	char _canShowMovies;
	char _allowVideoAutoplay;
	char _allowVideoTagging;
	char _forceShowingCheckMarkForThumbnails;
	unsigned _maxPhotosSelected;
	unsigned _postSelectionAction;
	NSString* _actionButtonTitle;
	unsigned _maxVideoLength;
	CGSize _minVideoResolution;

}

@property (nonatomic,readonly) char allowTagging;                                    //@synthesize allowTagging=_allowTagging - In the implementation block
@property (nonatomic,readonly) char allowFaceDetection;                              //@synthesize allowFaceDetection=_allowFaceDetection - In the implementation block
@property (nonatomic,readonly) unsigned maxPhotosSelected;                           //@synthesize maxPhotosSelected=_maxPhotosSelected - In the implementation block
@property (nonatomic,readonly) char requireSquarePhoto;                              //@synthesize requireSquarePhoto=_requireSquarePhoto - In the implementation block
@property (nonatomic,readonly) char allowFullScreenPhotoViewing;                     //@synthesize allowFullScreenPhotoViewing=_allowFullScreenPhotoViewing - In the implementation block
@property (nonatomic,readonly) char allowPhotoEditing;                               //@synthesize allowPhotoEditing=_allowPhotoEditing - In the implementation block
@property (nonatomic,readonly) char cpuFiltersEnabled;                               //@synthesize cpuFiltersEnabled=_cpuFiltersEnabled - In the implementation block
@property (nonatomic,readonly) char autoNavigationEnabled;                           //@synthesize autoNavigationEnabled=_autoNavigationEnabled - In the implementation block
@property (nonatomic,readonly) char longPressToBringUpGalleryView;                   //@synthesize longPressToBringUpGalleryView=_longPressToBringUpGalleryView - In the implementation block
@property (nonatomic,readonly) unsigned postSelectionAction;                         //@synthesize postSelectionAction=_postSelectionAction - In the implementation block
@property (nonatomic,copy,readonly) NSString * actionButtonTitle;                    //@synthesize actionButtonTitle=_actionButtonTitle - In the implementation block
@property (nonatomic,readonly) char shouldRestoreCompositionOnCancel;                //@synthesize shouldRestoreCompositionOnCancel=_shouldRestoreCompositionOnCancel - In the implementation block
@property (nonatomic,readonly) unsigned maxVideoLength;                              //@synthesize maxVideoLength=_maxVideoLength - In the implementation block
@property (nonatomic,readonly) char stickersAllowed;                                 //@synthesize stickersAllowed=_stickersAllowed - In the implementation block
@property (nonatomic,readonly) char textOnPhotosAllowed;                             //@synthesize textOnPhotosAllowed=_textOnPhotosAllowed - In the implementation block
@property (nonatomic,readonly) char doodlesOnPhotosAllowed;                          //@synthesize doodlesOnPhotosAllowed=_doodlesOnPhotosAllowed - In the implementation block
@property (nonatomic,readonly) char canSelectMultiplePhotosAndVideos;                //@synthesize canSelectMultiplePhotosAndVideos=_canSelectMultiplePhotosAndVideos - In the implementation block
@property (nonatomic,readonly) char canShowMovies;                                   //@synthesize canShowMovies=_canShowMovies - In the implementation block
@property (nonatomic,readonly) CGSize minVideoResolution;                            //@synthesize minVideoResolution=_minVideoResolution - In the implementation block
@property (nonatomic,readonly) char allowVideoAutoplay;                              //@synthesize allowVideoAutoplay=_allowVideoAutoplay - In the implementation block
@property (nonatomic,readonly) char allowVideoTagging;                               //@synthesize allowVideoTagging=_allowVideoTagging - In the implementation block
@property (nonatomic,readonly) char forceShowingCheckMarkForThumbnails;              //@synthesize forceShowingCheckMarkForThumbnails=_forceShowingCheckMarkForThumbnails - In the implementation block
-(unsigned)maxVideoLength;
-(char)allowFaceDetection;
-(char)canSelectMultiplePhotosAndVideos;
-(char)forceShowingCheckMarkForThumbnails;
-(char)longPressToBringUpGalleryView;
-(char)allowFullScreenPhotoViewing;
-(unsigned)maxPhotosSelected;
-(CGSize)minVideoResolution;
-(char)canShowMovies;
-(char)allowVideoAutoplay;
-(id)initWithAllowTagging:(char)arg1 allowFaceDetection:(char)arg2 maxPhotosSelected:(unsigned)arg3 requireSquarePhoto:(char)arg4 allowFullScreenPhotoViewing:(char)arg5 allowPhotoEditing:(char)arg6 cpuFiltersEnabled:(char)arg7 autoNavigationEnabled:(char)arg8 longPressToBringUpGalleryView:(char)arg9 postSelectionAction:(unsigned)arg10 actionButtonTitle:(id)arg11 shouldRestoreCompositionOnCancel:(char)arg12 maxVideoLength:(unsigned)arg13 stickersAllowed:(char)arg14 textOnPhotosAllowed:(char)arg15 doodlesOnPhotosAllowed:(char)arg16 canSelectMultiplePhotosAndVideos:(char)arg17 canShowMovies:(char)arg18 minVideoResolution:(CGSize)arg19 allowVideoAutoplay:(char)arg20 allowVideoTagging:(char)arg21 forceShowingCheckMarkForThumbnails:(char)arg22 ;
-(char)allowVideoTagging;
-(char)allowPhotoEditing;
-(unsigned)postSelectionAction;
-(char)stickersAllowed;
-(char)textOnPhotosAllowed;
-(char)doodlesOnPhotosAllowed;
-(char)shouldRestoreCompositionOnCancel;
-(char)allowTagging;
-(char)requireSquarePhoto;
-(char)autoNavigationEnabled;
-(char)cpuFiltersEnabled;
-(NSString *)actionButtonTitle;
@end

