/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:02 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/ZRTariffedSessionTaskDelegate.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBLocationAuthorizationListener.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBSessionClassProvidable.h>

@protocol FBLocationManagerSubscription, FBMAppProperties;
@class ZRTariffedUxSessionCookie, ZRTariffedSessionTask, FBUserSession, CLLocation, FBMLocationUpdateListenerAnnouncer, NSString;

@interface FBMLocationUpdater : NSObject <ZRTariffedSessionTaskDelegate, FBLocationAuthorizationListener, FBSessionClassProvidable> {

	char _startWhenSessionBecomesValid;
	ZRTariffedUxSessionCookie* _session;
	id<FBLocationManagerSubscription> _locationManagerToken;
	ZRTariffedSessionTask* _sessionTask;
	FBUserSession* _userSession;
	CLLocation* _lastLocationAccurate;
	CLLocation* _lastLocationLatest;
	FBMLocationUpdateListenerAnnouncer* _announcer;
	id<FBMAppProperties> _appProperties;

}

@property (assign,nonatomic) char startWhenSessionBecomesValid;                                   //@synthesize startWhenSessionBecomesValid=_startWhenSessionBecomesValid - In the implementation block
@property (nonatomic,retain) id<FBLocationManagerSubscription> locationManagerToken;              //@synthesize locationManagerToken=_locationManagerToken - In the implementation block
@property (nonatomic,retain) ZRTariffedSessionTask * sessionTask;                                 //@synthesize sessionTask=_sessionTask - In the implementation block
@property (nonatomic,retain) FBUserSession * userSession;                                         //@synthesize userSession=_userSession - In the implementation block
@property (nonatomic,retain) CLLocation * lastLocationAccurate;                                   //@synthesize lastLocationAccurate=_lastLocationAccurate - In the implementation block
@property (nonatomic,retain) CLLocation * lastLocationLatest;                                     //@synthesize lastLocationLatest=_lastLocationLatest - In the implementation block
@property (nonatomic,retain) FBMLocationUpdateListenerAnnouncer * announcer;                      //@synthesize announcer=_announcer - In the implementation block
@property (nonatomic,retain) id<FBMAppProperties> appProperties;                                  //@synthesize appProperties=_appProperties - In the implementation block
@property (nonatomic,retain,readonly) ZRTariffedUxSessionCookie * session;                        //@synthesize session=_session - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(FBMLocationUpdateListenerAnnouncer *)announcer;
-(void)setAnnouncer:(FBMLocationUpdateListenerAnnouncer *)arg1 ;
-(void)setAppProperties:(id<FBMAppProperties>)arg1 ;
-(id<FBMAppProperties>)appProperties;
-(char)locationIsDisabled;
-(id)initWithNonZeroRatedSession:(id)arg1 userSession:(id)arg2 appProperties:(id)arg3 ;
-(void)_stopUpdatingLocation;
-(id<FBLocationManagerSubscription>)locationManagerToken;
-(CLLocation *)lastLocationAccurate;
-(void)_subscribeToLocationManager;
-(void)_unregisterLocationManager;
-(void)_locationUpdaterDidUpdateLocation:(id)arg1 error:(id)arg2 ;
-(void)setLocationManagerToken:(id<FBLocationManagerSubscription>)arg1 ;
-(void)setLastLocationAccurate:(CLLocation *)arg1 ;
-(void)setLastLocationLatest:(CLLocation *)arg1 ;
-(void)_startLocationListeningIfNeeded;
-(void)nonZeroRatedSessionTaskMayActivate:(id)arg1 ;
-(void)nonZeroRatedSessionTaskMustDeactivate:(id)arg1 ;
-(void)locationAuthorizationDidChange:(int)arg1 ;
-(CLLocation *)lastLocationLatest;
-(char)startWhenSessionBecomesValid;
-(void)setStartWhenSessionBecomesValid:(char)arg1 ;
-(ZRTariffedUxSessionCookie *)session;
-(void)dealloc;
-(void)_reset;
-(void)removeListener:(id)arg1 ;
-(void)addListener:(id)arg1 ;
-(FBUserSession *)userSession;
-(void)setUserSession:(FBUserSession *)arg1 ;
-(ZRTariffedSessionTask *)sessionTask;
-(void)setSessionTask:(ZRTariffedSessionTask *)arg1 ;
@end

