/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:08 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <UIKit/UIView.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBCropBottomBarDelegate.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBMediaTopNavigationBarDelegation.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBMediaGalleryTopBarDelegate.h>
#import <UIKit/UIScrollViewDelegate.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBMoveAndScaleViewProtocol.h>

@protocol FBMoveAndScaleViewDelegate;
@class UIView, NSArray, FBMediaTopNavigationBar, FBMediaGalleryTopBar, FBMediaGallerySecondaryBar, UIImageView, UIButton, FBCropConstraintView, UIScrollView, FBPhotoCropInfo, UIImage, FBCropBottomBar, NSString;

@interface FBMoveAndScaleView : UIView <FBCropBottomBarDelegate, FBMediaTopNavigationBarDelegation, FBMediaGalleryTopBarDelegate, UIScrollViewDelegate, FBMoveAndScaleViewProtocol> {

	FBMediaTopNavigationBar* _cropTopBar;
	FBMediaGalleryTopBar* _mediaGalleryTopBar;
	unsigned _mediaPickerStyle;
	float _cropSquareRatio;
	float _fallBackMaxZoomScale;
	char _inUnifiedMediaGalleryExperiment;
	UIView* _bannerView;
	UIView* _privacyMessageView;
	FBMediaGallerySecondaryBar* _secondaryBar;
	char _scrollViewUpdated;
	UIImageView* _constraintOverlayView;
	UIView* _topLineView;
	UIView* _bottomLineView;
	int _scrollViewOrientation;
	char _rotationButtonTapped;
	id<FBMoveAndScaleViewDelegate> _delegate;
	int _interfaceOrientation;
	float _topLayoutGuideLength;
	UIButton* _rotationButton;
	FBCropConstraintView* _cropConstraintView;
	UIScrollView* _scrollView;
	FBPhotoCropInfo* _cropInfo;
	NSArray* _initialCropPoints;
	UIImageView* _imageView;
	UIImage* _image;
	FBCropBottomBar* _bottomBar;
	float _minimumZoomScale;
	float _maximumZoomScale;
	CGSize _minimumCroppedSize;
	CGPoint _centerContentOffset;

}

@property (nonatomic,retain) UIImageView * imageView;                                     //@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,retain) UIImage * image;                                             //@synthesize image=_image - In the implementation block
@property (nonatomic,retain) FBCropBottomBar * bottomBar;                                 //@synthesize bottomBar=_bottomBar - In the implementation block
@property (assign,nonatomic) float minimumZoomScale;                                      //@synthesize minimumZoomScale=_minimumZoomScale - In the implementation block
@property (assign,nonatomic) float maximumZoomScale;                                      //@synthesize maximumZoomScale=_maximumZoomScale - In the implementation block
@property (assign,nonatomic) CGPoint centerContentOffset;                                 //@synthesize centerContentOffset=_centerContentOffset - In the implementation block
@property (assign,nonatomic,__weak) id<FBMoveAndScaleViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) int interfaceOrientation;                                    //@synthesize interfaceOrientation=_interfaceOrientation - In the implementation block
@property (assign,nonatomic) float topLayoutGuideLength;                                  //@synthesize topLayoutGuideLength=_topLayoutGuideLength - In the implementation block
@property (assign,nonatomic) CGSize minimumCroppedSize;                                   //@synthesize minimumCroppedSize=_minimumCroppedSize - In the implementation block
@property (nonatomic,readonly) UIButton * rotationButton;                                 //@synthesize rotationButton=_rotationButton - In the implementation block
@property (nonatomic,retain) FBCropConstraintView * cropConstraintView;                   //@synthesize cropConstraintView=_cropConstraintView - In the implementation block
@property (nonatomic,retain) UIScrollView * scrollView;                                   //@synthesize scrollView=_scrollView - In the implementation block
@property (nonatomic,retain) FBPhotoCropInfo * cropInfo;                                  //@synthesize cropInfo=_cropInfo - In the implementation block
@property (assign,nonatomic) char rotationButtonTapped;                                   //@synthesize rotationButtonTapped=_rotationButtonTapped - In the implementation block
@property (nonatomic,copy) NSArray * initialCropPoints;                                   //@synthesize initialCropPoints=_initialCropPoints - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) UIView * asUIView; 
-(void)setTopLayoutGuideLength:(float)arg1 ;
-(float)topLayoutGuideLength;
-(void)didTapLeftButton:(id)arg1 ;
-(void)didTapRightButton:(id)arg1 ;
-(FBPhotoCropInfo *)cropInfo;
-(void)setCropInfo:(FBPhotoCropInfo *)arg1 ;
-(FBCropConstraintView *)cropConstraintView;
-(void)setCropConstraintView:(FBCropConstraintView *)arg1 ;
-(UIView *)asUIView;
-(void)zoomToCropSquareAnimated:(char)arg1 ;
-(void)swapInHighResolutionImage:(id)arg1 ;
-(void)setRotationButtonTapped:(char)arg1 ;
-(id)getCurrentCropPoints;
-(NSArray *)initialCropPoints;
-(UIButton *)rotationButton;
-(void)setMinimumCroppedSize:(CGSize)arg1 ;
-(id)initWithFrame:(CGRect)arg1 image:(id)arg2 interfaceOrientation:(int)arg3 topBarTitle:(id)arg4 topBarRightButtonTitle:(id)arg5 photoCropInfo:(id)arg6 cropSquareRatio:(float)arg7 fallbackMaxZoomScale:(float)arg8 mediaPickerStyle:(unsigned)arg9 inUnifiedMediaGalleryExperiment:(char)arg10 mediaGalleryTopBarConfiguration:(id)arg11 bannerView:(id)arg12 privacyMessageView:(id)arg13 constraintOverlay:(id)arg14 ;
-(void)galleryTopBarDidTapBackButton:(id)arg1 ;
-(void)galleryTopBarDidTapSelectButton:(id)arg1 ;
-(void)cropBottomBarDidTapCropOptionsButton:(id)arg1 ;
-(void)aspectRatioLockButtonTapped:(id)arg1 ;
-(void)presetRotationButtonTapped:(id)arg1 ;
-(CGSize)minimumCroppedSize;
-(void)hideCropConstraintView;
-(void)hideBottomBar:(char)arg1 ;
-(char)isBottomBarHidden;
-(void)_updateScrollViewWithFrame:(CGRect)arg1 image:(id)arg2 ;
-(void)_setupCropConstraintView:(CGRect)arg1 ;
-(void)_setupToolbarWithFrame:(CGRect)arg1 ;
-(void)_updateScrollViewScaleAndOffset;
-(char)rotationButtonTapped;
-(CGRect)_cropRectangleForFrame:(CGRect)arg1 ;
-(void)_zoomToCropRectWithCropInfo:(id)arg1 animated:(char)arg2 ;
-(id)_standardCropInfo;
-(float)_zoomScaleForPreviousScrollView;
-(CGPoint)_getContentOffsetForPreviousScrollView;
-(void)setInitialCropPoints:(NSArray *)arg1 ;
-(float)_calculateMaximumZoomScale;
-(float)_initialZoomScaleForPreviousScrollView;
-(CGPoint)_getInitialContentOffsetForPreviousScrollView;
-(void)setCenterContentOffset:(CGPoint)arg1 ;
-(id)initWithFrame:(CGRect)arg1 image:(id)arg2 interfaceOrientation:(int)arg3 topBarTitle:(id)arg4 topBarRightButtonTitle:(id)arg5 mediaPickerStyle:(unsigned)arg6 inUnifiedMediaGalleryExperiment:(char)arg7 mediaGalleryTopBarConfiguration:(id)arg8 bannerView:(id)arg9 privacyMessageView:(id)arg10 ;
-(void)zoomToPhotoCrop:(id)arg1 animated:(char)arg2 ;
-(CGPoint)centerContentOffset;
-(void)setImage:(UIImage *)arg1 ;
-(void)setDelegate:(id<FBMoveAndScaleViewDelegate>)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(char)arg2 ;
-(id)viewForZoomingInScrollView:(id)arg1 ;
-(void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3 ;
-(id<FBMoveAndScaleViewDelegate>)delegate;
-(int)interfaceOrientation;
-(void)setInterfaceOrientation:(int)arg1 ;
-(void)setScrollView:(UIScrollView *)arg1 ;
-(UIScrollView *)scrollView;
-(UIImage *)image;
-(float)minimumZoomScale;
-(void)setMinimumZoomScale:(float)arg1 ;
-(void)setMaximumZoomScale:(float)arg1 ;
-(float)maximumZoomScale;
-(UIImageView *)imageView;
-(void)setImageView:(UIImageView *)arg1 ;
-(id)_topBar;
-(void)setBottomBar:(FBCropBottomBar *)arg1 ;
-(FBCropBottomBar *)bottomBar;
@end

