/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:21 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBModalAnimatedTransitioning.h>

@protocol FBModalAnimatedTransitioning <NSObject>
@optional
-(void)animationEnded:(char)arg1;

@required
-(void)animateTransition:(id)arg1 withAnimationGroup:(id)arg2 completion:(/*^block*/id)arg3;
-(float)animationDuration;

@end


@protocol FBModalAnimation;
@class NSString;

@interface FBModalAnimatedTransitioning : NSObject <FBModalAnimatedTransitioning> {

	id<FBModalAnimation> _animation;
	char _isPresenting;

}

@property (nonatomic,readonly) char isPresenting;                           //@synthesize isPresenting=_isPresenting - In the implementation block
@property (nonatomic,readonly) id<FBModalAnimation> animation;              //@synthesize animation=_animation - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)animateTransition:(id)arg1 withAnimationGroup:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)initForPresentation:(char)arg1 withAnimation:(id)arg2 ;
-(id<FBModalAnimation>)animation;
-(float)animationDuration;
-(char)isPresenting;
@end

