/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:23:01 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBMThreadSummaryTypeProperties, FBMThreadCustomizationInfo, FBMIndexedThreadParticipationInfoSet, FBMThreadSnippet, NSSet, NSDictionary, FBMThreadSummaryFetchStatus;

@interface FBMThreadSummaryBuilder : NSObject {

	FBMThreadSummaryTypeProperties* _typeProperties;
	int _ephemeralMessageLifeTime;
	FBMThreadCustomizationInfo* _customizationInfo;
	unsigned _statusForViewer;
	long long _mutedUntil;
	unsigned long long _timestamp;
	FBMIndexedThreadParticipationInfoSet* _participationInfoCollection;
	unsigned _numberOfMessages;
	unsigned _numberOfUnreadMessages;
	unsigned _folderType;
	char _isArchived;
	FBMThreadSnippet* _snippet;
	char _isFlaggedAsImportant;
	NSSet* _eventReminders;
	NSDictionary* _gameData;
	FBMThreadSummaryFetchStatus* _fetchStatus;

}
+(id)threadSummary;
+(id)threadSummaryFromExistingThreadSummary:(id)arg1 ;
-(id)withFetchStatus:(id)arg1 ;
-(id)withTimestamp:(unsigned long long)arg1 ;
-(id)withNumberOfMessages:(unsigned)arg1 ;
-(id)withNumberOfUnreadMessages:(unsigned)arg1 ;
-(id)withIsArchived:(char)arg1 ;
-(id)withCustomizationInfo:(id)arg1 ;
-(id)withEphemeralMessageLifeTime:(int)arg1 ;
-(id)withEventReminders:(id)arg1 ;
-(id)withIsFlaggedAsImportant:(char)arg1 ;
-(id)withFolderType:(unsigned)arg1 ;
-(id)withGameData:(id)arg1 ;
-(id)withMutedUntil:(long long)arg1 ;
-(id)withParticipationInfoCollection:(id)arg1 ;
-(id)withTypeProperties:(id)arg1 ;
-(id)withStatusForViewer:(unsigned)arg1 ;
-(id)withSnippet:(id)arg1 ;
-(id)build;
@end

