/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:04 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBPhotoAttachmentProtocol.h>

@class CLLocation, NSArray, FBPhotoAssetEdits, NSMutableArray, NSString, UIImage, FBAssetMetadata, NSDate, NSDictionary;

@interface FBPlatformPhotoAttachment : NSObject <FBPhotoAttachmentProtocol> {

	NSMutableArray* _publishedPhotoTags;
	char _allowEditing;
	char _allowRemoval;
	char _showServerProcessingProgress;
	NSString* _caption;
	NSArray* _mentions;
	UIImage* _thumbnailImage;
	NSString* _assetID;
	FBAssetMetadata* _metadata;
	NSDate* _creationDate;
	NSArray* _tagsEdges;
	NSString* _dataSourceID;
	NSString* _dataSourceDescription;
	UIImage* _displayImage;
	UIImage* _image;
	unsigned _indexHint;
	FBPhotoAssetEdits* _edits;
	NSDictionary* _platformPhotoMetadata;

}

@property (nonatomic,retain) UIImage * thumbnailImage;                                                 //@synthesize thumbnailImage=_thumbnailImage - In the implementation block
@property (assign,nonatomic) char allowEditing;                                                        //@synthesize allowEditing=_allowEditing - In the implementation block
@property (assign,nonatomic) char allowRemoval;                                                        //@synthesize allowRemoval=_allowRemoval - In the implementation block
@property (nonatomic,copy) NSString * assetID;                                                         //@synthesize assetID=_assetID - In the implementation block
@property (nonatomic,readonly) FBAssetMetadata * metadata;                                             //@synthesize metadata=_metadata - In the implementation block
@property (nonatomic,retain) NSDate * creationDate;                                                    //@synthesize creationDate=_creationDate - In the implementation block
@property (nonatomic,retain) CLLocation * location; 
@property (nonatomic,copy) NSArray * publishedPhotoTags;                                               //@synthesize publishedPhotoTags=_publishedPhotoTags - In the implementation block
@property (nonatomic,copy) NSArray * tagsEdges;                                                        //@synthesize tagsEdges=_tagsEdges - In the implementation block
@property (nonatomic,copy,readonly) NSString * dataSourceID;                                           //@synthesize dataSourceID=_dataSourceID - In the implementation block
@property (nonatomic,copy,readonly) NSString * dataSourceDescription;                                  //@synthesize dataSourceDescription=_dataSourceDescription - In the implementation block
@property (nonatomic,retain) UIImage * displayImage;                                                   //@synthesize displayImage=_displayImage - In the implementation block
@property (nonatomic,readonly) UIImage * image;                                                        //@synthesize image=_image - In the implementation block
@property (assign,nonatomic) unsigned indexHint;                                                       //@synthesize indexHint=_indexHint - In the implementation block
@property (assign,nonatomic) char showServerProcessingProgress;                                        //@synthesize showServerProcessingProgress=_showServerProcessingProgress - In the implementation block
@property (nonatomic,retain) FBPhotoAssetEdits * edits;                                                //@synthesize edits=_edits - In the implementation block
@property (nonatomic,retain) NSDictionary * platformPhotoMetadata;                                     //@synthesize platformPhotoMetadata=_platformPhotoMetadata - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy) NSString * caption;                                                         //@synthesize caption=_caption - In the implementation block
@property (nonatomic,copy) NSArray * mentions;                                                         //@synthesize mentions=_mentions - In the implementation block
@property (nonatomic,readonly) char requiresUpload; 
@property (nonatomic,readonly) char selectedFromMultiPicker; 
@property (nonatomic,copy,readonly) NSString * existingFBID; 
@property (nonatomic,readonly) char isLivePhoto; 
@property (nonatomic,copy,readonly) NSString * nameOfServerAssetIDFieldOverridingFileURL; 
@property (nonatomic,readonly) CGSize imageSize; 
+(id)propertiesToSkipForCoding;
-(NSString *)assetID;
-(void)loadImageDataForUploadWithCompressionRate:(float)arg1 maximumDimension:(int)arg2 specialCasePanoramas:(char)arg3 loggingBlock:(/*^block*/id)arg4 completionBlock:(/*^block*/id)arg5 ;
-(unsigned)indexHint;
-(void)setIndexHint:(unsigned)arg1 ;
-(FBPhotoAssetEdits *)edits;
-(id)visualDedupRepresentation;
-(char)allowRemoval;
-(void)setAllowRemoval:(char)arg1 ;
-(char)requiresUpload;
-(char)selectedFromMultiPicker;
-(NSString *)existingFBID;
-(char)showServerProcessingProgress;
-(void)setShowServerProcessingProgress:(char)arg1 ;
-(char)isLivePhoto;
-(NSString *)nameOfServerAssetIDFieldOverridingFileURL;
-(void)setDisplayImage:(UIImage *)arg1 ;
-(char)supportsQualitySampling;
-(char)isPhotoCropped;
-(NSArray *)publishedPhotoTags;
-(NSArray *)tagsEdges;
-(void)setTagsEdges:(NSArray *)arg1 ;
-(void)setEdits:(FBPhotoAssetEdits *)arg1 ;
-(char)is360Photo;
-(void)setAssetID:(NSString *)arg1 ;
-(void)setPublishedPhotoTags:(NSArray *)arg1 ;
-(NSString *)dataSourceDescription;
-(NSDictionary *)platformPhotoMetadata;
-(void)setPlatformPhotoMetadata:(NSDictionary *)arg1 ;
-(id)initWithAssetID:(id)arg1 platformPhotoMetadata:(id)arg2 ;
-(NSString *)dataSourceID;
-(void)setAllowEditing:(char)arg1 ;
-(char)allowEditing;
-(float)aspectRatio;
-(NSDate *)creationDate;
-(void)setCreationDate:(NSDate *)arg1 ;
-(UIImage *)thumbnailImage;
-(void)setMentions:(NSArray *)arg1 ;
-(NSArray *)mentions;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(UIImage *)image;
-(CGSize)imageSize;
-(CLLocation *)location;
-(void)setLocation:(CLLocation *)arg1 ;
-(UIImage *)displayImage;
-(NSString *)caption;
-(void)setCaption:(NSString *)arg1 ;
-(FBAssetMetadata *)metadata;
-(void)setThumbnailImage:(UIImage *)arg1 ;
-(unsigned)attachmentType;
@end

