/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:06 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSError;

@interface FBPublicationError : FBValueObject <NSCopying> {

	unsigned _type;
	NSString* _humanizedErrorTitle;
	NSString* _humanizedErrorDescription;
	NSString* _developerFacingDescription;
	int _errorCode;
	int _errorSubcode;
	NSError* _serverError;

}

@property (nonatomic,readonly) unsigned type;                                           //@synthesize type=_type - In the implementation block
@property (nonatomic,copy,readonly) NSString * humanizedErrorTitle;                     //@synthesize humanizedErrorTitle=_humanizedErrorTitle - In the implementation block
@property (nonatomic,copy,readonly) NSString * humanizedErrorDescription;               //@synthesize humanizedErrorDescription=_humanizedErrorDescription - In the implementation block
@property (nonatomic,copy,readonly) NSString * developerFacingDescription;              //@synthesize developerFacingDescription=_developerFacingDescription - In the implementation block
@property (nonatomic,readonly) int errorCode;                                           //@synthesize errorCode=_errorCode - In the implementation block
@property (nonatomic,readonly) int errorSubcode;                                        //@synthesize errorSubcode=_errorSubcode - In the implementation block
@property (nonatomic,copy,readonly) NSError * serverError;                              //@synthesize serverError=_serverError - In the implementation block
-(id)initWithType:(unsigned)arg1 humanizedErrorTitle:(id)arg2 humanizedErrorDescription:(id)arg3 developerFacingDescription:(id)arg4 errorCode:(int)arg5 errorSubcode:(int)arg6 serverError:(id)arg7 ;
-(NSString *)developerFacingDescription;
-(int)errorSubcode;
-(NSString *)humanizedErrorTitle;
-(NSString *)humanizedErrorDescription;
-(unsigned)type;
-(NSError *)serverError;
-(int)errorCode;
@end

