/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:53 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBGraphQLInput.h>

@class NSString;

@interface FBStoryCreateInputDataInlineActivities : FBGraphQLInput {

	NSString* _taggableActivityId;
	NSString* _objectId;
	NSString* _isProfileBadgePost;
	NSString* _objectText;
	NSString* _objectAttachmentBehavior;
	NSString* _suggestionMechanism;
	NSString* _iconId;

}

@property (nonatomic,copy) NSString * taggableActivityId;                    //@synthesize taggableActivityId=_taggableActivityId - In the implementation block
@property (nonatomic,copy) NSString * objectId;                              //@synthesize objectId=_objectId - In the implementation block
@property (nonatomic,copy) NSString * isProfileBadgePost;                    //@synthesize isProfileBadgePost=_isProfileBadgePost - In the implementation block
@property (nonatomic,copy) NSString * objectText;                            //@synthesize objectText=_objectText - In the implementation block
@property (nonatomic,copy) NSString * objectAttachmentBehavior;              //@synthesize objectAttachmentBehavior=_objectAttachmentBehavior - In the implementation block
@property (nonatomic,copy) NSString * suggestionMechanism;                   //@synthesize suggestionMechanism=_suggestionMechanism - In the implementation block
@property (nonatomic,copy) NSString * iconId;                                //@synthesize iconId=_iconId - In the implementation block
-(NSString *)iconId;
-(NSString *)suggestionMechanism;
-(const FBGraphQLInputField*)fieldsMetadataWithOutLength:(out int*)arg1 ;
-(NSString *)taggableActivityId;
-(void)setTaggableActivityId:(NSString *)arg1 ;
-(NSString *)isProfileBadgePost;
-(void)setIsProfileBadgePost:(NSString *)arg1 ;
-(NSString *)objectText;
-(void)setObjectText:(NSString *)arg1 ;
-(NSString *)objectAttachmentBehavior;
-(void)setObjectAttachmentBehavior:(NSString *)arg1 ;
-(void)setSuggestionMechanism:(NSString *)arg1 ;
-(void)setIconId:(NSString *)arg1 ;
-(NSString *)objectId;
-(void)setObjectId:(NSString *)arg1 ;
@end

