/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:59 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
@class EAGLContext;

@interface FBSurface : NSObject {

	unsigned _texture;
	unsigned _framebuffer;
	unsigned _renderbuffer;
	char _generatedTexture;
	CVOpenGLESTextureCacheRef _textureCache;
	CVBufferRef _cvTexture;
	EAGLContext* _glContext;
	CAEAGLLayer* _layer;
	CGSize _size;
	char _layerRenderBufferStorageNeedsRefresh;
	unsigned char _flipped;
	CVBufferRef _pixelBuffer;
	unsigned _textureTarget;

}

@property (nonatomic,readonly) CGSize size; 
@property (nonatomic,readonly) CVBufferRef pixelBuffer;                           //@synthesize pixelBuffer=_pixelBuffer - In the implementation block
@property (assign,getter=isFlipped,nonatomic) unsigned char flipped;              //@synthesize flipped=_flipped - In the implementation block
@property (nonatomic,readonly) unsigned texture; 
@property (nonatomic,readonly) unsigned textureTarget;                            //@synthesize textureTarget=_textureTarget - In the implementation block
@property (nonatomic,readonly) unsigned framebuffer; 
@property (nonatomic,readonly) unsigned renderbuffer; 
+(id)surfaceWithPixelBufferFromPool:(CVPixelBufferPoolRef)arg1 ;
-(id)initWithPixelBuffer:(CVBufferRef)arg1 ;
-(id)initWithTexture:(unsigned)arg1 target:(unsigned)arg2 size:(CGSize)arg3 ;
-(id)initWithTexture:(unsigned)arg1 size:(CGSize)arg2 ;
-(id)initWithIGTexture:(id)arg1 ;
-(id)initWithFramebuffer:(unsigned)arg1 size:(CGSize)arg2 ;
-(CVBufferRef)pixelBuffer;
-(void)setFlipped:(unsigned char)arg1 ;
-(unsigned)textureTarget;
-(CGSize)size;
-(void)dealloc;
-(id)UIImage;
-(id)initWithSize:(CGSize)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)present;
-(id)initWithLayer:(CAEAGLLayer*)arg1 ;
-(unsigned char)isFlipped;
-(unsigned)texture;
-(unsigned)framebuffer;
-(unsigned)renderbuffer;
@end

