/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:16 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBTextOnPhotoLog : NSObject {

	char _deleted;
	char _shownInComposer;
	unsigned _entryCount;
	unsigned _numberOfCancels;
	unsigned _textOnPhotosAdded;
	unsigned _textOnPhotosRemoved;
	unsigned _textOnPhotosRemovedFromCancels;
	unsigned _totalNumberOfTextOnPhotos;

}

@property (assign,nonatomic) unsigned entryCount;                                  //@synthesize entryCount=_entryCount - In the implementation block
@property (assign,nonatomic) char deleted;                                         //@synthesize deleted=_deleted - In the implementation block
@property (assign,nonatomic) unsigned numberOfCancels;                             //@synthesize numberOfCancels=_numberOfCancels - In the implementation block
@property (assign,nonatomic) unsigned textOnPhotosAdded;                           //@synthesize textOnPhotosAdded=_textOnPhotosAdded - In the implementation block
@property (assign,nonatomic) unsigned textOnPhotosRemoved;                         //@synthesize textOnPhotosRemoved=_textOnPhotosRemoved - In the implementation block
@property (assign,nonatomic) unsigned textOnPhotosRemovedFromCancels;              //@synthesize textOnPhotosRemovedFromCancels=_textOnPhotosRemovedFromCancels - In the implementation block
@property (assign,nonatomic) unsigned totalNumberOfTextOnPhotos;                   //@synthesize totalNumberOfTextOnPhotos=_totalNumberOfTextOnPhotos - In the implementation block
@property (assign,nonatomic) char shownInComposer;                                 //@synthesize shownInComposer=_shownInComposer - In the implementation block
-(void)setEntryCount:(unsigned)arg1 ;
-(char)shownInComposer;
-(void)setShownInComposer:(char)arg1 ;
-(unsigned)numberOfCancels;
-(void)setNumberOfCancels:(unsigned)arg1 ;
-(unsigned)textOnPhotosAdded;
-(void)setTextOnPhotosAdded:(unsigned)arg1 ;
-(unsigned)textOnPhotosRemoved;
-(void)setTextOnPhotosRemoved:(unsigned)arg1 ;
-(unsigned)textOnPhotosRemovedFromCancels;
-(void)setTextOnPhotosRemovedFromCancels:(unsigned)arg1 ;
-(unsigned)totalNumberOfTextOnPhotos;
-(void)setTotalNumberOfTextOnPhotos:(unsigned)arg1 ;
-(char)deleted;
-(void)setDeleted:(char)arg1 ;
-(unsigned)entryCount;
@end

