/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:48 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface FBVideoChannelHeaderViewModel : FBValueObject <NSCopying> {

	char _shouldShowLiveLabel;
	char _isVerified;
	int _liveVideoCount;
	NSString* _liveLabelText;
	NSString* _profilePictureUri;
	NSString* _videoChannelTitle;
	NSString* _videoChannelSubtitle;
	unsigned _videoChannelHeaderStyle;

}

@property (nonatomic,readonly) char shouldShowLiveLabel;                          //@synthesize shouldShowLiveLabel=_shouldShowLiveLabel - In the implementation block
@property (nonatomic,readonly) int liveVideoCount;                                //@synthesize liveVideoCount=_liveVideoCount - In the implementation block
@property (nonatomic,copy,readonly) NSString * liveLabelText;                     //@synthesize liveLabelText=_liveLabelText - In the implementation block
@property (nonatomic,copy,readonly) NSString * profilePictureUri;                 //@synthesize profilePictureUri=_profilePictureUri - In the implementation block
@property (nonatomic,readonly) char isVerified;                                   //@synthesize isVerified=_isVerified - In the implementation block
@property (nonatomic,copy,readonly) NSString * videoChannelTitle;                 //@synthesize videoChannelTitle=_videoChannelTitle - In the implementation block
@property (nonatomic,copy,readonly) NSString * videoChannelSubtitle;              //@synthesize videoChannelSubtitle=_videoChannelSubtitle - In the implementation block
@property (nonatomic,readonly) unsigned videoChannelHeaderStyle;                  //@synthesize videoChannelHeaderStyle=_videoChannelHeaderStyle - In the implementation block
-(char)isVerified;
-(id)initWithShouldShowLiveLabel:(char)arg1 liveVideoCount:(int)arg2 liveLabelText:(id)arg3 profilePictureUri:(id)arg4 isVerified:(char)arg5 videoChannelTitle:(id)arg6 videoChannelSubtitle:(id)arg7 videoChannelHeaderStyle:(unsigned)arg8 ;
-(char)shouldShowLiveLabel;
-(int)liveVideoCount;
-(NSString *)liveLabelText;
-(NSString *)profilePictureUri;
-(unsigned)videoChannelHeaderStyle;
-(NSString *)videoChannelTitle;
-(NSString *)videoChannelSubtitle;
@end

