/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:12 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBClassProvidable.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBWebRTCVoipAudioSessionDelegate.h>

@protocol VideoRenderInfo, FBWebRTCLogger;
@class FBUserSession, FBWebRTCEngineListenerAnnouncer, FBWebRTCInCallEventListenerAnnouncer, NSString, FBWebRTCVoipAudioSession, FBWebRTCCallProperties, FBWebRTCCallConnectionStatus, UIView, FBWebRTCPeerVideoView, FBWebRTCCallStateLogWriter, FBWebRTCRemoteVideoRenderStatusWatchdog, FBTimer, RTCVideoCaptureSession, FBWebRTCCallModel, FBWebRTCRemoteVideoRenderStatus;

@interface FBWebRTCEngine : NSObject <FBClassProvidable, FBWebRTCVoipAudioSessionDelegate> {

	unique_ptr<WebRTCEngine, std::__1::default_delete<WebRTCEngine> >* _nativeEngine;
	WebRTCConfigInterface* _configuration;
	FBUserSession* _userSession;
	FBWebRTCEngineListenerAnnouncer* _announcer;
	FBWebRTCInCallEventListenerAnnouncer* _inCallEventAnnouncer;
	char _engineInitialized;
	int _videoWidth;
	int _videoHeight;
	int _frameRate;
	int _requestedVideoWidth;
	int _requestedVideoHeight;
	int _requestedFrameRate;
	char _isRequestingLowResolution;
	NSString* _frontCameraUniqueId;
	NSString* _backCameraUniqueId;
	FBWebRTCVoipAudioSession* _currentCallAudioSession;
	FBWebRTCCallProperties* _currentCallProperties;
	FBWebRTCCallConnectionStatus* _currentConnectionStatus;
	UIView*<VideoRenderInfo> _rendererWindow;
	FBWebRTCPeerVideoView* _activePeerVideoView;
	id<FBWebRTCLogger> _logger;
	FBWebRTCCallStateLogWriter* _callStateLogWriter;
	FBWebRTCRemoteVideoRenderStatusWatchdog* _remoteVideoRenderStatusWatchdog;
	FBTimer* _escalationTimer;
	RTCVideoCaptureSession* _videoCaptureSession;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) RTCVideoCaptureSession * videoCaptureSession;                           //@synthesize videoCaptureSession=_videoCaptureSession - In the implementation block
@property (nonatomic,readonly) FBWebRTCCallModel * currentCall; 
@property (nonatomic,readonly) FBWebRTCCallConnectionStatus * currentConnectionStatus;                 //@synthesize currentConnectionStatus=_currentConnectionStatus - In the implementation block
@property (nonatomic,readonly) FBWebRTCRemoteVideoRenderStatus * remoteVideoRenderStatus; 
-(id)initWithProviderMapData:(id)arg1 ;
-(long long)currentCallId;
-(id)initWithUserSession:(id)arg1 voipVideoWidth:(int)arg2 voipVideoHeight:(int)arg3 frameRate:(int)arg4 ;
-(FBWebRTCCallModel *)currentCall;
-(void)logApplicationMessage:(id)arg1 inContext:(id)arg2 ;
-(void)acceptCall;
-(RTCVideoCaptureSession *)videoCaptureSession;
-(void)endCall:(int)arg1 ;
-(void)updateRequestedResolutionForChatHead:(char)arg1 ;
-(void)cancelRequestVideoEscalation;
-(void)pauseSendingVideo;
-(void)resumeSendingVideo;
-(void)releaseNativeEngine;
-(void)configureWithNativeEngine:(unique_ptr<WebRTCEngine, std::__1::default_delete<WebRTCEngine> >*)arg1 configuration:(WebRTCConfigInterface*)arg2 logger:(id)arg3 ;
-(char)subscribeToRemoteVideoStream:(id)arg1 ;
-(void)subscribeToLoudestSpeakerVideoStream;
-(void)addInCallEventListener:(id)arg1 ;
-(void)addRemoteVideoRenderStatusListener:(id)arg1 ;
-(char)hasMultipleCameras;
-(FBWebRTCRemoteVideoRenderStatus *)remoteVideoRenderStatus;
-(void)setActivePeerVideoView:(id)arg1 ;
-(void)requestVideoEscalation;
-(void)acceptVideoEscalation;
-(void)declineVideoEscalation;
-(char)canSetSpeakerPhone:(char)arg1 ;
-(void)setSpeakerPhone:(char)arg1 ;
-(void)setAudioOn:(char)arg1 ;
-(id)currentPeerId;
-(void)removeInCallEventListener:(id)arg1 ;
-(void)removeRemoteVideoRenderStatusListener:(id)arg1 ;
-(void)ringUsers:(id)arg1 ;
-(char)_isLocalVideoSupported;
-(id)_createCall:(long long)arg1 ;
-(id)createPeerUsersInfo:(id)arg1 ;
-(void)_startCallWithPeerUser:(id)arg1 callTrigger:(id)arg2 isVideoCall:(char)arg3 callabilityStatus:(id)arg4 ;
-(void)_initalizeCall:(/*^block*/id)arg1 promptForCamera:(char)arg2 andStartCall:(/*^block*/id)arg3 ;
-(void)_startConferenceCallRingingUsers:(id)arg1 callTrigger:(id)arg2 isVideoCall:(char)arg3 serverInfoData:(id)arg4 ;
-(void)_initializeEngineIfNeeded;
-(void)_resetCurrentCall;
-(void)_createAudioSession;
-(void)_configureVideoCaptureForCall;
-(void)_notifyCallStarted:(id)arg1 ;
-(void)_logAbortedOutgoingCallWithFailedDeviceRequest:(unsigned)arg1 ;
-(void)_notifyCallAbortedWithFailedDeviceRequest:(unsigned)arg1 ;
-(void)_promptForCamera:(char)arg1 onSuccess:(/*^block*/id)arg2 onFailure:(/*^block*/id)arg3 ;
-(void)_acceptCall;
-(void)_notifyCallTransitionAborted:(id)arg1 withFailedDeviceRequest:(unsigned)arg2 ;
-(void)_transitionToCallState:(unsigned)arg1 ;
-(void)_updateCallModel:(id)arg1 ;
-(void)_updateIsSpeakerPhone:(char)arg1 ;
-(void)_sendEscalationRequest:(char)arg1 ;
-(void)_deEscalateVideo;
-(void)_sendEscalationResponse:(char)arg1 ;
-(void)_setVideoOn:(char)arg1 ;
-(void)_createRendererWindowIfNeeded;
-(char)isCameraSupported:(unsigned)arg1 ;
-(id)_currentCameraId;
-(void)onVideoEscalationTimeout;
-(void)_notifyCallEnded:(id)arg1 reason:(int)arg2 remoteEnded:(char)arg3 callSummary:(id)arg4 ;
-(void)_startIncomingCall:(long long)arg1 peerUser:(id)arg2 isDirectVideoCall:(char)arg3 ;
-(void)_startIncomingCallWithCollision:(char)arg1 ;
-(void)switchToRinging;
-(void)setRemoteVideoSupported:(char)arg1 callId:(long long)arg2 ;
-(char)_isOneOnOneOverMultiway;
-(void)switchToStreaming:(char)arg1 ;
-(void)onRemoteVideoEscalationResponse:(char)arg1 ;
-(void)onRemoteVideoEscalationRequest:(char)arg1 ;
-(void)removeRemoteVideoTrack:(unsigned)arg1 peerId:(id)arg2 cname:(id)arg3 ;
-(void)_sendEscalationSuccess;
-(void)_startCallTimeTracking;
-(void)_notifyCallConnectionStatusChangedFromConnectionStatus:(id)arg1 toConnectionStatus:(id)arg2 forCall:(id)arg3 ;
-(void)_notifyCallChangedFromState:(id)arg1 toState:(id)arg2 ;
-(void)_initializeAvailableCameras;
-(void)_initializeVideoParameters;
-(void)_resetCameraToDefault;
-(void)_endCallTimeTracking;
-(void)_updateDefaultSpeakerMode;
-(void)_setAudioOutputRoute:(int)arg1 ;
-(void)handleBeginAudioInterrupt;
-(void)handleEndAudioInterrupt;
-(void)audioRouteChangedToSpeakerphone:(char)arg1 ;
-(void)audioRouteUpdated:(int)arg1 ;
-(void)audioVolumeChanged:(int)arg1 ;
-(void)startCallWithPeerUser:(id)arg1 callTrigger:(id)arg2 isVideoCall:(char)arg3 callabilityStatus:(id)arg4 analyticsExtra:(id)arg5 ;
-(void)startCallWithPeerUserUsingMultiway:(id)arg1 callTrigger:(id)arg2 isVideoCall:(char)arg3 callabilityStatus:(id)arg4 analyticsExtra:(id)arg5 ;
-(void)startLiveWithMultiwayVideoCallWithBroadcastId:(id)arg1 callabilityStatus:(id)arg2 analyticsExtra:(id)arg3 ;
-(void)startConferenceCallWithThreadFbId:(id)arg1 participants:(id)arg2 userIdsToRing:(id)arg3 serverInfoData:(id)arg4 callTrigger:(id)arg5 analyticsExtra:(id)arg6 ;
-(char)isVideoCallingSupported;
-(void)setVideoParametersWithCaptureWidth:(int)arg1 captureHeight:(int)arg2 captureFramerate:(int)arg3 requestedWidth:(int)arg4 requestedHeight:(int)arg5 requestedFramerate:(int)arg6 ;
-(void)extendAudioSession:(/*^block*/id)arg1 ;
-(void)initializeCall:(long long)arg1 peerId:(id)arg2 isOutboundCall:(char)arg3 ;
-(void)callEnded:(long long)arg1 reason:(int)arg2 remoteEnded:(char)arg3 endCallSummary:(id)arg4 ;
-(void)startIncomingCall:(long long)arg1 peerUser:(id)arg2 isVideoCall:(char)arg3 ;
-(void)startIncomingConferenceCall:(id)arg1 callId:(long long)arg2 ringType:(int)arg3 peerUsers:(id)arg4 ;
-(void)switchToContacting;
-(void)localMediaStateChanged:(WebRTCMediaState)arg1 ;
-(void)remoteMediaStateChanged:(WebRTCMediaState)arg1 ;
-(void)addRemoteVideoTrack:(unsigned)arg1 peerId:(id)arg2 cname:(id)arg3 ;
-(void)onCallJoined:(char)arg1 ;
-(void)onLoudestSpeakerUpdate:(id)arg1 cname:(id)arg2 ;
-(void)onMediaStatusUpdate:(id)arg1 users:(id)arg2 cnames:(id)arg3 mediaTypes:(id)arg4 states:(id)arg5 ;
-(void)clearRendererWindows;
-(void)onRemoteVideoEscalationSuccess;
-(void)setIsConnected:(char)arg1 isPoorAudioConnection:(char)arg2 isPoorVideoConnection:(char)arg3 connectionQuality:(unsigned)arg4 localVideoState:(unsigned)arg5 remoteVideoState:(unsigned)arg6 isH264Video:(char)arg7 ;
-(void)updateParticipantStates:(id)arg1 isDirectVideoCall:(char)arg2 ;
-(void)onThriftMessage:(id)arg1 withFBTraceMetadata:(id)arg2 withMessageSource:(id)arg3 ;
-(void)handleMultiwaySignalingMessage:(id)arg1 withFBTraceMetadata:(id)arg2 ;
-(void)onMessageSendSuccess:(long long)arg1 callId:(long long)arg2 ;
-(void)onMessageSendError:(long long)arg1 callId:(long long)arg2 errorDomain:(id)arg3 errorCode:(int)arg4 errorDescription:(id)arg5 ;
-(void)onMultiwayMessageSendSuccess:(id)arg1 conferenceName:(id)arg2 ;
-(void)onMultiwayMessageSendError:(id)arg1 conferenceName:(id)arg2 error:(id)arg3 ;
-(void)onInputeAudioLevel:(unsigned)arg1 outputAudioLevel:(unsigned)arg2 ;
-(void)onActiveAudioLevels:(id)arg1 ;
-(FBWebRTCCallConnectionStatus *)currentConnectionStatus;
-(void)dealloc;
-(void)removeListener:(id)arg1 ;
-(void)setVideoOrientation:(int)arg1 ;
-(void)addListener:(id)arg1 ;
-(void)setCurrentCamera:(unsigned)arg1 ;
-(void)toggleCamera;
@end

