/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:21:55 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBWebRTCVideoChatHeadsUsageInfo : NSObject {

	char _draggedChatHead;
	unsigned _switchToMessengerCount;
	unsigned _switchToCallScreenCount;
	double _messengerUIDuration;
	double _callScreenDuration;
	double _backgroundDuration;
	double _mutedDuration;

}

@property (assign,nonatomic) unsigned switchToMessengerCount;               //@synthesize switchToMessengerCount=_switchToMessengerCount - In the implementation block
@property (assign,nonatomic) unsigned switchToCallScreenCount;              //@synthesize switchToCallScreenCount=_switchToCallScreenCount - In the implementation block
@property (assign,nonatomic) char draggedChatHead;                          //@synthesize draggedChatHead=_draggedChatHead - In the implementation block
@property (assign,nonatomic) double messengerUIDuration;                    //@synthesize messengerUIDuration=_messengerUIDuration - In the implementation block
@property (assign,nonatomic) double callScreenDuration;                     //@synthesize callScreenDuration=_callScreenDuration - In the implementation block
@property (assign,nonatomic) double backgroundDuration;                     //@synthesize backgroundDuration=_backgroundDuration - In the implementation block
@property (assign,nonatomic) double mutedDuration;                          //@synthesize mutedDuration=_mutedDuration - In the implementation block
-(unsigned)switchToCallScreenCount;
-(unsigned)switchToMessengerCount;
-(char)draggedChatHead;
-(double)messengerUIDuration;
-(double)callScreenDuration;
-(double)backgroundDuration;
-(double)mutedDuration;
-(void)setSwitchToMessengerCount:(unsigned)arg1 ;
-(void)setSwitchToCallScreenCount:(unsigned)arg1 ;
-(void)setDraggedChatHead:(char)arg1 ;
-(void)setMessengerUIDuration:(double)arg1 ;
-(void)setCallScreenDuration:(double)arg1 ;
-(void)setBackgroundDuration:(double)arg1 ;
-(void)setMutedDuration:(double)arg1 ;
@end

