/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:23:05 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBWebDialogsDelegate <NSObject>
@optional
-(void)webDialogsWillDismissDialog:(id)arg1 parameters:(id)arg2 session:(id)arg3 result:(unsigned*)arg4 url:(id*)arg5 error:(id*)arg6;
-(char)webDialogsDialog:(id)arg1 parameters:(id)arg2 session:(id)arg3 shouldAutoHandleURL:(id)arg4;
-(void)webDialogsWillPresentDialog:(id)arg1 parameters:(id)arg2 session:(id)arg3;

@end

