/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:21:55 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBWebRTCHostApplicationListener.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBClassProvidable.h>

@protocol FBWebRTCHostApplication, MNModalPresentation;
@class UIViewController, NSString;

@interface FBWebRTCUIDisplayCoordinator : NSObject <FBWebRTCHostApplicationListener, FBClassProvidable> {

	id<FBWebRTCHostApplication> _hostApplication;
	id<MNModalPresentation> _modalPresentation;
	unsigned _pendingState;
	UIViewController* _vcPendingPresentation;

}

@property (nonatomic,retain) UIViewController * vcPendingPresentation;              //@synthesize vcPendingPresentation=_vcPendingPresentation - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(void)dismissViewController:(id)arg1 animated:(char)arg2 completion:(/*^block*/id)arg3 ;
-(void)hostApplicationReady:(char)arg1 ;
-(void)cancelPendingVCPresentation;
-(void)presentViewControllerModally:(id)arg1 animated:(char)arg2 ;
-(id)initWithHostApplication:(id)arg1 modalPresentation:(id)arg2 ;
-(void)_presentOrDeferViewControllerModally:(id)arg1 animated:(char)arg2 ;
-(char)_isPendingVCPresentation;
-(void)setVcPendingPresentation:(UIViewController *)arg1 ;
-(void)_presentDeferredViewControllerIfNeeded;
-(UIViewController *)vcPendingPresentation;
-(char)_canPresentViewControllerNow;
-(void)_dismissAndPresentViewControllerModallyNow:(id)arg1 animated:(char)arg2 ;
-(char)_isApplicationInBackground;
-(void)_deferPresentViewController:(id)arg1 ;
-(void)_onApplicationWillEnterForeground:(id)arg1 ;
-(void)_onApplicationBecameActiveNotification:(id)arg1 ;
-(char)isVCWaitingForVisible;
-(void)dealloc;
@end

