/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:21:53 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBUserSession, MNLocalNotificationController, MNBusinessWifiNotificationExperimentContext, MNUserStore, MNBusinessWifiUserFetcher;

@interface MNBusinessWifiNotificationPusher : NSObject {

	FBUserSession* _session;
	MNLocalNotificationController* _notificationController;
	MNBusinessWifiNotificationExperimentContext* _experimentContext;
	MNUserStore* _userStore;
	MNBusinessWifiUserFetcher* _userFetcher;

}
-(id)initWithSession:(id)arg1 userStore:(id)arg2 ;
-(char)_shouldPostNotificationForWifiEntryAtBusiness:(id)arg1 ;
-(void)_postLocalNotificationForBusiness:(id)arg1 toUserWithName:(id)arg2 ;
-(id)_notificationForBusiness:(id)arg1 forUserWithName:(id)arg2 ;
-(id)_notificationNameForBusinessType:(int)arg1 ;
-(void)_didPostNotificationForBusiness:(id)arg1 ;
-(id)_notificationMessageForUserWithName:(id)arg1 ;
-(void)_initExperimentContextIfNecessary;
-(id)_lastNotificationPostDateForBusiness:(id)arg1 ;
-(void)_saveNotificationPostDateForBusiness:(id)arg1 ;
-(void)postLocalNotificationForBusinessIfApplicable:(id)arg1 ;
@end

