/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:54 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
@class FBMobileConfigFactory, NSMutableDictionary;

@interface MNConfigManager : NSObject {

	FBMobileConfigFactory* _configFactory;
	NSMutableDictionary* _configContexts;
	mutex _cachedContextsLock;

}
+(id)sessionlessManager;
-(char)getBool:(unsigned long long)arg1 forConfig:(unsigned)arg2 ;
-(id)getString:(unsigned long long)arg1 forConfig:(unsigned)arg2 ;
-(void)logShadowResultForParam:(unsigned long long)arg1 forConfig:(unsigned)arg2 withValue:(char)arg3 ;
-(id)initWithMobileConfigFactory:(id)arg1 ;
-(id)cachedConfigValues;
-(double)getDouble:(unsigned long long)arg1 forConfig:(unsigned)arg2 ;
-(long long)getInt64:(unsigned long long)arg1 forConfig:(unsigned)arg2 ;
-(id)_contextForConfig:(unsigned)arg1 ;
-(char)getBool:(unsigned long long)arg1 forConfig:(unsigned)arg2 withDefault:(char)arg3 ;
-(char)getLatestBool:(unsigned long long)arg1 forConfig:(unsigned)arg2 ;
-(char)getLatestBool:(unsigned long long)arg1 forConfig:(unsigned)arg2 withDefault:(char)arg3 ;
-(long long)getInt64:(unsigned long long)arg1 forConfig:(unsigned)arg2 withDefault:(long long)arg3 ;
-(double)getDouble:(unsigned long long)arg1 forConfig:(unsigned)arg2 withDefault:(double)arg3 ;
-(id)getString:(unsigned long long)arg1 forConfig:(unsigned)arg2 withDefault:(id)arg3 ;
-(void)cacheContext:(id)arg1 withIdentifier:(unsigned)arg2 ;
@end

