/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:21:54 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MNAbstractComposerTrayExtension.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MNComposerOverflowTabViewControllerDelegate.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBClassProvidable.h>

@protocol FBProvider, MNModalPresentation;
@class MNComposerOverflowTabViewController, MNPlatformComposerGatingChecker, MNPhotoImageRequester, UIViewController, FBLazyCreator, NSArray, NSString;

@interface MNComposerOverflowExtension : MNAbstractComposerTrayExtension <MNComposerOverflowTabViewControllerDelegate, FBClassProvidable> {

	id<FBProvider> _composerOverflowTabViewControllerProvider;
	MNComposerOverflowTabViewController* _composerOverflowTabViewController;
	MNPlatformComposerGatingChecker* _platformComposerGatingChecker;
	id<MNModalPresentation> _modalPresenter;
	MNPhotoImageRequester* _imageRequester;
	UIViewController* _presentedNavigationController;
	FBLazyCreator* _composerIconCreator;
	NSArray* _extensions;
	unsigned _badgeCount;

}

@property (assign,nonatomic,__weak) id<MNComposerOverflowExtensionDelegate> delegate; 
@property (nonatomic,copy) NSArray * extensions;                                                   //@synthesize extensions=_extensions - In the implementation block
@property (assign,nonatomic) unsigned badgeCount;                                                  //@synthesize badgeCount=_badgeCount - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(id)_composerIcon;
-(void)didSelect:(char)arg1 source:(int)arg2 ;
-(char)shouldPresent:(char)arg1 source:(int)arg2 ;
-(id)viewControllerForPresentation;
-(void)_updateComposerOverflowTabViewController;
-(void)_presentOverflowTabAsModal;
-(void)_initModalNavigationControllerIfNeeded;
-(void)_dismissModalOverflowTabWithCompletion:(/*^block*/id)arg1 ;
-(void)_releaseComposerOverflowTabViewController;
-(void)_initComposerOverflowTabViewControllerIfNeeded;
-(char)_isModalOverflowTabPresented;
-(void)composerOverflowTabViewController:(id)arg1 didSelectItemWithExtensionIdentifier:(id)arg2 ;
-(void)composerOverflowTabViewController:(id)arg1 didSelectContent:(id)arg2 ;
-(void)composerOverflowTabViewControllerDidBecomeActive;
-(void)updateOverflownTabBarItems;
-(void)dismissModalOverflowTabIfPresented;
-(int)category;
-(id)tabBarItem;
-(void)setBadgeCount:(unsigned)arg1 ;
-(unsigned)badgeCount;
-(NSArray *)extensions;
-(void)setExtensions:(NSArray *)arg1 ;
-(id)extensionIdentifier;
@end

