/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:21:52 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>

@class MNBusinessNavigationHandler, FBMemMessengerRetailShipment, NSString;

@interface MNCommerceDeliveryUpdateActionButtonHelper : NSObject <UITableViewDataSource, UITableViewDelegate> {

	MNBusinessNavigationHandler* _navigationHandler;
	FBMemMessengerRetailShipment* _shipment;
	NSString* _businessID;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)_commerceCellStyle;
-(id)initWithNavigationHandler:(id)arg1 ;
-(void)_configureCell:(id)arg1 withTitle:(id)arg2 disabled:(char)arg3 ;
-(void)_didTapChangeShipping;
-(void)_didTapViewOrderDetails;
-(void)setShipment:(id)arg1 businessID:(id)arg2 ;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
@end

