/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:21:58 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MNNuxViewDelegate.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBClassProvidable.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBMMessageSendListening.h>

@protocol MNActionNuxPresenter, MNHawtLikeNuxControllerDelegate;
@class MNUserSettings, FBUserSession, MNHawtLikeNuxView, NSString;

@interface MNHawtLikeNuxController : NSObject <MNNuxViewDelegate, FBClassProvidable, FBMMessageSendListening> {

	MNUserSettings* _userSettings;
	FBUserSession* _session;
	MNHawtLikeNuxView* _hawtLikeNuxView;
	double _timeHawtLikeNuxPresented;
	char _hasUsedLikeThisSession;
	id<MNActionNuxPresenter> _actionNuxPresenter;
	id<MNHawtLikeNuxControllerDelegate> _delegate;

}

@property (nonatomic,retain) id<MNActionNuxPresenter> actionNuxPresenter;                      //@synthesize actionNuxPresenter=_actionNuxPresenter - In the implementation block
@property (assign,nonatomic,__weak) id<MNHawtLikeNuxControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(void)didEnqueueMessage:(id)arg1 ;
-(void)didPublishMessage:(id)arg1 ;
-(void)didSendMessage:(id)arg1 ;
-(void)didPutMessageBackInQueue:(id)arg1 ;
-(void)didCancelMessage:(id)arg1 ;
-(void)didFailMessage:(id)arg1 error:(id)arg2 ;
-(void)willRetryMessage:(id)arg1 ;
-(void)message:(id)arg1 didUpdateUploadProgress:(double)arg2 ;
-(char)isHawtLikeNuxPresented;
-(void)setActionNuxPresenter:(id<MNActionNuxPresenter>)arg1 ;
-(void)dismissHawtLikeNux;
-(void)updateHawtLikeNux;
-(void)_cancelDelayedHawtLikeNuxPresentation;
-(char)_shouldPresentHawtLikeNux;
-(void)_presentHawtLikeNuxDelayed;
-(void)_dismissHawtLikeNuxUserInitiated:(char)arg1 ;
-(void)_presentHawtLikeNux;
-(void)_initHawtLikeNuxIfNeeded;
-(char)_canPresentHawtLikeNux;
-(void)_logNuxDismissalUserInitiated:(char)arg1 ;
-(void)_updateLikeStickerSentStateWith:(id)arg1 ;
-(void)nuxViewDidTapToDismiss:(id)arg1 ;
-(id<MNActionNuxPresenter>)actionNuxPresenter;
-(void)setDelegate:(id<MNHawtLikeNuxControllerDelegate>)arg1 ;
-(id<MNHawtLikeNuxControllerDelegate>)delegate;
-(void)reset;
@end

