/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:00 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MNInAppNotificationViewDataSource.h>

@class NSString, UIView;

@interface MNInAppNotificationActionMessageDataSource : NSObject <MNInAppNotificationViewDataSource> {

	NSString* _title;
	NSString* _message;
	UIView* _imageView;
	/*^block*/id _action;

}

@property (nonatomic,copy) NSString * title;                        //@synthesize title=_title - In the implementation block
@property (nonatomic,copy) NSString * message;                      //@synthesize message=_message - In the implementation block
@property (assign,nonatomic) UIView * imageView;                    //@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,copy) id action;                               //@synthesize action=_action - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithTitle:(id)arg1 message:(id)arg2 imageView:(id)arg3 actionBlock:(/*^block*/id)arg4 ;
-(void)startAction;
-(id)inAppNotificationTitle;
-(id)inAppNotificationMessage;
-(id)inAppNotificationImageView;
-(void)setTitle:(NSString *)arg1 ;
-(id)action;
-(NSString *)title;
-(void)setAction:(id)arg1 ;
-(NSString *)message;
-(UIView *)imageView;
-(void)setMessage:(NSString *)arg1 ;
-(void)setImageView:(UIView *)arg1 ;
@end

