/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:21:51 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <UIKit/UIScrollView.h>

@protocol MNPaymentsView;
@class MNPaymentsActorsHeaderView, FBPaymentsPeerToPeerTransferReceiptBodyView, MNPaymentsTransferReceiptPaymentIdView, UIView;

@interface MNPaymentsTransferReceiptView : UIScrollView {

	MNPaymentsActorsHeaderView* _headerView;
	FBPaymentsPeerToPeerTransferReceiptBodyView* _bodyView;
	MNPaymentsTransferReceiptPaymentIdView* _paymentIdView;
	UIView* _topExtraInfoSeperatorView;
	UIView*<MNPaymentsView> _extraInfoView;

}

@property (nonatomic,retain) UIView*<MNPaymentsView> extraInfoView;              //@synthesize extraInfoView=_extraInfoView - In the implementation block
-(id)initWithFrame:(CGRect)arg1 receiptHeaderView:(id)arg2 receiptBodyView:(id)arg3 extraInfoView:(id)arg4 paymentIdView:(id)arg5 ;
-(void)setExtraInfoView:(UIView*<MNPaymentsView>)arg1 ;
-(void)presentWithHeaderViewModel:(id)arg1 bodyViewModel:(id)arg2 extraInfoViewModel:(id)arg3 paymentIdViewModel:(id)arg4 ;
-(UIView*<MNPaymentsView>)extraInfoView;
-(void)layoutSubviews;
-(void)_updateContentSize;
@end

