/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:21:47 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <UIKit/UIView.h>

@protocol MNRegistrationExistingAccountViewDelegate;
@class MNHeaderView, MNButton, MNLoadingIndicator, UIImage, MNStackedContainerView;

@interface MNRegistrationExistingAccountView : UIView {

	MNHeaderView* _headerView;
	MNButton* _loginWithFacebookButton;
	MNButton* _createNewAccountButton;
	MNLoadingIndicator* _interstitialLoadingIndicator;
	char _showsInterstitialLoadingIndicator;
	char _showsExistingAccountLoginLoadingIndicator;
	UIImage* _existingAccountProfilePhoto;
	MNStackedContainerView* _stackedContainerView;
	id<MNRegistrationExistingAccountViewDelegate> _delegate;

}

@property (assign,nonatomic) char showsInterstitialLoadingIndicator;                                     //@synthesize showsInterstitialLoadingIndicator=_showsInterstitialLoadingIndicator - In the implementation block
@property (assign,nonatomic) char showsExistingAccountLoginLoadingIndicator;                             //@synthesize showsExistingAccountLoginLoadingIndicator=_showsExistingAccountLoginLoadingIndicator - In the implementation block
@property (nonatomic,retain) UIImage * existingAccountProfilePhoto;                                      //@synthesize existingAccountProfilePhoto=_existingAccountProfilePhoto - In the implementation block
@property (nonatomic,readonly) MNStackedContainerView * stackedContainerView;                            //@synthesize stackedContainerView=_stackedContainerView - In the implementation block
@property (assign,nonatomic,__weak) id<MNRegistrationExistingAccountViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)_loginWithFacebookButtonPressed;
-(void)_createNewAccountButtonPressed;
-(void)_layoutStackedContainerView;
-(void)_layoutLoadingIndicator;
-(id)initWithFrame:(CGRect)arg1 existingAccount:(id)arg2 ;
-(void)setShowsExistingAccountLoginLoadingIndicator:(char)arg1 ;
-(void)setShowsInterstitialLoadingIndicator:(char)arg1 ;
-(void)setExistingAccountProfilePhoto:(UIImage *)arg1 ;
-(char)showsInterstitialLoadingIndicator;
-(char)showsExistingAccountLoginLoadingIndicator;
-(UIImage *)existingAccountProfilePhoto;
-(MNStackedContainerView *)stackedContainerView;
-(void)setDelegate:(id<MNRegistrationExistingAccountViewDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<MNRegistrationExistingAccountViewDelegate>)delegate;
@end

