/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:23 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MNRichMediaUploadListener <NSObject>
@required
-(void)uploadDidSucceed:(id)arg1 withContentFBID:(id)arg2 metrics:(id)arg3;
-(void)uploadDidFail:(id)arg1 withFailureReason:(unsigned)arg2 isResumable:(char)arg3 metrics:(id)arg4;
-(void)uploadWasCancelled:(id)arg1 metrics:(id)arg2;
-(void)uploadHasProgressed:(id)arg1 withProgressInformation:(MNRichMediaUploadJobProgressInformation)arg2;

@end

