/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:21:48 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MNSessionStateMachineDelegate.h>

@protocol FBMAppProperties, FBProvider, OS_dispatch_queue, MNSessionStateMachineTransitionHandlerDelegate;
@class UIApplication, FBAPISessionStore, FBUserSession, MNServiceController, NSObject, MNLigerAdapter, MNAppEventMonitor;

@interface MNSessionStateMachineTransitionHandler : NSObject <MNSessionStateMachineDelegate> {

	UIApplication* _application;
	FBAPISessionStore* _apiSessionStore;
	id<FBMAppProperties> _appProperties;
	FBUserSession* _session;
	MNServiceController* _serviceController;
	id<FBProvider> _experimentManagerProvider;
	id<FBProvider> _mobileConfigFactoryProvider;
	id<FBProvider> _stateRestorationStrategyProvider;
	id<FBProvider> _storeOpenerProvider;
	id<FBProvider> _syncStoreProvider;
	id<FBProvider> _messagingStoreProvider;
	id<FBProvider> _backgroundPolicyDeciderProvider;
	NSObject*<OS_dispatch_queue> _storeOpeningQueue;
	MNLigerAdapter* _ligerAdapter;
	MNAppEventMonitor* _eventMonitor;
	BOOL _mobileConfigEnabled;
	id<MNSessionStateMachineTransitionHandlerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<MNSessionStateMachineTransitionHandlerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)initWithApplication:(id)arg1 session:(id)arg2 apiSessionStore:(id)arg3 appProperties:(id)arg4 serviceController:(id)arg5 experimentManagerProvider:(id)arg6 mobileConfigFactoryProvider:(id)arg7 stateRestorationStrategyProvider:(id)arg8 storeOpenerProvider:(id)arg9 syncStoreProvider:(id)arg10 messagingStoreProvider:(id)arg11 ligerAdapter:(id)arg12 ;
-(void)willTransitionFromStateNotReadyForApplicationState:(int)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)willTransitionFromStateReadyForApplicationState:(int)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)willTransitionFromStateBackgroundOnlyForApplicationState:(int)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)willTransitionFromStateRestoreCompleteForApplicationState:(int)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)willTransitionFromStateCompleteForApplicationState:(int)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)willTransitionFromStatePresentedLoggedInUIForApplicationState:(int)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)_configureNetwork:(id)arg1 ;
-(void)_configureFBAnalytics:(id)arg1 ;
-(void)_startBackgroundServices:(int)arg1 callback:(/*^block*/id)arg2 ;
-(void)_openStoresAndRestoreState:(int)arg1 withCompletionBlock:(/*^block*/id)arg2 ;
-(void)_startForegroundServices:(int)arg1 callback:(/*^block*/id)arg2 ;
-(void)_presentLoggedInUI:(int)arg1 ;
-(void)_restoreStateInStore:(id)arg1 callback:(/*^block*/id)arg2 ;
-(void)_openStores:(/*^block*/id)arg1 ;
-(void)disableMobileConfig;
-(void)setDelegate:(id<MNSessionStateMachineTransitionHandlerDelegate>)arg1 ;
-(id<MNSessionStateMachineTransitionHandlerDelegate>)delegate;
@end

