/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:21:42 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MessengerCompressed-iphoneos-arm64,iphoneos-armv7-Structs.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBActionableTableViewCell.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MNThreadPreviewing.h>

@class UIImageView, UILabel, UIButton, MNLoadingView, MNReceiptStateView, FBTypingIndicatorView, FBRectangleWithRoundedCornerView, FBUserSession, MNThreadRow, MNThreadCellConfiguration, MNThreadCellResources, MNProfileImageView, MNSeenHeadListView, MNInboxImpressionLoggingData, NSString;

@interface MNThreadCell : FBActionableTableViewCell <MNThreadPreviewing> {

	UIImageView* _presenceIndicator;
	UILabel* _threadNameLabel;
	UILabel* _snippetLabel;
	UILabel* _timestampLabel;
	UILabel* _promotedLabel;
	UIButton* _statusIndicator;
	MNLoadingView* _messageSendingIndicator;
	MNReceiptStateView* _receiptStateView;
	char _drawCellAsSelected;
	UIButton* _moreButton;
	UIButton* _muteButton;
	UIButton* _unmuteButton;
	UIButton* _deleteButton;
	FBTypingIndicatorView* _typingView;
	FBRectangleWithRoundedCornerView* _bubbleView;
	UIButton* _firstCTAButton;
	UIButton* _secondCTAButton;
	FBUserSession* _session;
	MNThreadRow* _threadRow;
	MNThreadCellConfiguration* _configuration;
	MNThreadCellResources* _threadCellResources;
	MNProfileImageView* _profileImageView;
	MNSeenHeadListView* _seenHeadListView;
	MNInboxImpressionLoggingData* _inboxLoggingData;
	UIEdgeInsets _contentInset;

}

@property (nonatomic,copy,readonly) MNThreadRow * threadRow;                                //@synthesize threadRow=_threadRow - In the implementation block
@property (nonatomic,copy,readonly) MNThreadCellConfiguration * configuration;              //@synthesize configuration=_configuration - In the implementation block
@property (nonatomic,retain) MNThreadCellResources * threadCellResources;                   //@synthesize threadCellResources=_threadCellResources - In the implementation block
@property (assign,nonatomic,__weak) id<MNThreadCellDelegate> delegate; 
@property (assign,nonatomic) UIEdgeInsets contentInset;                                     //@synthesize contentInset=_contentInset - In the implementation block
@property (nonatomic,readonly) MNProfileImageView * profileImageView;                       //@synthesize profileImageView=_profileImageView - In the implementation block
@property (nonatomic,readonly) MNSeenHeadListView * seenHeadListView;                       //@synthesize seenHeadListView=_seenHeadListView - In the implementation block
@property (nonatomic,copy) MNInboxImpressionLoggingData * inboxLoggingData;                 //@synthesize inboxLoggingData=_inboxLoggingData - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)previewableThreadAtLocation:(CGPoint)arg1 inView:(id)arg2 ;
-(MNInboxImpressionLoggingData *)inboxLoggingData;
-(void)setInboxLoggingData:(MNInboxImpressionLoggingData *)arg1 ;
-(void)_didTapStatusIndicator:(id)arg1 ;
-(void)_updateCellBackgroundWithSelectedState:(char)arg1 ;
-(void)_didTapCTAButton:(id)arg1 ;
-(MNThreadRow *)threadRow;
-(void)_layoutContentViews;
-(float)_maxTitleWidth;
-(float)_maxSnippetWidth;
-(CGSize)_seenStateListViewSize;
-(CGRect)_frameForReceiptStateWithSize:(CGSize)arg1 ;
-(char)_statusIndicatorShouldRecognizeTaps;
-(CGRect)_frameForPromotedLabelWithSize:(CGSize)arg1 ;
-(float)_maxTextWidth;
-(float)_maxSeenHeadListWidth;
-(float)_receiptStateViewsWidth;
-(void)_updatePromotedLabel;
-(void)_updateCellImagesWithRow:(id)arg1 selectedState:(char)arg2 ;
-(void)_setShowsTyping:(char)arg1 ;
-(void)_updateCTAButtons;
-(void)_updateAccessibilityCustomActions;
-(void)_updateCTAButton:(id)arg1 forAction:(id)arg2 ;
-(void)setDrawCellAsSelected:(char)arg1 ;
-(void)_loadMessageSendingIndicatorIfNeccessary;
-(void)_updateReceiptAndSeenHeadViewsWithReceiptState:(unsigned)arg1 statusIndicatorHidden:(char)arg2 ;
-(void)_updateDrawCellAsSelected;
-(void)_didTapMore:(id)arg1 ;
-(void)_didTapMute:(id)arg1 ;
-(void)_didTapUnmute:(id)arg1 ;
-(void)_didTapDelete:(id)arg1 ;
-(void)_didTapUnmuteAX:(id)arg1 ;
-(void)_didTapMuteAX:(id)arg1 ;
-(void)_didTapDeleteAX:(id)arg1 ;
-(void)_didTapMoreAX:(id)arg1 ;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 session:(id)arg3 ;
-(void)setThreadRow:(id)arg1 configuration:(id)arg2 ;
-(void)loadActionPanelView;
-(MNThreadCellResources *)threadCellResources;
-(void)setThreadCellResources:(MNThreadCellResources *)arg1 ;
-(MNProfileImageView *)profileImageView;
-(MNSeenHeadListView *)seenHeadListView;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(NSString *)description;
-(UIEdgeInsets)contentInset;
-(void)setSelected:(char)arg1 animated:(char)arg2 ;
-(id)accessibilityLabel;
-(void)setContentInset:(UIEdgeInsets)arg1 ;
-(void)setHighlighted:(char)arg1 ;
-(void)setHighlighted:(char)arg1 animated:(char)arg2 ;
-(void)prepareForReuse;
-(void)setSelected:(char)arg1 ;
-(MNThreadCellConfiguration *)configuration;
-(char)isAccessibilityElement;
@end

