/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:21:58 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class FBStringWithRedactedDescription, NSString, NSDictionary, NSArray;

@interface MNThreadContext : FBValueObject <NSCopying> {

	char _isVerified;
	FBStringWithRedactedDescription* _titleString;
	NSString* _contextString;
	NSDictionary* _detailItems;
	NSArray* _imageUrls;

}

@property (nonatomic,copy,readonly) FBStringWithRedactedDescription * titleString;              //@synthesize titleString=_titleString - In the implementation block
@property (nonatomic,copy,readonly) NSString * contextString;                                   //@synthesize contextString=_contextString - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * detailItems;                                 //@synthesize detailItems=_detailItems - In the implementation block
@property (nonatomic,copy,readonly) NSArray * imageUrls;                                        //@synthesize imageUrls=_imageUrls - In the implementation block
@property (nonatomic,readonly) char isVerified;                                                 //@synthesize isVerified=_isVerified - In the implementation block
-(char)isVerified;
-(NSArray *)imageUrls;
-(id)initWithTitleString:(id)arg1 contextString:(id)arg2 detailItems:(id)arg3 imageUrls:(id)arg4 isVerified:(char)arg5 ;
-(NSDictionary *)detailItems;
-(FBStringWithRedactedDescription *)titleString;
-(NSString *)contextString;
@end

