/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:23:01 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBLanguageNameFormatFactory, FBLazyCreator;

@interface MNThreadParticipantNameFormatter : NSObject {

	FBLanguageNameFormatFactory* _languageNameFormatFactory;
	FBLazyCreator* _languageNameFormatCreator;

}
-(id)initWithLanguageNameFormatFactory:(id)arg1 ;
-(id)shortNameForUser:(id)arg1 ;
-(id)nameForUser:(id)arg1 ;
-(id)shortNameForUserId:(id)arg1 inUserSet:(id)arg2 ;
-(id)nameForConversationContact:(id)arg1 ;
-(id)shortNameForConversationContact:(id)arg1 ;
-(id)nameListForUsers:(id)arg1 customizationInfo:(id)arg2 useFullName:(char)arg3 truncateAt:(unsigned)arg4 ;
-(id)nameListForUsers:(id)arg1 customizationInfo:(id)arg2 formatString:(id)arg3 useFullName:(char)arg4 maxNames:(unsigned)arg5 minNames:(unsigned)arg6 maxWidth:(float)arg7 font:(id)arg8 moreParticipantsFormat:(unsigned)arg9 ;
-(id)shortNameForParticipant:(id)arg1 ;
-(id)nameForParticipant:(id)arg1 ;
-(id)nameForFormattableName:(id)arg1 ;
-(id)shortNameForFormattableName:(id)arg1 ;
-(id)nameListForFormattableNames:(id)arg1 useFullName:(char)arg2 truncateAt:(unsigned)arg3 ;
-(id)nameListForFormattableNames:(id)arg1 formatString:(id)arg2 useFullName:(char)arg3 maxNames:(unsigned)arg4 minNames:(unsigned)arg5 maxWidth:(float)arg6 font:(id)arg7 ;
-(id)nameListForParticipants:(id)arg1 useFullName:(char)arg2 truncateAt:(unsigned)arg3 ;
-(id)nameListForParticipants:(id)arg1 formatString:(id)arg2 useFullName:(char)arg3 maxNames:(unsigned)arg4 minNames:(unsigned)arg5 maxWidth:(float)arg6 font:(id)arg7 ;
-(id)_nameForUserWithName:(id)arg1 email:(id)arg2 ;
-(id)_shortNameForUserWithName:(id)arg1 firstName:(id)arg2 email:(id)arg3 ;
-(id)_repeatedNamesForUsers:(id)arg1 ;
-(id)_shortNameForUser:(id)arg1 inRepeatedNameSet:(id)arg2 ;
-(id)_namesForUsers:(id)arg1 customizationInfo:(id)arg2 useFullName:(char)arg3 ;
-(id)_namesForUserIds:(id)arg1 inUserSet:(id)arg2 customizationInfo:(id)arg3 useFullName:(char)arg4 ;
-(id)_namesForContacts:(id)arg1 useFullName:(char)arg2 ;
-(id)_namesForFormattableNames:(id)arg1 useFullName:(char)arg2 ;
-(id)_sizeLimitedJoinedStringForNames:(id)arg1 formatString:(id)arg2 maxNames:(unsigned)arg3 minNames:(unsigned)arg4 maxWidth:(float)arg5 font:(id)arg6 moreParticipantsFormat:(unsigned)arg7 ;
-(id)_formatName:(id)arg1 ;
-(id)nameListForUserIds:(id)arg1 inUserSet:(id)arg2 customizationInfo:(id)arg3 truncateAt:(unsigned)arg4 ;
-(id)nameListForConversationContacts:(id)arg1 useFullName:(char)arg2 truncateAt:(unsigned)arg3 ;
-(id)nameListForUserIds:(id)arg1 inUserSet:(id)arg2 customizationInfo:(id)arg3 formatString:(id)arg4 maxNames:(unsigned)arg5 minNames:(unsigned)arg6 maxWidth:(float)arg7 font:(id)arg8 ;
-(id)nameListForConversationContacts:(id)arg1 formatString:(id)arg2 useFullName:(char)arg3 maxNames:(unsigned)arg4 minNames:(unsigned)arg5 maxWidth:(float)arg6 font:(id)arg7 ;
@end

