/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:18 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MNSuggestedContactsRetriever.h>
#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/MNFriendListModelControllerDelegate.h>

@protocol MNFriendListModelController, MNSuggestedContactsRetrieverDelegate;
@class MNUserSortRankPolicy, NSString;

@interface MNTopContactsRetriever : NSObject <MNSuggestedContactsRetriever, MNFriendListModelControllerDelegate> {

	id<MNFriendListModelController> _friendListModelController;
	MNUserSortRankPolicy* _userSortRankPolicy;
	id<MNSuggestedContactsRetrieverDelegate> _delegate;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) id<MNSuggestedContactsRetrieverDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)friendListModelController:(id)arg1 didLoadConversationPeople:(id)arg2 ;
-(id)initWithUserSortRankPolicy:(id)arg1 friendListModelController:(id)arg2 ;
-(void)startRetrievingSuggestedContacts;
-(void)stopRetrievingSuggestedContacts;
-(void)setDelegate:(id<MNSuggestedContactsRetrieverDelegate>)arg1 ;
-(void)dealloc;
-(id<MNSuggestedContactsRetrieverDelegate>)delegate;
@end

