/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:22:25 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PMATimelineHeaderDataQuery : NSObject
+(id)graphQLQueryWithAfterCursor:(id)arg1 callToActionFormFieldsCount:(id)arg2 commentOrder:(id)arg3 contextItemIconSize:(id)arg4 coverPhotoResolution:(id)arg5 device:(id)arg6 entityCardContext:(id)arg7 entityCardContextRedirectedFromEntityId:(id)arg8 entityCardContextSurface:(id)arg9 feedbackIncludeSeenBy:(id)arg10 firstCount:(id)arg11 formatType:(id)arg12 genericAttachmentFallbackSquareImageDimension:(id)arg13 genericAttachmentLargeSquareImageDimension:(id)arg14 genericAttachmentPortraitImageHeight:(id)arg15 genericAttachmentPortraitImageWidth:(id)arg16 genericAttachmentSmallCoverImageHeight:(id)arg17 genericAttachmentSmallCoverImageWidth:(id)arg18 genericAttachmentSmallSquareImageDimension:(id)arg19 genericAttachmentTallCoverImageHeight:(id)arg20 genericAttachmentTallCoverImageWidth:(id)arg21 genericAttachmentTallCoverImageWidthNoScale:(id)arg22 inChannelsExperiment:(id)arg23 includeAdminInfo:(id)arg24 includeNegativeFeedbackActions:(id)arg25 includeProfileBadge:(id)arg26 includeProfileVideo:(id)arg27 mediaType:(id)arg28 numBylines:(id)arg29 pageId:(id)arg30 profileVideoQuality:(id)arg31 renderLocation:(id)arg32 scale:(id)arg33 shouldFetchFeedExpandedComments:(id)arg34 shouldFetchLikeSentence:(id)arg35 shouldFetchTopLevelComments:(id)arg36 shouldCheckStories:(id)arg37 shouldFetchCommentInteractors:(id)arg38 shouldFetchFriendCommenters:(id)arg39 shouldFetchInterestingRepliers:(id)arg40 shouldShowCtaButton:(id)arg41 sourceId:(id)arg42 storyCheckCount:(id)arg43 topicFeedsNewsFeedPills:(id)arg44 videoThumbnailSize:(id)arg45 videoChannelEntryPageId:(id)arg46 videoChannelEntryPoint:(id)arg47 voiceoverEnabled:(id)arg48 ;
@end

