/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 14, 2016 at 2:23:04 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/B4BDDC65-4400-4BC5-A974-2245FB5B0846/MessengerCompressed-iphoneos-arm64,iphoneos-armv7.app/MessengerCompressed-iphoneos-arm64,iphoneos-armv7
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessengerCompressed-iphoneos-arm64,iphoneos-armv7/PBGeneratedMessage.h>

@class NSData;

@interface TSProtoWhisperMessage : PBGeneratedMessage {

	unsigned hasRatchetKey_ : 1;
	unsigned hasCiphertext_ : 1;
	unsigned hasCounter_ : 1;
	unsigned hasPreviousCounter_ : 1;
	NSData* ratchetKey;
	NSData* ciphertext;
	unsigned long counter;
	unsigned long previousCounter;

}

@property (retain) NSData * ratchetKey; 
@property (assign) unsigned long counter; 
@property (assign) unsigned long previousCounter; 
@property (retain) NSData * ciphertext; 
+(id)parseFromData:(id)arg1 ;
+(id)builderWithPrototype:(id)arg1 ;
+(id)parseFromData:(id)arg1 extensionRegistry:(id)arg2 ;
+(id)parseFromInputStream:(id)arg1 ;
+(id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2 ;
+(id)parseFromCodedInputStream:(id)arg1 ;
+(id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2 ;
+(id)defaultInstance;
+(void)initialize;
+(id)builder;
-(void)setRatchetKey:(NSData *)arg1 ;
-(void)setPreviousCounter:(unsigned long)arg1 ;
-(void)setCiphertext:(NSData *)arg1 ;
-(char)hasCiphertext;
-(char)hasCounter;
-(char)hasRatchetKey;
-(NSData *)ratchetKey;
-(unsigned long)previousCounter;
-(NSData *)ciphertext;
-(char)hasPreviousCounter;
-(void)writeToCodedOutputStream:(id)arg1 ;
-(long)serializedSize;
-(void)writeDescriptionTo:(id)arg1 withIndent:(id)arg2 ;
-(void)setHasRatchetKey:(char)arg1 ;
-(void)setHasCounter:(char)arg1 ;
-(void)setHasPreviousCounter:(char)arg1 ;
-(void)setHasCiphertext:(char)arg1 ;
-(id)toBuilder;
-(id)defaultInstance;
-(id)init;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(unsigned long)counter;
-(void)setCounter:(unsigned long)arg1 ;
-(id)builder;
-(char)isInitialized;
@end

