/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:48 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/ADJLogger.h>

@protocol ADJLogger
@required
-(void)info:(id)arg1;
-(void)debug:(id)arg1;
-(void)verbose:(id)arg1;
-(void)assert:(id)arg1;
-(void)setLogLevel:(int)arg1;
-(void)error:(id)arg1;
-(void)warn:(id)arg1;

@end


@interface ADJLogger : NSObject <ADJLogger> {

	int _loglevel;

}

@property (assign,nonatomic) int loglevel;              //@synthesize loglevel=_loglevel - In the implementation block
+(int)LogLevelFromString:(id)arg1 ;
-(void)info:(id)arg1 ;
-(void)debug:(id)arg1 ;
-(void)verbose:(id)arg1 ;
-(int)loglevel;
-(void)logLevel:(id)arg1 format:(id)arg2 parameters:(void*)arg3 ;
-(void)assert:(id)arg1 ;
-(void)setLogLevel:(int)arg1 ;
-(void)error:(id)arg1 ;
-(void)warn:(id)arg1 ;
-(void)setLoglevel:(int)arg1 ;
@end

