/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:49 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/Spotify-Structs.h>
#import <Spotify/CLSCrashReport.h>

@class NSString, NSDictionary, NSDate, CLSInternalReport;

@interface CLSReport : NSObject <CLSCrashReport> {

	CLSInternalReport* _internalReport;
	unsigned _internalKVCounter;
	unsigned _userKVCounter;
	NSString* _internalCompactedKVFile;
	NSString* _internalIncrementalKVFile;
	NSString* _userCompactedKVFile;
	NSString* _userIncrementalKVFile;

}

@property (nonatomic,copy,readonly) NSString * identifier; 
@property (nonatomic,copy,readonly) NSDictionary * customKeys; 
@property (nonatomic,copy,readonly) NSString * bundleVersion; 
@property (nonatomic,copy,readonly) NSString * bundleShortVersionString; 
@property (nonatomic,copy,readonly) NSDate * dateCreated; 
@property (nonatomic,copy,readonly) NSString * OSVersion; 
@property (nonatomic,copy,readonly) NSString * OSBuildVersion; 
@property (nonatomic,readonly) char isCrash; 
@property (nonatomic,copy) NSString * userIdentifier; 
@property (nonatomic,copy) NSString * userName; 
@property (nonatomic,copy) NSString * userEmail; 
@property (nonatomic,readonly) CLSInternalReport * internalReport;                    //@synthesize internalReport=_internalReport - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy,readonly) NSDate * crashedOnDate; 
-(char)isCrash;
-(NSDictionary *)customKeys;
-(NSString *)OSBuildVersion;
-(void)setObjectValue:(id)arg1 forKey:(id)arg2 ;
-(id)initWithInternalReport:(id)arg1 ;
-(CLSInternalReport *)internalReport;
-(SCD_Struct_CL62)internalKVStorage;
-(SCD_Struct_CL62)userKVStorage;
-(void)recordValue:(id)arg1 forUserKey:(id)arg2 ;
-(void)recordValue:(id)arg1 forInternalKey:(id)arg2 ;
-(NSDate *)crashedOnDate;
-(NSString *)userIdentifier;
-(NSString *)userName;
-(NSDate *)dateCreated;
-(NSString *)identifier;
-(void)setUserEmail:(NSString *)arg1 ;
-(NSString *)userEmail;
-(NSString *)bundleVersion;
-(NSString *)OSVersion;
-(void)setUserName:(NSString *)arg1 ;
-(void)setUserIdentifier:(NSString *)arg1 ;
-(NSString *)bundleShortVersionString;
@end

