/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:52 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/HUBViewControllerFactory.h>

@protocol HUBImageLoaderFactory, HUBContentReloadPolicy, HUBComponentLayoutManager;
@class HUBViewModelLoaderFactoryImplementation, HUBFeatureRegistryImplementation, HUBComponentRegistryImplementation, HUBInitialViewModelRegistry, NSString;

@interface HUBViewControllerFactoryImplementation : NSObject <HUBViewControllerFactory> {

	HUBViewModelLoaderFactoryImplementation* _viewModelLoaderFactory;
	id<HUBImageLoaderFactory> _imageLoaderFactory;
	HUBFeatureRegistryImplementation* _featureRegistry;
	HUBComponentRegistryImplementation* _componentRegistry;
	HUBInitialViewModelRegistry* _initialViewModelRegistry;
	id<HUBContentReloadPolicy> _defaultContentReloadPolicy;
	id<HUBComponentLayoutManager> _componentLayoutManager;

}

@property (nonatomic,readonly) HUBViewModelLoaderFactoryImplementation * viewModelLoaderFactory;              //@synthesize viewModelLoaderFactory=_viewModelLoaderFactory - In the implementation block
@property (nonatomic,readonly) id<HUBImageLoaderFactory> imageLoaderFactory;                                  //@synthesize imageLoaderFactory=_imageLoaderFactory - In the implementation block
@property (nonatomic,readonly) HUBFeatureRegistryImplementation * featureRegistry;                            //@synthesize featureRegistry=_featureRegistry - In the implementation block
@property (nonatomic,readonly) HUBComponentRegistryImplementation * componentRegistry;                        //@synthesize componentRegistry=_componentRegistry - In the implementation block
@property (nonatomic,readonly) HUBInitialViewModelRegistry * initialViewModelRegistry;                        //@synthesize initialViewModelRegistry=_initialViewModelRegistry - In the implementation block
@property (nonatomic,readonly) id<HUBContentReloadPolicy> defaultContentReloadPolicy;                         //@synthesize defaultContentReloadPolicy=_defaultContentReloadPolicy - In the implementation block
@property (nonatomic,readonly) id<HUBComponentLayoutManager> componentLayoutManager;                          //@synthesize componentLayoutManager=_componentLayoutManager - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id<HUBImageLoaderFactory>)imageLoaderFactory;
-(char)canCreateViewControllerForViewURI:(id)arg1 ;
-(id)createViewControllerForViewURI:(id)arg1 ;
-(HUBComponentRegistryImplementation *)componentRegistry;
-(HUBFeatureRegistryImplementation *)featureRegistry;
-(HUBViewModelLoaderFactoryImplementation *)viewModelLoaderFactory;
-(id<HUBContentReloadPolicy>)defaultContentReloadPolicy;
-(id<HUBComponentLayoutManager>)componentLayoutManager;
-(HUBInitialViewModelRegistry *)initialViewModelRegistry;
-(id)initWithViewModelLoaderFactory:(id)arg1 imageLoaderFactory:(id)arg2 featureRegistry:(id)arg3 componentRegistry:(id)arg4 initialViewModelRegistry:(id)arg5 defaultContentReloadPolicy:(id)arg6 componentLayoutManager:(id)arg7 ;
@end

