/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:23 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/Spotify-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class IDVariantData;

@interface IDTableCell : NSObject <NSCopying> {

	char _dirty;
	char _visible;
	char _placeholderImageIdDirty;
	unsigned _type;
	int _placeholderImageId;
	IDVariantData* _data;

}

@property (assign) unsigned type;                               //@synthesize type=_type - In the implementation block
@property (assign) char dirty;                                  //@synthesize dirty=_dirty - In the implementation block
@property (assign,nonatomic) char visible;                      //@synthesize visible=_visible - In the implementation block
@property (assign) int placeholderImageId;                      //@synthesize placeholderImageId=_placeholderImageId - In the implementation block
@property (assign) char placeholderImageIdDirty;                //@synthesize placeholderImageIdDirty=_placeholderImageIdDirty - In the implementation block
@property (nonatomic,retain) IDVariantData * data;              //@synthesize data=_data - In the implementation block
+(id)tableCellWithInteger:(int)arg1 ;
+(id)tableCellWithImageData:(id)arg1 ;
+(id)tableCellWithString:(id)arg1 ;
+(id)tableCellWithImageData:(id)arg1 placeholderImageId:(int)arg2 ;
+(id)tableCellWithTextId:(int)arg1 ;
+(id)tableCellWithImageId:(int)arg1 ;
-(int)placeholderImageId;
-(char)placeholderImageIdDirty;
-(void)setPlaceholderImageIdDirty:(char)arg1 ;
-(void)setPlaceholderImageId:(int)arg1 ;
-(id)init;
-(void)setType:(unsigned)arg1 ;
-(unsigned)type;
-(id)copyWithZone:(NSZone*)arg1 ;
-(IDVariantData *)data;
-(void)setData:(IDVariantData *)arg1 ;
-(char)visible;
-(void)setVisible:(char)arg1 ;
-(void)setDirty:(char)arg1 ;
-(char)dirty;
@end

