/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:20 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NielsenAppApiDelegate;
@class NSDictionary, NielsenAppApi;

@interface NlsErrorConstructor : NSObject {

	NSDictionary* _lastError;
	NSDictionary* _lastEvent;
	NielsenAppApi* _appApi;
	id<NielsenAppApiDelegate> _delegate;

}

@property (retain) NSDictionary * lastError;                        //@synthesize lastError=_lastError - In the implementation block
@property (retain) NSDictionary * lastEvent;                        //@synthesize lastEvent=_lastEvent - In the implementation block
@property (__weak) NielsenAppApi * appApi;                          //@synthesize appApi=_appApi - In the implementation block
@property (__weak) id<NielsenAppApiDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)setLastErrorForCode:(int)arg1 withSystemError:(id)arg2 andException:(id)arg3 ;
-(id)initWithAppApi:(id)arg1 delegate:(id)arg2 ;
-(NSDictionary *)lastEvent;
-(void)setAppApi:(NielsenAppApi *)arg1 ;
-(id)setLastEventForCode:(int)arg1 ;
-(NielsenAppApi *)appApi;
-(void)setLastEvent:(NSDictionary *)arg1 ;
-(void)setDelegate:(id<NielsenAppApiDelegate>)arg1 ;
-(id<NielsenAppApiDelegate>)delegate;
-(void)setLastError:(NSDictionary *)arg1 ;
-(NSDictionary *)lastError;
@end

