/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:27 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSData;

@interface SDLPolicyDataParser : NSObject {

	unsigned char _protocolVersion;
	char _isResponseRequired;
	char _isHighBandwidth;
	char _isSigned;
	char _isEncrypted;
	char _hasESN;
	unsigned char _serviceType;
	unsigned char _commandType;
	char _CPUDestination;
	unsigned char _encryptionKeyIndex;
	unsigned char _messageStatus;
	unsigned long _payloadSize;
	NSData* _ESN;
	unsigned long _moduleMessageId;
	unsigned long _serverMessageId;
	NSData* _initializationVector;
	NSData* _payload;
	NSData* _signatureTag;

}

@property (assign) unsigned char protocolVersion;                 //@synthesize protocolVersion=_protocolVersion - In the implementation block
@property (assign) char isResponseRequired;                       //@synthesize isResponseRequired=_isResponseRequired - In the implementation block
@property (assign) char isHighBandwidth;                          //@synthesize isHighBandwidth=_isHighBandwidth - In the implementation block
@property (assign) char isSigned;                                 //@synthesize isSigned=_isSigned - In the implementation block
@property (assign) char isEncrypted;                              //@synthesize isEncrypted=_isEncrypted - In the implementation block
@property (assign) char hasESN;                                   //@synthesize hasESN=_hasESN - In the implementation block
@property (assign) unsigned char serviceType;                     //@synthesize serviceType=_serviceType - In the implementation block
@property (assign) unsigned char commandType;                     //@synthesize commandType=_commandType - In the implementation block
@property (assign) char CPUDestination;                           //@synthesize CPUDestination=_CPUDestination - In the implementation block
@property (assign) unsigned char encryptionKeyIndex;              //@synthesize encryptionKeyIndex=_encryptionKeyIndex - In the implementation block
@property (assign) unsigned long payloadSize;                     //@synthesize payloadSize=_payloadSize - In the implementation block
@property (retain) NSData * ESN;                                  //@synthesize ESN=_ESN - In the implementation block
@property (assign) unsigned long moduleMessageId;                 //@synthesize moduleMessageId=_moduleMessageId - In the implementation block
@property (assign) unsigned long serverMessageId;                 //@synthesize serverMessageId=_serverMessageId - In the implementation block
@property (assign) unsigned char messageStatus;                   //@synthesize messageStatus=_messageStatus - In the implementation block
@property (retain) NSData * initializationVector;                 //@synthesize initializationVector=_initializationVector - In the implementation block
@property (retain) NSData * payload;                              //@synthesize payload=_payload - In the implementation block
@property (retain) NSData * signatureTag;                         //@synthesize signatureTag=_signatureTag - In the implementation block
-(void)setIsResponseRequired:(char)arg1 ;
-(void)setIsHighBandwidth:(char)arg1 ;
-(void)setIsEncrypted:(char)arg1 ;
-(void)setHasESN:(char)arg1 ;
-(void)setCPUDestination:(char)arg1 ;
-(void)setEncryptionKeyIndex:(unsigned char)arg1 ;
-(char)isHighBandwidth;
-(char)hasESN;
-(void)setESN:(NSData *)arg1 ;
-(NSData *)ESN;
-(void)setModuleMessageId:(unsigned long)arg1 ;
-(void)setServerMessageId:(unsigned long)arg1 ;
-(void)setMessageStatus:(unsigned char)arg1 ;
-(void)setInitializationVector:(NSData *)arg1 ;
-(NSData *)initializationVector;
-(void)setSignatureTag:(NSData *)arg1 ;
-(char)isResponseRequired;
-(char)CPUDestination;
-(unsigned char)encryptionKeyIndex;
-(unsigned long)moduleMessageId;
-(unsigned long)serverMessageId;
-(unsigned char)messageStatus;
-(NSData *)signatureTag;
-(id)unwrap:(id)arg1 ;
-(void)parsePolicyData:(id)arg1 ;
-(id)description;
-(NSData *)payload;
-(void)setPayload:(NSData *)arg1 ;
-(void)setIsSigned:(char)arg1 ;
-(void)setProtocolVersion:(unsigned char)arg1 ;
-(unsigned char)protocolVersion;
-(void)setServiceType:(unsigned char)arg1 ;
-(unsigned char)serviceType;
-(char)isSigned;
-(char)isEncrypted;
-(void)setPayloadSize:(unsigned long)arg1 ;
-(unsigned long)payloadSize;
-(void)setCommandType:(unsigned char)arg1 ;
-(unsigned char)commandType;
@end

