/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:26 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/SDLProtocolListener.h>
#import <libobjc.A.dylib/NSStreamDelegate.h>

@class SDLLockScreenManager, SDLAbstractProtocol, SDLAbstractTransport, SDLTimer, NSString, SDLStreamingMediaManager, NSMutableSet, NSSet;

@interface SDLProxy : NSObject <SDLProtocolListener, NSStreamDelegate> {

	unsigned char _version;
	unsigned char _bulkSessionID;
	char _isConnected;
	char _alreadyDestructed;
	SDLLockScreenManager* _lsm;
	SDLAbstractProtocol* _protocol;
	SDLAbstractTransport* _transport;
	SDLTimer* _startSessionTimer;
	NSString* _debugConsoleGroupName;
	SDLStreamingMediaManager* _streamingMediaManager;
	NSMutableSet* _mutableProxyListeners;

}

@property (retain) SDLAbstractProtocol * protocol;                                          //@synthesize protocol=_protocol - In the implementation block
@property (retain) SDLAbstractTransport * transport;                                        //@synthesize transport=_transport - In the implementation block
@property (copy,readonly) NSSet * proxyListeners; 
@property (retain) SDLTimer * startSessionTimer;                                            //@synthesize startSessionTimer=_startSessionTimer - In the implementation block
@property (copy) NSString * debugConsoleGroupName;                                          //@synthesize debugConsoleGroupName=_debugConsoleGroupName - In the implementation block
@property (copy,readonly) NSString * proxyVersion; 
@property (nonatomic,retain) SDLStreamingMediaManager * streamingMediaManager;              //@synthesize streamingMediaManager=_streamingMediaManager - In the implementation block
@property (nonatomic,retain) NSMutableSet * mutableProxyListeners;                          //@synthesize mutableProxyListeners=_mutableProxyListeners - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)enableSiphonDebug;
+(void)disableSiphonDebug;
-(id)initWithTransport:(id)arg1 protocol:(id)arg2 delegate:(id)arg3 ;
-(void)invokeMethodOnDelegates:(SEL)arg1 withObject:(id)arg2 ;
-(NSMutableSet *)mutableProxyListeners;
-(SDLTimer *)startSessionTimer;
-(void)setStartSessionTimer:(SDLTimer *)arg1 ;
-(void)notifyProxyClosed;
-(void)handleProtocolMessage:(id)arg1 ;
-(void)handleRPCDictionary:(id)arg1 ;
-(void)handleRPCUnregistered:(id)arg1 ;
-(void)handleRegisterAppInterfaceResponse:(id)arg1 ;
-(void)handleSyncPData:(id)arg1 ;
-(void)handleSystemRequest:(id)arg1 ;
-(void)handleSystemRequestResponse:(id)arg1 ;
-(void)handleAfterHMIStatus:(id)arg1 ;
-(void)handleAfterDriverDistraction:(id)arg1 ;
-(NSString *)proxyVersion;
-(void)sendEncodedSyncPData:(id)arg1 toURL:(id)arg2 withTimeout:(id)arg3 ;
-(void)handleSystemRequestProprietary:(id)arg1 ;
-(void)handleSystemRequestLockScreenIconURL:(id)arg1 ;
-(id)validateAndParseSystemRequest:(id)arg1 ;
-(void)uploadForBodyDataDictionary:(id)arg1 URLString:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(NSSet *)proxyListeners;
-(void)syncPDataNetworkRequestCompleteWithData:(id)arg1 response:(id)arg2 error:(id)arg3 ;
-(SDLStreamingMediaManager *)streamingMediaManager;
-(void)handleRpcMessage:(id)arg1 ;
-(void)putFileStream:(id)arg1 withRequest:(id)arg2 ;
-(void)setStreamingMediaManager:(SDLStreamingMediaManager *)arg1 ;
-(void)setMutableProxyListeners:(NSMutableSet *)arg1 ;
-(void)sendRPC:(id)arg1 ;
-(void)onProtocolClosed;
-(void)handleProtocolStartSessionACK:(unsigned char)arg1 sessionID:(unsigned char)arg2 version:(unsigned char)arg3 ;
-(void)onProtocolMessageReceived:(id)arg1 ;
-(void)onProtocolOpened;
-(void)onError:(id)arg1 exception:(id)arg2 ;
-(void)destructObjects;
-(void)sendRPCRequest:(id)arg1 ;
-(NSString *)debugConsoleGroupName;
-(void)setDebugConsoleGroupName:(NSString *)arg1 ;
-(void)stream:(id)arg1 handleEvent:(unsigned)arg2 ;
-(void)dispose;
-(void)dealloc;
-(SDLAbstractProtocol *)protocol;
-(SDLAbstractTransport *)transport;
-(void)setTransport:(SDLAbstractTransport *)arg1 ;
-(void)removeDelegate:(id)arg1 ;
-(void)addDelegate:(id)arg1 ;
-(void)setProtocol:(SDLAbstractProtocol *)arg1 ;
@end

