/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:19 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/Spotify-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol SPStackedNavigationScrollViewDelegate;
@class UIPanGestureRecognizer, CADisplayLink, NSString;

@interface SPStackedNavigationScrollView : UIView <UIGestureRecognizerDelegate> {

	CGPoint _actualOffset;
	CGPoint _targetOffset;
	CGPoint _scrollAtStartOfPan;
	float _scrollDoneMargin;
	char _runningRunLoop;
	char _inRunLoop;
	id<SPStackedNavigationScrollViewDelegate> _delegate;
	UIPanGestureRecognizer* _scrollRec;
	CADisplayLink* _scrollAnimationTimer;
	/*^block*/id _onScrollDone;

}

@property (assign,nonatomic) CGPoint contentOffset;                                                  //@synthesize targetOffset=_targetOffset - In the implementation block
@property (assign,nonatomic,__weak) id<SPStackedNavigationScrollViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) UIPanGestureRecognizer * panGestureRecognizer; 
@property (nonatomic,retain) UIPanGestureRecognizer * scrollRec;                                     //@synthesize scrollRec=_scrollRec - In the implementation block
@property (nonatomic,retain) CADisplayLink * scrollAnimationTimer;                                   //@synthesize scrollAnimationTimer=_scrollAnimationTimer - In the implementation block
@property (nonatomic,copy) id onScrollDone;                                                          //@synthesize onScrollDone=_onScrollDone - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)containerForViewController:(id)arg1 ;
-(float)scrollOffsetForAligningPage:(id)arg1 position:(int)arg2 ;
-(void)scrollGesture:(id)arg1 ;
-(void)setScrollRec:(UIPanGestureRecognizer *)arg1 ;
-(NSRange)scrollRangeForPageContainer:(id)arg1 ;
-(float)scrollOffsetForAligningPageWithLeftEdge:(id)arg1 ;
-(float)scrollOffsetForAligningPageWithRightEdge:(id)arg1 ;
-(void)setOnScrollDone:(id)arg1 ;
-(void)startRunLoop;
-(void)scrollAndSnapWithVelocity:(float)arg1 animated:(char)arg2 ;
-(UIPanGestureRecognizer *)scrollRec;
-(CADisplayLink *)scrollAnimationTimer;
-(void)setScrollAnimationTimer:(CADisplayLink *)arg1 ;
-(id)onScrollDone;
-(void)updateContainerVisibilityByShowing:(char)arg1 byHiding:(char)arg2 ;
-(void)scrollAnimationFrame:(id)arg1 ;
-(void)animateToTargetScrollOffset;
-(NSRange)scrollRange;
-(void)snapToClosest;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<SPStackedNavigationScrollViewDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<SPStackedNavigationScrollViewDelegate>)delegate;
-(char)gestureRecognizerShouldBegin:(id)arg1 ;
-(UIPanGestureRecognizer *)panGestureRecognizer;
-(CGPoint)contentOffset;
-(void)setContentOffset:(CGPoint)arg1 animated:(char)arg2 ;
-(void)setContentOffset:(CGPoint)arg1 ;
-(void)stopRunLoop;
@end

