/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:28 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/SPTAdBillboardTouchControllerDelegate.h>

@protocol SPTWebViewFactory, SPTPlayer, SPTAdEventLogger;
@class SPTAdsViewModel, SPTAdCosmosRequestHandler, SPTAdFeaturedActionHandler, MetaViewController, SPTAdBillboardWindow, SPTAdBillboardTouchController, NSString;

@interface SPTAdBillboardManager : NSObject <SPTAdBillboardTouchControllerDelegate> {

	char _playerMaximized;
	char _previewSubscribed;
	SPTAdsViewModel* _adsViewModel;
	SPTAdCosmosRequestHandler* _cosmosRequestHandler;
	SPTAdFeaturedActionHandler* _actionHandler;
	id<SPTWebViewFactory> _webViewFactory;
	id<SPTPlayer> _player;
	MetaViewController* _metaViewController;
	id<SPTAdEventLogger> _eventLogger;
	SPTAdBillboardWindow* _window;
	SPTAdBillboardTouchController* _touchController;
	double _lastActiveTimestamp;

}

@property (nonatomic,__weak,readonly) SPTAdsViewModel * adsViewModel;                                //@synthesize adsViewModel=_adsViewModel - In the implementation block
@property (nonatomic,__weak,readonly) SPTAdCosmosRequestHandler * cosmosRequestHandler;              //@synthesize cosmosRequestHandler=_cosmosRequestHandler - In the implementation block
@property (nonatomic,__weak,readonly) SPTAdFeaturedActionHandler * actionHandler;                    //@synthesize actionHandler=_actionHandler - In the implementation block
@property (nonatomic,__weak,readonly) id<SPTWebViewFactory> webViewFactory;                          //@synthesize webViewFactory=_webViewFactory - In the implementation block
@property (nonatomic,__weak,readonly) id<SPTPlayer> player;                                          //@synthesize player=_player - In the implementation block
@property (nonatomic,__weak,readonly) MetaViewController * metaViewController;                       //@synthesize metaViewController=_metaViewController - In the implementation block
@property (nonatomic,__weak,readonly) id<SPTAdEventLogger> eventLogger;                              //@synthesize eventLogger=_eventLogger - In the implementation block
@property (assign,nonatomic) double lastActiveTimestamp;                                             //@synthesize lastActiveTimestamp=_lastActiveTimestamp - In the implementation block
@property (nonatomic,retain) SPTAdBillboardWindow * window;                                          //@synthesize window=_window - In the implementation block
@property (nonatomic,retain) SPTAdBillboardTouchController * touchController;                        //@synthesize touchController=_touchController - In the implementation block
@property (assign,nonatomic) char playerMaximized;                                                   //@synthesize playerMaximized=_playerMaximized - In the implementation block
@property (assign,nonatomic) char previewSubscribed;                                                 //@synthesize previewSubscribed=_previewSubscribed - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(MetaViewController *)metaViewController;
-(void)addObservers;
-(void)removeObservers;
-(void)subscribeToPreview;
-(void)setLastActiveTimestamp:(double)arg1 ;
-(void)fetchBillboard;
-(char)shouldDisplayBillboard;
-(SPTAdsViewModel *)adsViewModel;
-(void)displayBillboardEntity:(id)arg1 ;
-(void)removeWindow;
-(void)maximizePlayerIfNecessary:(/*^block*/id)arg1 ;
-(id<SPTAdEventLogger>)eventLogger;
-(SPTAdBillboardTouchController *)touchController;
-(id)provideWindow;
-(void)minimizePlayerIfNecessary:(/*^block*/id)arg1 ;
-(double)lastActiveTimestamp;
-(void)setPlayerMaximized:(char)arg1 ;
-(char)playerMaximized;
-(char)previewSubscribed;
-(SPTAdCosmosRequestHandler *)cosmosRequestHandler;
-(void)setPreviewSubscribed:(char)arg1 ;
-(void)adBillboardController:(id)arg1 didReceiveActionTouch:(id)arg2 ;
-(void)adBillboardControllerDidReceiveDismissTouch:(id)arg1 ;
-(id)initWithAdsViewModel:(id)arg1 cosmosRequestHandler:(id)arg2 actionHandler:(id)arg3 webViewFactory:(id)arg4 player:(id)arg5 metaViewController:(id)arg6 eventLogger:(id)arg7 ;
-(void)registeredAdResolver:(id)arg1 ;
-(void)forceDisplayBillboardWithCompletion:(/*^block*/id)arg1 ;
-(id<SPTWebViewFactory>)webViewFactory;
-(void)setTouchController:(SPTAdBillboardTouchController *)arg1 ;
-(id<SPTPlayer>)player;
-(void)dealloc;
-(SPTAdBillboardWindow *)window;
-(void)applicationDidBecomeActive:(id)arg1 ;
-(void)applicationWillResignActive:(id)arg1 ;
-(void)setWindow:(SPTAdBillboardWindow *)arg1 ;
-(SPTAdFeaturedActionHandler *)actionHandler;
@end

