/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:29 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/Spotify-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <Spotify/SPTAdEntityViewModelDelegate.h>

@class SPTAdsViewModel, SPTAdEntityViewModel, SPTAdEntityView, SPTProgressView, NSString;

@interface SPTAdsVideoViewController : UIViewController <UIGestureRecognizerDelegate, SPTAdEntityViewModelDelegate> {

	SPTAdsViewModel* _adsViewModel;
	SPTAdEntityViewModel* _entityModel;
	SPTAdEntityView* _entityView;
	id _playbackObserver;
	SPTProgressView* _progressView;

}

@property (assign,nonatomic,__weak) SPTAdsViewModel * adsViewModel;              //@synthesize adsViewModel=_adsViewModel - In the implementation block
@property (nonatomic,retain) SPTAdEntityViewModel * entityModel;                 //@synthesize entityModel=_entityModel - In the implementation block
@property (nonatomic,retain) SPTAdEntityView * entityView;                       //@synthesize entityView=_entityView - In the implementation block
@property (nonatomic,retain) id playbackObserver;                                //@synthesize playbackObserver=_playbackObserver - In the implementation block
@property (nonatomic,retain) SPTProgressView * progressView;                     //@synthesize progressView=_progressView - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(SPTAdEntityView *)entityView;
-(void)setAdsViewModel:(SPTAdsViewModel *)arg1 ;
-(SPTAdsViewModel *)adsViewModel;
-(void)adEntityViewModel:(id)arg1 setLoading:(char)arg2 ;
-(void)updatePlayButtonState;
-(void)adEntityViewModel:(id)arg1 didStartPlaying:(char)arg2 ;
-(void)adEntityViewModel:(id)arg1 videoIsAvailable:(char)arg2 ;
-(id)initWithViewModel:(id)arg1 entityViewModel:(id)arg2 ;
-(void)hideAdView;
-(SPTAdEntityViewModel *)entityModel;
-(void)skipAd;
-(void)setPlaybackObserver:(id)arg1 ;
-(void)setEntityView:(SPTAdEntityView *)arg1 ;
-(void)becomeActive:(id)arg1 ;
-(id)playbackObserver;
-(void)setEntityModel:(SPTAdEntityViewModel *)arg1 ;
-(void)handleRotation:(int)arg1 ;
-(void)showUI;
-(void)hideUI;
-(void)dealloc;
-(unsigned)supportedInterfaceOrientations;
-(char)shouldAutorotate;
-(char)canBecomeFirstResponder;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2 ;
-(void)remoteControlReceivedWithEvent:(id)arg1 ;
-(void)setProgressView:(SPTProgressView *)arg1 ;
-(SPTProgressView *)progressView;
-(void)handleTap;
-(void)togglePlayPause;
-(void)resignActive:(id)arg1 ;
-(void)interruption:(id)arg1 ;
@end

