/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:32 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol SPTCollectionFiltering <NSObject>
@property (nonatomic,copy) NSString * textFilter; 
@property (getter=isContentFiltered,nonatomic,readonly) char contentFiltered; 
@property (assign,nonatomic) char showsOnlyOfflinedContent; 
@required
-(char)isContentFiltered;
-(void)resetFilters;
-(void)setTextFilter:(id)arg1;
-(char)showsOnlyOfflinedContent;
-(void)setShowsOnlyOfflinedContent:(char)arg1;
-(NSString *)textFilter;

@end

