/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:33 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary;

@interface SPTEqualizerCurve : NSObject {

	NSDictionary* _values;

}

@property (nonatomic,copy) NSDictionary * values;              //@synthesize values=_values - In the implementation block
+(id)equalizerCurveWithValues:(id)arg1 ;
-(void)setValue:(double)arg1 forFrequency:(double)arg2 ;
-(double)valueForFrequency:(double)arg1 ;
-(id)initWithValues:(id)arg1 ;
-(void)setValues:(NSDictionary *)arg1 ;
-(NSDictionary *)values;
@end

