/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:53 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/Spotify-Structs.h>
#import <Spotify/LogObserver.h>

@class SPCore, NSHashTable, NSString;

@interface SPTLog : NSObject <LogObserver> {

	SPCore* _core;
	NSHashTable* _observers;
	shared_ptr<coreobjc::LogObserver>* _log_observer;

}

@property (assign,nonatomic,__weak) SPCore * core;                                         //@synthesize core=_core - In the implementation block
@property (nonatomic,retain) NSHashTable * observers;                                      //@synthesize observers=_observers - In the implementation block
@property (assign,nonatomic) shared_ptr<coreobjc::LogObserver>* log_observer;              //@synthesize log_observer=_log_observer - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)createAndInstallLogWithObserver:(id)arg1 core:(id)arg2 identificator:(id)arg3 ;
-(SPCore *)core;
-(void)setCore:(SPCore *)arg1 ;
-(void)logObserver:(LogObserver*)arg1 receivedLogLine:(id)arg2 fromModule:(id)arg3 file:(id)arg4 line:(int)arg5 threadId:(unsigned long long)arg6 at:(id)arg7 logLevel:(int)arg8 ;
-(id)initWithCore:(id)arg1 identificator:(id)arg2 ;
-(shared_ptr<coreobjc::LogObserver>*)log_observer;
-(void)checkHasObservers;
-(void)writeLine:(id)arg1 fromModule:(id)arg2 file:(id)arg3 line:(int)arg4 threadId:(unsigned long long)arg5 at:(id)arg6 logLevel:(int)arg7 ;
-(void)setLog_observer:(shared_ptr<coreobjc::LogObserver>*)arg1 ;
-(void)dealloc;
-(void)addObserver:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
-(void)setObservers:(NSHashTable *)arg1 ;
-(NSHashTable *)observers;
-(void)install;
@end

