/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:37 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/SPTNowPlayingCarouselContentProviderFactory.h>
#import <Spotify/SPTLocalSettingsObserver.h>
#import <Spotify/SPTAbbaFeatureFlagsObserver.h>
#import <Spotify/SPTLyricsFeature.h>

@protocol SPTClientSessionService, SPTSettingsFeature, SPTLocalSettings, SPTAbbaFeature, SPTNetworkFeature, SPTPlayerFeature, NowPlayingFeature, SPTTinkerbellFeature, SPTCoreService, SPContextMenuFeature, SPTAbbaFeatureFlags, SPTPlayer, SPTLyricsOnboardingManager;
@class SPTLyricsService, SPTLyricsLoggingService, SPTLyricsNowPlayingBarContentProvider, NSString, SPTAllocationContext;

@interface SPTLyricsFeatureImplementation : NSObject <SPTNowPlayingCarouselContentProviderFactory, SPTLocalSettingsObserver, SPTAbbaFeatureFlagsObserver, SPTLyricsFeature> {

	char _hasRegisteredProviders;
	id<SPTClientSessionService> _clientSessionService;
	id<SPTSettingsFeature> _settings;
	id<SPTLocalSettings> _localSettings;
	id<SPTAbbaFeature> _abbaFeature;
	id<SPTNetworkFeature> _networkFeature;
	id<SPTPlayerFeature> _playerFeature;
	id<NowPlayingFeature> _nowPlayingFeature;
	id<SPTTinkerbellFeature> _tinkerbellFeature;
	id<SPTCoreService> _coreService;
	id<SPContextMenuFeature> _contextMenuFeature;
	id<SPTAbbaFeatureFlags> _abbaFeatureFlags;
	id<SPTPlayer> _player;
	SPTLyricsService* _lyricsService;
	SPTLyricsLoggingService* _loggingService;
	id<SPTLyricsOnboardingManager> _onboardingManager;
	SPTLyricsNowPlayingBarContentProvider* _barContentProvider;

}

@property (assign,nonatomic,__weak) id<SPTClientSessionService> clientSessionService;                 //@synthesize clientSessionService=_clientSessionService - In the implementation block
@property (assign,nonatomic,__weak) id<SPTSettingsFeature> settings;                                  //@synthesize settings=_settings - In the implementation block
@property (nonatomic,retain) id<SPTLocalSettings> localSettings;                                      //@synthesize localSettings=_localSettings - In the implementation block
@property (assign,nonatomic,__weak) id<SPTAbbaFeature> abbaFeature;                                   //@synthesize abbaFeature=_abbaFeature - In the implementation block
@property (assign,nonatomic,__weak) id<SPTNetworkFeature> networkFeature;                             //@synthesize networkFeature=_networkFeature - In the implementation block
@property (assign,nonatomic,__weak) id<SPTPlayerFeature> playerFeature;                               //@synthesize playerFeature=_playerFeature - In the implementation block
@property (assign,nonatomic,__weak) id<NowPlayingFeature> nowPlayingFeature;                          //@synthesize nowPlayingFeature=_nowPlayingFeature - In the implementation block
@property (assign,nonatomic,__weak) id<SPTTinkerbellFeature> tinkerbellFeature;                       //@synthesize tinkerbellFeature=_tinkerbellFeature - In the implementation block
@property (assign,nonatomic,__weak) id<SPTCoreService> coreService;                                   //@synthesize coreService=_coreService - In the implementation block
@property (assign,nonatomic,__weak) id<SPContextMenuFeature> contextMenuFeature;                      //@synthesize contextMenuFeature=_contextMenuFeature - In the implementation block
@property (nonatomic,retain) id<SPTAbbaFeatureFlags> abbaFeatureFlags;                                //@synthesize abbaFeatureFlags=_abbaFeatureFlags - In the implementation block
@property (nonatomic,retain) id<SPTPlayer> player;                                                    //@synthesize player=_player - In the implementation block
@property (nonatomic,retain) SPTLyricsService * lyricsService;                                        //@synthesize lyricsService=_lyricsService - In the implementation block
@property (nonatomic,retain) SPTLyricsLoggingService * loggingService;                                //@synthesize loggingService=_loggingService - In the implementation block
@property (nonatomic,retain) id<SPTLyricsOnboardingManager> onboardingManager;                        //@synthesize onboardingManager=_onboardingManager - In the implementation block
@property (nonatomic,retain) SPTLyricsNowPlayingBarContentProvider * barContentProvider;              //@synthesize barContentProvider=_barContentProvider - In the implementation block
@property (assign,nonatomic) char hasRegisteredProviders;                                             //@synthesize hasRegisteredProviders=_hasRegisteredProviders - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) SPTAllocationContext * allocationContext; 
+(id)serviceDependencies;
+(id)serviceIdentifier;
-(void)setCoreService:(id<SPTCoreService>)arg1 ;
-(id<SPTCoreService>)coreService;
-(void)configureWithServices:(id)arg1 ;
-(void)featureFlagsDidChange:(id)arg1 ;
-(void)localSettingsDidChange:(id)arg1 ;
-(id<SPTAbbaFeatureFlags>)abbaFeatureFlags;
-(void)setAbbaFeatureFlags:(id<SPTAbbaFeatureFlags>)arg1 ;
-(id<SPTLocalSettings>)localSettings;
-(void)setLocalSettings:(id<SPTLocalSettings>)arg1 ;
-(void)setClientSessionService:(id<SPTClientSessionService>)arg1 ;
-(void)setNetworkFeature:(id<SPTNetworkFeature>)arg1 ;
-(id<SPTNetworkFeature>)networkFeature;
-(id<SPTClientSessionService>)clientSessionService;
-(void)setPlayerFeature:(id<SPTPlayerFeature>)arg1 ;
-(id<SPTPlayerFeature>)playerFeature;
-(void)setAbbaFeature:(id<SPTAbbaFeature>)arg1 ;
-(id<SPTAbbaFeature>)abbaFeature;
-(id<SPContextMenuFeature>)contextMenuFeature;
-(void)setContextMenuFeature:(id<SPContextMenuFeature>)arg1 ;
-(void)registerFeatureSettingsPage;
-(void)setOnboardingManager:(id<SPTLyricsOnboardingManager>)arg1 ;
-(id<SPTLyricsOnboardingManager>)onboardingManager;
-(void)setNowPlayingFeature:(id<NowPlayingFeature>)arg1 ;
-(void)registerViewControllerURI;
-(void)registerCarouselContentProvider;
-(id<NowPlayingFeature>)nowPlayingFeature;
-(char)isLyricsEnabled;
-(id)providePlayer;
-(id)createProvider;
-(SPTLyricsLoggingService *)loggingService;
-(void)setLoggingService:(SPTLyricsLoggingService *)arg1 ;
-(void)setTinkerbellFeature:(id<SPTTinkerbellFeature>)arg1 ;
-(id<SPTTinkerbellFeature>)tinkerbellFeature;
-(SPTLyricsService *)lyricsService;
-(void)setLyricsService:(SPTLyricsService *)arg1 ;
-(void)updateLyricsFeatureRegistration;
-(id)provideLyricsMiniNPVController:(id)arg1 ;
-(id)provideLyricsFullScreenViewController:(id)arg1 ;
-(id)provideBarContentProvider;
-(SPTLyricsNowPlayingBarContentProvider *)barContentProvider;
-(id)provideLyricsService;
-(id)provideLyricsOnboardingManager;
-(void)setBarContentProvider:(SPTLyricsNowPlayingBarContentProvider *)arg1 ;
-(id)provideLoggingService;
-(id)provideOfflineModeState;
-(char)hasRegisteredProviders;
-(void)unregisterViewControllerURI;
-(void)unregisterCarouselContentProvider;
-(void)unregisterBarContentProvider;
-(void)setHasRegisteredProviders:(char)arg1 ;
-(void)registerBarContentProvider;
-(void)registerContextMenuActions;
-(void)setPlayer:(id<SPTPlayer>)arg1 ;
-(id<SPTPlayer>)player;
-(id<SPTSettingsFeature>)settings;
-(void)load;
-(void)setSettings:(id<SPTSettingsFeature>)arg1 ;
-(void)unload;
@end

