/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:39 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/SettingsSection.h>

@protocol SPTLocalSettings;
@class SettingsSwitchTableViewCell;

@interface SPTNowPlayingHideAlbumArtworkSettingsSection : SettingsSection {

	SettingsSwitchTableViewCell* _cell;
	id<SPTLocalSettings> _localSettings;

}

@property (nonatomic,retain) SettingsSwitchTableViewCell * cell;              //@synthesize cell=_cell - In the implementation block
@property (nonatomic,retain) id<SPTLocalSettings> localSettings;              //@synthesize localSettings=_localSettings - In the implementation block
-(id<SPTLocalSettings>)localSettings;
-(void)setLocalSettings:(id<SPTLocalSettings>)arg1 ;
-(void)hideAlbumArtworkChanged:(id)arg1 ;
-(id)initWithSettingsViewController:(id)arg1 localSettings:(id)arg2 ;
-(id)cellForRow:(int)arg1 ;
-(void)dealloc;
-(int)numberOfRows;
-(SettingsSwitchTableViewCell *)cell;
-(void)setCell:(SettingsSwitchTableViewCell *)arg1 ;
@end

