/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:39 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/SPTNowPlayingBaseUnitProvider.h>

@protocol SPContextMenuFeature, SPTRunningTestManager, SPTPodcastFeature, SPTAdsManager, SPTAdEventLogger;
@class SPTNowPlayingModel, SPTTheme, SPTLogCenter;

@interface SPTNowPlayingInformationUnitProvider : SPTNowPlayingBaseUnitProvider {

	SPTNowPlayingModel* _model;
	SPTTheme* _theme;
	id<SPContextMenuFeature> _contextMenuFeature;
	SPTLogCenter* _logCenter;
	id<SPTRunningTestManager> _runningTestManager;
	id<SPTPodcastFeature> _podcastFeature;
	id<SPTAdsManager> _adsManager;
	id<SPTAdEventLogger> _adEventLogger;

}

@property (nonatomic,retain) SPTNowPlayingModel * model;                                       //@synthesize model=_model - In the implementation block
@property (nonatomic,retain) SPTTheme * theme;                                                 //@synthesize theme=_theme - In the implementation block
@property (assign,nonatomic,__weak) id<SPContextMenuFeature> contextMenuFeature;               //@synthesize contextMenuFeature=_contextMenuFeature - In the implementation block
@property (assign,nonatomic,__weak) SPTLogCenter * logCenter;                                  //@synthesize logCenter=_logCenter - In the implementation block
@property (assign,nonatomic,__weak) id<SPTRunningTestManager> runningTestManager;              //@synthesize runningTestManager=_runningTestManager - In the implementation block
@property (assign,nonatomic,__weak) id<SPTPodcastFeature> podcastFeature;                      //@synthesize podcastFeature=_podcastFeature - In the implementation block
@property (assign,nonatomic,__weak) id<SPTAdsManager> adsManager;                              //@synthesize adsManager=_adsManager - In the implementation block
@property (nonatomic,retain) id<SPTAdEventLogger> adEventLogger;                               //@synthesize adEventLogger=_adEventLogger - In the implementation block
-(SPTLogCenter *)logCenter;
-(void)setLogCenter:(SPTLogCenter *)arg1 ;
-(id<SPContextMenuFeature>)contextMenuFeature;
-(void)setContextMenuFeature:(id<SPContextMenuFeature>)arg1 ;
-(id<SPTAdsManager>)adsManager;
-(id<SPTAdEventLogger>)adEventLogger;
-(void)setAdsManager:(id<SPTAdsManager>)arg1 ;
-(void)setAdEventLogger:(id<SPTAdEventLogger>)arg1 ;
-(id<SPTPodcastFeature>)podcastFeature;
-(void)setPodcastFeature:(id<SPTPodcastFeature>)arg1 ;
-(id<SPTRunningTestManager>)runningTestManager;
-(void)setRunningTestManager:(id<SPTRunningTestManager>)arg1 ;
-(void)processPlayerStateChange:(id)arg1 ;
-(void)createAdInformationUnit;
-(void)createRunningOnboardingInformationUnit;
-(void)createShowsInformationUnit;
-(void)createRunningInformationUnit;
-(void)createMusicInformationUnit;
-(id)initWithPlayer:(id)arg1 model:(id)arg2 theme:(id)arg3 contextMenuFeature:(id)arg4 runningTestManager:(id)arg5 podcastFeature:(id)arg6 logCenter:(id)arg7 adsManager:(id)arg8 adEventLogger:(id)arg9 ;
-(SPTNowPlayingModel *)model;
-(void)setModel:(SPTNowPlayingModel *)arg1 ;
-(SPTTheme *)theme;
-(void)setTheme:(SPTTheme *)arg1 ;
@end

