/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:39 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/Spotify-Structs.h>
#import <UIKit/UIButton.h>

@class UIColor;

@interface SPTNowPlayingButton : UIButton {

	unsigned _buttonState;
	int _icon;
	UIColor* _iconColor;
	CGSize _iconSize;

}

@property (assign,nonatomic) unsigned buttonState;              //@synthesize buttonState=_buttonState - In the implementation block
@property (assign,nonatomic) int icon;                          //@synthesize icon=_icon - In the implementation block
@property (assign,nonatomic) CGSize iconSize;                   //@synthesize iconSize=_iconSize - In the implementation block
@property (nonatomic,copy) UIColor * iconColor;                 //@synthesize iconColor=_iconColor - In the implementation block
+(id)previousTrackButton;
+(id)nextTrackButton;
+(id)dailyMixNegativeFeedbackButton;
+(id)dailyMixPositiveFeedbackButton;
+(id)titleCloseButton;
+(id)titleQueueButton;
+(id)skipForwardButton;
+(id)skipBackButton;
+(id)thumbUpButton;
+(id)thumbDownButton;
+(id)barOpenButton;
+(id)collectionButton;
+(id)playBarButton;
+(id)userProfileButton;
+(id)button;
+(id)repeatButton;
+(id)shuffleButton;
+(id)playButton;
-(void)setIconColor:(UIColor *)arg1 ;
-(UIColor *)iconColor;
-(void)applyIcon;
-(unsigned)buttonState;
-(void)setButtonState:(unsigned)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(unsigned)state;
-(void)setIcon:(int)arg1 ;
-(int)icon;
-(void)setIconSize:(CGSize)arg1 ;
-(CGSize)iconSize;
@end

