/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:39 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/Spotify-Structs.h>
#import <Spotify/SPTNowPlayingButton.h>
#import <Spotify/SPTNowPlayingRepeatButton.h>

@protocol SPTNowPlayingRepeatButton <NSObject>
@property (assign,nonatomic) unsigned buttonState; 
@required
-(unsigned)buttonState;
-(void)setButtonState:(unsigned)arg1;

@end


@class NSString;

@interface SPTNowPlayingRepeatButton : SPTNowPlayingButton <SPTNowPlayingRepeatButton> {

	CGSize _iconSize;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) unsigned buttonState; 
+(id)button;
-(void)applyIcon;
-(id)initWithFrame:(CGRect)arg1 ;
-(NSString *)description;
-(id)accessibilityLabel;
-(id)accessibilityValue;
-(id)accessibilityHint;
-(void)setIconSize:(CGSize)arg1 ;
-(CGSize)iconSize;
@end

