/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:42 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SPTPlaylistFolderViewModelDelegate <NSObject>
@optional
-(void)playlistFolderViewModelDidUpdate:(id)arg1;
-(void)playlistFolderViewModel:(id)arg1 didFailToRemoveRowAtIndexPath:(id)arg2;
-(void)playlistFolderViewModel:(id)arg1 didRemoveRowAtIndexPath:(id)arg2;
-(void)playlistFolderViewModel:(id)arg1 didChangeObjectWithContext:(id)arg2;
-(void)playlistFolderViewModel:(id)arg1 didChangeOfflineStatusWithContext:(id)arg2;
-(void)playlistFolderViewModelDidBeginiTunesLibrarySync:(id)arg1;
-(void)playlistFolderViewModel:(id)arg1 didUpdateSyncingProgress:(double)arg2;
-(void)playlistFolderViewModelDidEndiTunesLibrarySync:(id)arg1;

@end

