/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:55 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/Spotify-Structs.h>
#import <Spotify/SPTPersistentCachePosixWrapper.h>

@interface SPTPersistentCachePosixWrapperMock : SPTPersistentCachePosixWrapper {

	char _readOverridden;
	int _closeValue;
	long _readValue;
	long _writeValue;
	int _fsyncValue;
	int _statValue;
	long long _lseekValue;

}

@property (assign,nonatomic) int closeValue;                                           //@synthesize closeValue=_closeValue - In the implementation block
@property (assign,nonatomic) long readValue;                                           //@synthesize readValue=_readValue - In the implementation block
@property (assign,getter=isReadOverridden,nonatomic) char readOverridden;              //@synthesize readOverridden=_readOverridden - In the implementation block
@property (assign,nonatomic) long long lseekValue;                                     //@synthesize lseekValue=_lseekValue - In the implementation block
@property (assign,nonatomic) long writeValue;                                          //@synthesize writeValue=_writeValue - In the implementation block
@property (assign,nonatomic) int fsyncValue;                                           //@synthesize fsyncValue=_fsyncValue - In the implementation block
@property (assign,nonatomic) int statValue;                                            //@synthesize statValue=_statValue - In the implementation block
-(int)closeValue;
-(char)isReadOverridden;
-(long)readValue;
-(long long)lseekValue;
-(long)writeValue;
-(int)fsyncValue;
-(int)statValue;
-(void)setCloseValue:(int)arg1 ;
-(void)setReadValue:(long)arg1 ;
-(void)setReadOverridden:(char)arg1 ;
-(void)setLseekValue:(long long)arg1 ;
-(void)setWriteValue:(long)arg1 ;
-(void)setFsyncValue:(int)arg1 ;
-(void)setStatValue:(int)arg1 ;
-(long)read:(int)arg1 buffer:(void*)arg2 bufferSize:(unsigned long)arg3 ;
-(long long)lseek:(int)arg1 seekType:(long long)arg2 seekAmount:(int)arg3 ;
-(long)write:(int)arg1 buffer:(const void*)arg2 bufferSize:(unsigned long)arg3 ;
-(int)fsync:(int)arg1 ;
-(int)stat:(const char*)arg1 statStruct:(stat*)arg2 ;
-(int)close:(int)arg1 ;
@end

