/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:42 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/SPTOfflineObserver.h>
#import <Spotify/SPTITunesLibraryManagerObserver.h>
#import <Spotify/SPTCollectionSorting.h>
#import <Spotify/SPTCollectionFiltering.h>
#import <Spotify/SPTPlaylistExternalEntityFilterList.h>

@protocol SPTPlaylistExternalEntityFilter, SPTPlaylistFolderViewModelDelegate, SPTCollectionLogger, SPTPlaylistModel;
@class NSString, NSURL, SPSession, SPPlaylistContainer, NSMapTable, SPTOfflineManager, SPTPlaylistMigrateStarredManager, SPKVObservation, NSArray, NSMutableOrderedSet;

@interface SPTPlaylistFolderViewModel : NSObject <SPTOfflineObserver, SPTITunesLibraryManagerObserver, SPTCollectionSorting, SPTCollectionFiltering, SPTPlaylistExternalEntityFilterList> {

	char _showsOnlyOfflinedContent;
	char _showAllTracksCell;
	char _showLocalFilesCell;
	char _showCreateNewPlaylistCellInFolderRoot;
	char _showDisplaySectionIndex;
	char _showsOnlyWritablePlaylists;
	char _ascendingSortOrder;
	char _contentFiltered;
	char _isSynchronizing;
	NSString* _textFilter;
	id<SPTPlaylistExternalEntityFilter> _externalEntityFilter;
	id<SPTPlaylistFolderViewModelDelegate> _delegate;
	NSURL* _uri;
	SPSession* _session;
	SPPlaylistContainer* _playlistContainer;
	NSMapTable* _observationMapTable;
	SPTOfflineManager* _offlineManager;
	SPTPlaylistMigrateStarredManager* _starMigrationManager;
	SPKVObservation* _playlistContainerChildrenObservation;
	SPKVObservation* _treeContainerChildrenObservation;
	NSArray* _sectionedItems;
	unsigned _sortColumn;
	id<SPTCollectionLogger> _logger;
	id<SPTPlaylistModel> _playlistModel;
	NSArray* _extraPlaylists;
	NSMutableOrderedSet* _itemsToSynchronize;
	int _totalSynchronized;

}

@property (assign,nonatomic,__weak) id<SPTPlaylistFolderViewModelDelegate> delegate;                //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSURL * uri;                                                           //@synthesize uri=_uri - In the implementation block
@property (nonatomic,copy,readonly) NSString * name; 
@property (assign,nonatomic) char showLocalFilesCell;                                               //@synthesize showLocalFilesCell=_showLocalFilesCell - In the implementation block
@property (assign,nonatomic) char showAllTracksCell;                                                //@synthesize showAllTracksCell=_showAllTracksCell - In the implementation block
@property (assign,nonatomic) char showCreateNewPlaylistCellInFolderRoot;                            //@synthesize showCreateNewPlaylistCellInFolderRoot=_showCreateNewPlaylistCellInFolderRoot - In the implementation block
@property (assign,nonatomic) char showDisplaySectionIndex;                                          //@synthesize showDisplaySectionIndex=_showDisplaySectionIndex - In the implementation block
@property (assign,nonatomic) char showsOnlyWritablePlaylists;                                       //@synthesize showsOnlyWritablePlaylists=_showsOnlyWritablePlaylists - In the implementation block
@property (nonatomic,readonly) char isPlaylistFolderRootlist; 
@property (nonatomic,readonly) unsigned numberOfPlaylistContainers; 
@property (nonatomic,readonly) NSArray * sectionIndexTitles; 
@property (nonatomic,readonly) char isEmpty; 
@property (assign,nonatomic,__weak) SPSession * session;                                            //@synthesize session=_session - In the implementation block
@property (nonatomic,retain) SPPlaylistContainer * playlistContainer;                               //@synthesize playlistContainer=_playlistContainer - In the implementation block
@property (nonatomic,retain) NSMapTable * observationMapTable;                                      //@synthesize observationMapTable=_observationMapTable - In the implementation block
@property (assign,nonatomic,__weak) SPTOfflineManager * offlineManager;                             //@synthesize offlineManager=_offlineManager - In the implementation block
@property (nonatomic,retain) SPTPlaylistMigrateStarredManager * starMigrationManager;               //@synthesize starMigrationManager=_starMigrationManager - In the implementation block
@property (nonatomic,retain) SPKVObservation * playlistContainerChildrenObservation;                //@synthesize playlistContainerChildrenObservation=_playlistContainerChildrenObservation - In the implementation block
@property (nonatomic,retain) SPKVObservation * treeContainerChildrenObservation;                    //@synthesize treeContainerChildrenObservation=_treeContainerChildrenObservation - In the implementation block
@property (nonatomic,copy) NSArray * sectionedItems;                                                //@synthesize sectionedItems=_sectionedItems - In the implementation block
@property (assign,nonatomic) unsigned sortColumn;                                                   //@synthesize sortColumn=_sortColumn - In the implementation block
@property (assign,nonatomic) char ascendingSortOrder;                                               //@synthesize ascendingSortOrder=_ascendingSortOrder - In the implementation block
@property (assign,getter=isContentFiltered,nonatomic) char contentFiltered;                         //@synthesize contentFiltered=_contentFiltered - In the implementation block
@property (nonatomic,retain) id<SPTCollectionLogger> logger;                                        //@synthesize logger=_logger - In the implementation block
@property (nonatomic,retain) id<SPTPlaylistModel> playlistModel;                                    //@synthesize playlistModel=_playlistModel - In the implementation block
@property (nonatomic,retain) NSArray * extraPlaylists;                                              //@synthesize extraPlaylists=_extraPlaylists - In the implementation block
@property (assign,nonatomic) char isSynchronizing;                                                  //@synthesize isSynchronizing=_isSynchronizing - In the implementation block
@property (nonatomic,retain) NSMutableOrderedSet * itemsToSynchronize;                              //@synthesize itemsToSynchronize=_itemsToSynchronize - In the implementation block
@property (assign,nonatomic) int totalSynchronized;                                                 //@synthesize totalSynchronized=_totalSynchronized - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSArray * supportedSortColumns; 
@property (nonatomic,copy) NSString * textFilter;                                                   //@synthesize textFilter=_textFilter - In the implementation block
@property (assign,nonatomic) char showsOnlyOfflinedContent;                                         //@synthesize showsOnlyOfflinedContent=_showsOnlyOfflinedContent - In the implementation block
@property (nonatomic,retain) id<SPTPlaylistExternalEntityFilter> externalEntityFilter;              //@synthesize externalEntityFilter=_externalEntityFilter - In the implementation block
-(SPTOfflineManager *)offlineManager;
-(void)offlineStateChangedForEntity:(id)arg1 ;
-(void)setOfflineManager:(SPTOfflineManager *)arg1 ;
-(void)setSortColumn:(unsigned)arg1 ;
-(unsigned)flatIndexForIndexPath:(id)arg1 ;
-(char)isContentFiltered;
-(void)resetFilters;
-(void)setTextFilter:(NSString *)arg1 ;
-(void)setContentFiltered:(char)arg1 ;
-(char)ascendingSortOrder;
-(void)setAscendingSortOrder:(char)arg1 ;
-(NSArray *)supportedSortColumns;
-(unsigned)sortColumn;
-(void)setSortOrderWithColumn:(unsigned)arg1 ascending:(char)arg2 ;
-(char)showsOnlyOfflinedContent;
-(void)setShowsOnlyOfflinedContent:(char)arg1 ;
-(void)iTunesLibraryManagerDidEndSync:(id)arg1 ;
-(void)iTunesLibraryManager:(id)arg1 foundUsyncedSongs:(unsigned)arg2 ;
-(void)iTunesLibraryManager:(id)arg1 didUpdateProgress:(double)arg2 ;
-(id<SPTPlaylistModel>)playlistModel;
-(void)setPlaylistModel:(id<SPTPlaylistModel>)arg1 ;
-(id)titleForItem:(id)arg1 ;
-(void)itemDidChange:(id)arg1 context:(id)arg2 ;
-(void)setShowAllTracksCell:(char)arg1 ;
-(void)setShowLocalFilesCell:(char)arg1 ;
-(void)setShowDisplaySectionIndex:(char)arg1 ;
-(id)URLForRowAtIndexPath:(id)arg1 ;
-(char)canUserAddToPlaylistForRowAtIndexPath:(id)arg1 ;
-(void)logItemSelectedAtIndexPath:(id)arg1 targetURL:(id)arg2 ;
-(id)titleForRowAtIndexPath:(id)arg1 ;
-(unsigned)numberOfPlaylistContainers;
-(SPTPlaylistMigrateStarredManager *)starMigrationManager;
-(void)setStarMigrationManager:(SPTPlaylistMigrateStarredManager *)arg1 ;
-(void)stopObservingPlaylistContainerChildren;
-(SPPlaylistContainer *)playlistContainer;
-(SPKVObservation *)treeContainerChildrenObservation;
-(void)treeContainerChildrenChanged;
-(void)setTreeContainerChildrenObservation:(SPKVObservation *)arg1 ;
-(SPKVObservation *)playlistContainerChildrenObservation;
-(id)observePlaylistContainerChildren;
-(void)setPlaylistContainerChildrenObservation:(SPKVObservation *)arg1 ;
-(NSMapTable *)observationMapTable;
-(void)removeObservers:(id)arg1 context:(id)arg2 ;
-(NSArray *)sectionedItems;
-(void)playlistContainerChildrenChanged;
-(char)isPlaylistFolderRootlist;
-(void)setExtraPlaylists:(NSArray *)arg1 ;
-(void)setPlaylistContainer:(SPPlaylistContainer *)arg1 ;
-(char)showCreateNewPlaylistCellInFolderRoot;
-(char)showAllTracksCell;
-(NSArray *)extraPlaylists;
-(id)playlistForRowAtIndexPath:(id)arg1 ;
-(id)playlistContainerForRowAtIndexPath:(id)arg1 ;
-(char)canDeleteRowAtIndexPath:(id)arg1 ;
-(void)setIsSynchronizing:(char)arg1 ;
-(void)synchronizeItems;
-(NSMutableOrderedSet *)itemsToSynchronize;
-(int)totalSynchronized;
-(void)startSynchronizationWithInterval:(double)arg1 ;
-(char)isSynchronizing;
-(void)setTotalSynchronized:(int)arg1 ;
-(void)markItemForSynchronization:(id)arg1 ;
-(void)unmarkItemForSynchronization:(id)arg1 ;
-(id)flatRootListItems;
-(id<SPTPlaylistExternalEntityFilter>)externalEntityFilter;
-(char)showsOnlyWritablePlaylists;
-(id)itemsBySortingArray:(id)arg1 ;
-(void)setSectionedItems:(NSArray *)arg1 ;
-(void)updateItemList;
-(char)showDisplaySectionIndex;
-(void)externalEntityFilterDidChange:(id)arg1 ;
-(void)setExternalEntityFilter:(id<SPTPlaylistExternalEntityFilter>)arg1 ;
-(id)initWithSession:(id)arg1 offlineManager:(id)arg2 playlistContainer:(id)arg3 uri:(id)arg4 iTunesLibraryManager:(id)arg5 starMigrationManager:(id)arg6 collectionLogger:(id)arg7 playlistModel:(id)arg8 ;
-(void)startObservingPlaylistContainerChildren;
-(void)setShowCreateNewPlaylistCellInFolderRoot:(char)arg1 ;
-(id)subtitleForRowAtIndexPath:(id)arg1 ;
-(id)ownerForRowAtIndexPath:(id)arg1 ;
-(int)numberOfItemsInRowAtIndexPath:(id)arg1 ;
-(int)iconForRowAtIndexPath:(id)arg1 ;
-(int)offlineSyncStatusAtIndexPath:(id)arg1 ;
-(char)isRowAtIndexPathOwnedBySelf:(id)arg1 ;
-(char)isStarredAtIndexPath:(id)arg1 ;
-(id)imageURLForRowAtIndexPath:(id)arg1 ;
-(void)beginObservingRowAtIndexPath:(id)arg1 context:(id)arg2 ;
-(void)endObservingRowAtIndexPath:(id)arg1 context:(id)arg2 ;
-(char)playlistIsSeparatorAtIndexPath:(id)arg1 ;
-(char)toggleItemOfflineStateAtIndexPath:(id)arg1 ;
-(char)showLocalFilesCell;
-(void)setShowsOnlyWritablePlaylists:(char)arg1 ;
-(void)setObservationMapTable:(NSMapTable *)arg1 ;
-(void)setItemsToSynchronize:(NSMutableOrderedSet *)arg1 ;
-(id<SPTCollectionLogger>)logger;
-(void)setLogger:(id<SPTCollectionLogger>)arg1 ;
-(SPSession *)session;
-(void)setDelegate:(id<SPTPlaylistFolderViewModelDelegate>)arg1 ;
-(void)dealloc;
-(int)numberOfRowsInSection:(int)arg1 ;
-(id<SPTPlaylistFolderViewModelDelegate>)delegate;
-(NSString *)name;
-(int)numberOfSections;
-(char)isEmpty;
-(void)load;
-(NSArray *)sectionIndexTitles;
-(void)setSession:(SPSession *)arg1 ;
-(NSString *)textFilter;
-(NSURL *)uri;
-(void)setUri:(NSURL *)arg1 ;
-(void)deleteRowAtIndexPath:(id)arg1 ;
-(id)itemAtIndexPath:(id)arg1 ;
@end

