/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:44 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Spotify/SPTRadioModel.h>

@class NSString, NSURL;

@interface SPTRadioTrack : SPTRadioModel {

	NSString* _title;
	NSString* _artistName;
	NSURL* _artistURI;
	NSString* _albumName;
	NSURL* _albumURI;
	NSURL* _imageURI;
	int _thumbFeedback;
	NSString* _uid;

}

@property (nonatomic,retain) NSString * title;                   //@synthesize title=_title - In the implementation block
@property (nonatomic,retain) NSString * artistName;              //@synthesize artistName=_artistName - In the implementation block
@property (nonatomic,retain) NSURL * artistURI;                  //@synthesize artistURI=_artistURI - In the implementation block
@property (nonatomic,retain) NSString * albumName;               //@synthesize albumName=_albumName - In the implementation block
@property (nonatomic,retain) NSURL * albumURI;                   //@synthesize albumURI=_albumURI - In the implementation block
@property (nonatomic,retain) NSURL * imageURI;                   //@synthesize imageURI=_imageURI - In the implementation block
@property (assign,nonatomic) int thumbFeedback;                  //@synthesize thumbFeedback=_thumbFeedback - In the implementation block
@property (nonatomic,retain) NSString * uid;                     //@synthesize uid=_uid - In the implementation block
-(id)objectRepresentation;
-(char)restoreWithObjectRepresentation:(id)arg1 ;
-(NSURL *)artistURI;
-(void)setArtistURI:(NSURL *)arg1 ;
-(NSURL *)albumURI;
-(NSURL *)imageURI;
-(void)setImageURI:(NSURL *)arg1 ;
-(void)setAlbumURI:(NSURL *)arg1 ;
-(void)setThumbFeedback:(int)arg1 ;
-(int)thumbFeedback;
-(id)createPlayerTrack;
-(NSString *)albumName;
-(void)setAlbumName:(NSString *)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(NSString *)title;
-(NSString *)uid;
-(void)setUid:(NSString *)arg1 ;
-(NSString *)artistName;
-(void)setArtistName:(NSString *)arg1 ;
@end

