/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:47 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SPTAccountProductInformationController;
@interface SPTUpsellFallbackProvider : NSObject {

	id<SPTAccountProductInformationController> _productInformationController;

}

@property (nonatomic,readonly) id<SPTAccountProductInformationController> productInformationController;              //@synthesize productInformationController=_productInformationController - In the implementation block
-(id<SPTAccountProductInformationController>)productInformationController;
-(id)createTrialUpsellForReason:(int)arg1 ;
-(id)createPageForlocalizedHeading:(id)arg1 localizedTitle:(id)arg2 localizedSubtitle:(id)arg3 iconName:(id)arg4 reason:(int)arg5 ;
-(id)actionDataForFallbackUpsell;
-(id)buttonsForFallbackWithAction:(id)arg1 title:(id)arg2 dismissTitle:(id)arg3 ;
-(id)buttonTitleForFallbackUpsell;
-(id)initWithProductInfoController:(id)arg1 ;
-(id)fallbackUpsellForReason:(int)arg1 ;
@end

