/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 18, 2016 at 11:45:21 PM Eastern Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/D2238F36-ED84-40F4-9CB2-8C71CACC8B47/Spotify.app/Spotify
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate;

@interface XVRSpeechData : NSObject {

	NSDate* _time;
	id _data;
	int _type;

}

@property (nonatomic,readonly) NSDate * time;              //@synthesize time=_time - In the implementation block
@property (nonatomic,readonly) id data;                    //@synthesize data=_data - In the implementation block
@property (nonatomic,readonly) int type;                   //@synthesize type=_type - In the implementation block
-(id)initWithData:(id)arg1 type:(int)arg2 time:(id)arg3 ;
-(int)type;
-(id)data;
-(NSDate *)time;
@end

